-- Cust_ID _BAS
USE BAS

-- ALTER Scripts for drop constraints
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='CUST_ADDR_ID_FK')  BEGIN ALTER TABLE CUST_ADDR  DROP CONSTRAINT CUST_ADDR_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJECTCUST_ID_FK')  BEGIN ALTER TABLE PROJECT  DROP CONSTRAINT PROJECTCUST_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='USER_RIGHTS_CUSTOMER_ID_FK')  BEGIN ALTER TABLE USER_RIGHTS  DROP CONSTRAINT USER_RIGHTS_CUSTOMER_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='CUST_PK')  BEGIN ALTER TABLE CUSTOMER  DROP CONSTRAINT CUST_PK; END 


-- Alter scripts for vacrchar
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CUSTOMER' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CUSTOMER  ALTER COLUMN CUST_ID varchar(50) NOT NULL;  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJMGT_TEAM' AND name='CUST_IT' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJMGT_TEAM  ALTER COLUMN CUST_IT varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='EMP_INFO_FOR_CUSTOMER' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE EMP_INFO_FOR_CUSTOMER  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJMGT_USERSTORY' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJMGT_USERSTORY  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='TIMESHEET_SETTINGS' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE TIMESHEET_SETTINGS  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CUST_ADDR' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CUST_ADDR  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT_COURSE_MAPPING' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT_COURSE_MAPPING  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='USER_RIGHTS' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE USER_RIGHTS  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT_PREFERENCE' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT_PREFERENCE  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='Report_CSMUsageCompliance' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE Report_CSMUsageCompliance  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='customer_copy' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE customer_copy  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJMGT_DEFECT' AND name='CUST_IT' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJMGT_DEFECT  ALTER COLUMN CUST_IT varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJMGT_ITERATION' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJMGT_ITERATION  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CONFIGURATION_EXT' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CONFIGURATION_EXT  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJMGT_RELEASE' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJMGT_RELEASE  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJMGT_SUBPROJECT' AND name='CUST_IT' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJMGT_SUBPROJECT  ALTER COLUMN CUST_IT varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJMGT_TASK' AND name='CUST_IT' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJMGT_TASK  ALTER COLUMN CUST_IT varchar(50);  END
 


 
-- ALTER Scripts for create constraints
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME='CUSTOMER' AND CONSTRAINT_NAME ='CUST_PK')  BEGIN ALTER TABLE CUSTOMER  ADD CONSTRAINT CUST_PK PRIMARY KEY (CUST_ID);  END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='CUST_ADDR_ID_FK')  BEGIN ALTER TABLE CUST_ADDR  ADD CONSTRAINT CUST_ADDR_ID_FK  FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJECTCUST_ID_FK')  BEGIN ALTER TABLE PROJECT  ADD CONSTRAINT PROJECTCUST_ID_FK  FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='USER_RIGHTS_CUSTOMER_ID_FK')  BEGIN ALTER TABLE USER_RIGHTS  ADD CONSTRAINT USER_RIGHTS_CUSTOMER_ID_FK  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUST_ID) ; END


