USE BAS
GO
IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getCustomerUsersList' AND TYPE='P')
BEGIN
DROP PROCEDURE getCustomerUsersList         
END
GO
 
CREATE procedure [dbo].getCustomerUsersList 
@custId varchar(50)='-1'
As
Begin 

select  CUSTOMER_USER_ID,CP.CUST_ID, 
P.PROJ_ID,p.PROJ_NM,EMAILID, DISPLAY_NAME 
from customer_projects CP (NOLOCK)
INNER JOIN customer_users CU (NOLOCK)
ON  CP.CUSTOMER_USER_ID=CU.ID   
INNER JOIN PROJECT P (NOLOCK)
ON P.PROJ_ID =CP.PROJ_ID AND ISNULL(P.PROJ_STATUS,'')!='Close' 
where cp.ISACTIVE=1 AND (ISNULL(@custId,'-1')='-1' OR @custId= CP.CUST_ID) AND
ISNULL(CSAT_SURVEY,0)=1
GROUP BY CUSTOMER_USER_ID,CP.CUST_ID, 
P.PROJ_ID,p.PROJ_NM,EMAILID, DISPLAY_NAME 

END







 