
IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getCSSActionitem' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[getCSSActionitem]
END
GO

CREATE PROCEDURE getCSSActionitem   
  
@STARTDATE datetime,  
@ENDDATE datetime   
  
AS          
  
BEGIN       
  
select C.CUST_NM as ACCOUNT,P.PROJ_NM as PROJECT,CB.DISPLAY_NAME as CUSTOMER,E.FRST_NM as PROJECT_MANAGER,CB.EMAIL_ID as CUSTOMER_MAIL,  
SOURCE as SOURCE_CATEGORY, SOURCE_DESCRIPTION, 
FORMAT(CB.SURVEY_SENT_DATE,'yyyy-MM-dd') as SURVEY_SENT_DATE,FORMAT(CB.SURVEY_RECEIVED_DATE,'yyyy-MM-dd') as SURVEY_RECEIVED_DATE,  
PA.DESCRIPTION as ACTION_PLAN_DESCRIPTION, PA.STATUS,  
FORMAT(PA.IDENTIFIED_DATE,'yyyy-MM-dd') as IDENTIFIED_DATE,FORMAT(PA.TARGET_DATE,'yyyy-MM-dd') as TARGET_DATE,  
FORMAT(PA.COMPLETION_DATE,'yyyy-MM-dd') as COMPLETION_DATE,PA.BATCH_CUSTOMER_MONTHLY_ID,PA.PROJECT_ID,PA.CUSTOMER_ID  
  
from PROJECT_ACTIONITEM PA   
inner join PROJECT P on P.PROJ_ID = PA.PROJECT_ID  
inner join CUSTOMER C on C.CUST_ID = PA.CUSTOMER_ID  
inner join CSS_BATCH_CUSTOMER_MONTHLY CB on CB.ID = PA.BATCH_CUSTOMER_MONTHLY_ID  
inner join EMP_INFO E on E.EMP_ID = P.PROJ_PM_EMP_ID  
  
where PA.CUSTOMER_ID = '212100001' and PA.ISACTIVE=1 and CB.ISACTIVE=1 and PA.IDENTIFIED_DATE between @STARTDATE and @ENDDATE  
order by PA.IDENTIFIED_DATE,PROJECT,CUSTOMER desc  
  
END  
GO
