IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getProjectCertificationScopes' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].getProjectCertificationScopes
END
GO

CREATE PROCEDURE getProjectCertificationScopes

AS
BEGIN

SELECT PIS.STANDARD_NAME, PCS.SCOPE_NAME ,PCS.ID AS PROJECT_SCOPE_ID, PCS.ISO_STANDARD_ID
FROM PROJECT_CERTIFICATION_SCOPE PCS INNER JOIN PROJECT_ISO_STANDARD PIS ON PCS.ISO_STANDARD_ID = PIS.ID
WHERE PCS.ISACTIVE=1 AND PIS.ISACTIVE=1
ORDER BY PCS.SCOPE_NAME, PIS.STANDARD_NAME

END
GO
