IF EXISTS
(
    SELECT 1
    FROM sys.procedures
    WHERE name = 'reports_getCRISPScores'
          AND TYPE = 'P'
)
BEGIN
    DROP PROCEDURE [dbo].reports_getCRISPScores
END
GO

CREATE PROCEDURE [dbo].[reports_getCRISPScores]
@STARTDATE DATETIME,
@ENDDATE DATETIME
AS
BEGIN
SET @STARTDATE = CONVERT(DATETIME, CONVERT(varchar(11),@STARTDATE, 111 ) + ' 00:00:00', 111)
SET @ENDDATE = CONVERT(DATETIME, CONVERT(varchar(11),@ENDDATE, 111 ) + ' 23:59:59', 111)
SELECT (SELECT TOP 1 INFO.FRST_NM  from EMP_INFO INFO
WHERE  EMP_ID =  p.PROJ_DM_EMP_ID ) CSM,
C.CUST_NM [CUSTOMER NAME], c.cust_id, PO.TITLE AS [PORTFOLIO NAME],PROJ_NM [PROJECT NAME], FORMAT(PUBLISH_DATE, 'dd-MMM-yyy', 'EN-us') [PUBLISHED DATE],
CSP.STATUS,
(SELECT TOP 1 SCORE C FROM [CRISP_SCORES_CATEGORY] WHERE CRISP_SCORES_PROJECT_ID = CSP.ID AND CATEGORY_ID = 1)  C,
(SELECT TOP 1 SCORE C FROM [CRISP_SCORES_CATEGORY] WHERE CRISP_SCORES_PROJECT_ID = CSP.ID AND CATEGORY_ID = 2)  R,
(SELECT TOP 1 SCORE C FROM [CRISP_SCORES_CATEGORY] WHERE CRISP_SCORES_PROJECT_ID = CSP.ID AND CATEGORY_ID = 3)  I,
(SELECT TOP 1 SCORE C FROM [CRISP_SCORES_CATEGORY] WHERE CRISP_SCORES_PROJECT_ID = CSP.ID AND CATEGORY_ID = 4)  S,
(SELECT TOP 1 SCORE C FROM [CRISP_SCORES_CATEGORY] WHERE CRISP_SCORES_PROJECT_ID = CSP.ID AND CATEGORY_ID = 5)  P,
SCORE TOTAL,
CSP.COMMENTS [QA NEED FOCUS],
CSP.HR_NEED_FOCUS_COMMENTS [HR NEED FOCUS] ,
(select frst_nm from emp_info e where e.emp_id = p.quality_spoc) [QUALITY SPOC]
--,P.PROJ_ID [PROJECT ID]
FROM [CRISP_SCORES_PROJECT] CSP
INNER JOIN PROJECT P ON P.PROJ_ID = CSP.PROJECT_ID
INNER JOIN CUSTOMER C ON C.CUST_ID = P.CUST_ID
LEFT JOIN PORTFOLIO_PROJECT PP ON PP.PROJ_ID = CSP.PROJECT_ID  AND PP.ISACTIVE=1
LEFT JOIN PORTFOLIO PO ON PO.ID = pp.PORTFOLIO_ID AND PO.ISACTIVE=1
WHERE  c.cust_id != '202100062' and  PUBLISH_DATE >= @STARTDATE AND PUBLISH_DATE <= @ENDDATE ORDER BY 1,2,PUBLISH_DATE
--STATUS = 'PUBLISHED' AND
END