USE BAS
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='reports_ListofAssessmentChecklist' AND TYPE='P')
BEGIN
 DROP PROCEDURE [dbo].reports_ListofAssessmentChecklist
END
GO

CREATE PROCEDURE dbo.reports_ListofAssessmentChecklist                            

@checklist int
as

begin
select PS.TITLE as SERVICE_TOWER,PA.TITLE as PROCESS_AREA,P.TITLE as PROCESS,PQ.TITLE as QUESTION_NAME,
AW.WEIGHTAGE_TITLE as WEIGHTAGE,AW.WEIGHTAGE_SCORE,GP.SHORT_DESC as CATEGORY from  
CSP..PM_CHECKLIST_QUESTIONS PQ left join CSP..AUDIT_CHECKLIST_WEIGHTAGE AW on PQ.WEIGHTAGE_ID=AW.WEIGHTAGE_ID 
inner join CSP..GLOBAL_PERSPECTIVE GP on GP.ID=PQ.GLOBAL_PERSPECTIVE_ID
inner join CSP..PM_CHECKLIST PM on PM.ID=PQ.CHECKLIST_ID
inner join CSP..PM_PROCESS_QUESTIONS_MAPPING PQM on PQM.question_id=PQ.ID and PQM.checklist_id=PQ.CHECKLIST_ID
inner join CSP..PROCESS_SERVICE_AREA_NEW PS on PS.ID=PQM.SERVICE_AREA_ID
inner join CSP..PROCESS_AREA PA on PA.ID = PQM.PROCESS_AREA_ID
inner join CSP..PROCESS P on P.ID = PQM.process_id

where PQ.ISACTIVE=1 and PM.ISACTIVE=1 and PQM.isactive=1 and PM.ID=@checklist order by SERVICE_TOWER,PROCESS_AREA,PROCESS
end
GO
