-- Insert-or-update of a project's AI Adoption Metrics panel, keyed on PROJECT_ID
-- (replaces the Firestore "query then addDoc/updateDoc" upsert pattern with a real
-- unique-index-backed MERGE-style upsert).
IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='usp_AIMI_UpsertProjectInfo' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[usp_AIMI_UpsertProjectInfo]
END
GO

CREATE PROCEDURE [dbo].[usp_AIMI_UpsertProjectInfo]
    @ID INT = NULL OUTPUT,
    @PROJECT_ID VARCHAR(20),
    @PEOPLE_USING_AI INT = NULL,
    @IS_PROJECT_NA BIT = 0,
    @NA_COMMENTS NVARCHAR(MAX) = NULL,
    @LICENSE_COUNT INT = NULL,
    @LICENSE_PROVIDER VARCHAR(50) = NULL,
    @RUNOPS_AUTO_RESOLVED VARCHAR(100) = NULL,
    @RUNOPS_MTTR_REDUCTION VARCHAR(100) = NULL,
    @RUNOPS_AI_AGENTS VARCHAR(100) = NULL,
    @RUNOPS_AUTOMATED_WORKFLOWS VARCHAR(100) = NULL,
    @RUNOPS_MTTD VARCHAR(100) = NULL,
    @RUNOPS_MTTR VARCHAR(100) = NULL,
    @ENGINEER_AI_AGENTS VARCHAR(100) = NULL,
    @ENGINEER_DELIVERY_CYCLE_TIME VARCHAR(100) = NULL,
    @ENGINEER_CONTRACT_TEST_CASE_PASS_RATE VARCHAR(100) = NULL,
    @ENGINEER_PERFORMANCE_DEFECTS_PRE_RELEASE VARCHAR(100) = NULL,
    @COMMON_ADOPTION_WORKFORCE_CERTIFICATION VARCHAR(100) = NULL,
    @COMMON_ADOPTION_EFFORTS_SAVED VARCHAR(100) = NULL,
    @COMMON_DEPLOYMENT_ENGINEER VARCHAR(100) = NULL,
    @PRESENTATION_DONE BIT = 0,
    @PROJECT_FY VARCHAR(10) = NULL,
    @ACCEPTED_SCORE DECIMAL(4,2) = NULL,
    @SCORE_REVIEWED BIT = 0,
    @ACCEPTED_SCORE_COMMENT NVARCHAR(MAX) = NULL,
    @EMP_ID VARCHAR(10)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT @ID = ID FROM AIMI_PROJECT_INFO WHERE PROJECT_ID = @PROJECT_ID AND ISACTIVE = 1;

    IF @ID IS NULL
    BEGIN
        INSERT INTO AIMI_PROJECT_INFO
            (PROJECT_ID, PEOPLE_USING_AI, IS_PROJECT_NA, NA_COMMENTS, LICENSE_COUNT, LICENSE_PROVIDER,
             RUNOPS_AUTO_RESOLVED, RUNOPS_MTTR_REDUCTION, RUNOPS_AI_AGENTS, RUNOPS_AUTOMATED_WORKFLOWS,
             RUNOPS_MTTD, RUNOPS_MTTR,
             ENGINEER_AI_AGENTS, ENGINEER_DELIVERY_CYCLE_TIME, ENGINEER_CONTRACT_TEST_CASE_PASS_RATE,
             ENGINEER_PERFORMANCE_DEFECTS_PRE_RELEASE,
             COMMON_ADOPTION_WORKFORCE_CERTIFICATION, COMMON_ADOPTION_EFFORTS_SAVED, COMMON_DEPLOYMENT_ENGINEER,
             PRESENTATION_DONE, PROJECT_FY, ACCEPTED_SCORE, SCORE_REVIEWED, ACCEPTED_SCORE_COMMENT,
             CREATED_BY, CREATED_DATE, UPDATED_BY, UPDATED_DATE, ISACTIVE)
        VALUES
            (@PROJECT_ID, @PEOPLE_USING_AI, @IS_PROJECT_NA, @NA_COMMENTS, @LICENSE_COUNT, @LICENSE_PROVIDER,
             @RUNOPS_AUTO_RESOLVED, @RUNOPS_MTTR_REDUCTION, @RUNOPS_AI_AGENTS, @RUNOPS_AUTOMATED_WORKFLOWS,
             @RUNOPS_MTTD, @RUNOPS_MTTR,
             @ENGINEER_AI_AGENTS, @ENGINEER_DELIVERY_CYCLE_TIME, @ENGINEER_CONTRACT_TEST_CASE_PASS_RATE,
             @ENGINEER_PERFORMANCE_DEFECTS_PRE_RELEASE,
             @COMMON_ADOPTION_WORKFORCE_CERTIFICATION, @COMMON_ADOPTION_EFFORTS_SAVED, @COMMON_DEPLOYMENT_ENGINEER,
             @PRESENTATION_DONE, @PROJECT_FY, @ACCEPTED_SCORE, @SCORE_REVIEWED, @ACCEPTED_SCORE_COMMENT,
             @EMP_ID, GETDATE(), @EMP_ID, GETDATE(), 1);

        SET @ID = SCOPE_IDENTITY();
    END
    ELSE
    BEGIN
        UPDATE AIMI_PROJECT_INFO
           SET PEOPLE_USING_AI = @PEOPLE_USING_AI,
               IS_PROJECT_NA = @IS_PROJECT_NA,
               NA_COMMENTS = @NA_COMMENTS,
               LICENSE_COUNT = @LICENSE_COUNT,
               LICENSE_PROVIDER = @LICENSE_PROVIDER,
               RUNOPS_AUTO_RESOLVED = @RUNOPS_AUTO_RESOLVED,
               RUNOPS_MTTR_REDUCTION = @RUNOPS_MTTR_REDUCTION,
               RUNOPS_AI_AGENTS = @RUNOPS_AI_AGENTS,
               RUNOPS_AUTOMATED_WORKFLOWS = @RUNOPS_AUTOMATED_WORKFLOWS,
               RUNOPS_MTTD = @RUNOPS_MTTD,
               RUNOPS_MTTR = @RUNOPS_MTTR,
               ENGINEER_AI_AGENTS = @ENGINEER_AI_AGENTS,
               ENGINEER_DELIVERY_CYCLE_TIME = @ENGINEER_DELIVERY_CYCLE_TIME,
               ENGINEER_CONTRACT_TEST_CASE_PASS_RATE = @ENGINEER_CONTRACT_TEST_CASE_PASS_RATE,
               ENGINEER_PERFORMANCE_DEFECTS_PRE_RELEASE = @ENGINEER_PERFORMANCE_DEFECTS_PRE_RELEASE,
               COMMON_ADOPTION_WORKFORCE_CERTIFICATION = @COMMON_ADOPTION_WORKFORCE_CERTIFICATION,
               COMMON_ADOPTION_EFFORTS_SAVED = @COMMON_ADOPTION_EFFORTS_SAVED,
               COMMON_DEPLOYMENT_ENGINEER = @COMMON_DEPLOYMENT_ENGINEER,
               PRESENTATION_DONE = @PRESENTATION_DONE,
               PROJECT_FY = @PROJECT_FY,
               ACCEPTED_SCORE = @ACCEPTED_SCORE,
               SCORE_REVIEWED = @SCORE_REVIEWED,
               ACCEPTED_SCORE_COMMENT = @ACCEPTED_SCORE_COMMENT,
               UPDATED_BY = @EMP_ID,
               UPDATED_DATE = GETDATE()
         WHERE ID = @ID;
    END
END
GO
