IF EXISTS (SELECT 1 FROM CSS_QUESTION_MASTER WHERE QUESTION like '%GAVS%')
BEGIN
    UPDATE CSS_QUESTION_MASTER set QUESTION = REPLACE(question,'GS Lab | GAVS','Neurealm (Formerly GS Lab | GAVS)') from CSS_QUESTION_MASTER 
where QUESTION like '%GAVS%'
END

IF EXISTS (SELECT 1 FROM CONTACTS where CONTACT_TYPE ='GAVS')
BEGIN
UPDATE CONTACTS SET CONTACT_TYPE = 'Neurealm' where CONTACT_TYPE ='GAVS'
END
