/** Neurealm-relevant external signals generated by the configured AI insights service (JSON). */
export type NeurealmNewsImpact = 'High' | 'Medium' | 'Low';

export interface NeurealmNewsItem {
  headline: string;
  /** Short summary of the development (2–4 sentences). */
  summary: string;
  neurealmImpact: NeurealmNewsImpact;
  /** How this could affect Neurealm specifically (AI services, healthcare IT, silicon, US–India delivery, ERM). */
  whyItMatters: string;
  /** Concrete steps leadership or account teams should consider. */
  actionItems: string[];
  /** e.g. "Regulatory", "Silicon", "GenAI" */
  tags: string[];
  /** Source links returned by the AI insights service, when available. */
  sources?: NeurealmNewsSource[];
}

export interface NeurealmNewsBundle {
  briefingTitle: string;
  /** One line on what time horizon or sources the model used. */
  contextNote: string;
  items: NeurealmNewsItem[];
  /** Honest limitation text (model knowledge / not live web unless tools enabled). */
  disclaimer: string;
  /** Search queries or grounding notes generated while preparing the briefing. */
  searchQueries?: string[];
}

export interface NeurealmNewsSource {
  title: string;
  uri: string;
}
