
IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getAllMappedProcessByServiceArea' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[getAllMappedProcessByServiceArea]
END
GO

CREATE procedure getAllMappedProcessByServiceArea  

@serviceAreaId int=0  

as  
begin  

SELECT DISTINCT
    SA.ID AS SERVICE_AREA_ID,
    SA.TITLE AS SERVICE_AREA_NAME,
    PA.TITLE AS PROCESS_AREA,
    PA.ID AS PROCESS_AREA_ID,
    P.ID AS PROCESS_ID,
    P.TITLE AS PROCESS_TITLE,
    P.DESCRIPTION AS PROCESS_DESCRIPTION,
    STRING_AGG(PMR.ID, ',') AS REFERENCE_COLUMN  
FROM
    PROCESS P
INNER JOIN
    PROCESS_SERVICE_AREA_MAPPING MP  ON P.ID = MP.PROCESS_ID
INNER JOIN
    PROCESS_SERVICE_AREA_NEW SA ON MP.SERVICE_AREA_ID = SA.ID
INNER JOIN
    PROCESS_AREA PA ON P.PROCESS_AREA_ID = PA.ID
LEFT JOIN
    PROCESS_AREA_MODEL_REFERENCE PAR ON PAR.PROCESS_ID = P.ID
LEFT JOIN
    PROCESS_MODEL_REFERENCE PMR ON PMR.ID = PAR.PROCESS_MODEL_REFERENCE_ID
WHERE
    MP.ISACTIVE = 1 AND SA.ISACTIVE = 1 AND PA.ISACTIVE = 1 AND PA.SHOW_IN_MASTER = 1 AND P.ISACTIVE=1
	AND (PMR.ISACTIVE = 1 OR PMR.ID IS NULL) AND (PAR.ISACTIVE = 1 OR PAR.ID IS NULL)
    AND P.SHOW_IN_MASTER = 1 AND (ISNULL(@SERVICEAREAID, 0) = 0 OR (@SERVICEAREAID = SA.ID))
GROUP BY
	SA.ID,SA.TITLE,PA.TITLE,PA.ID,P.ID,P.TITLE,P.DESCRIPTION
ORDER BY
    SA.TITLE,PA.TITLE,P.TITLE

END
GO
