
IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getAllRiskFromRepository' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[getAllRiskFromRepository]
END
GO

CREATE PROCEDURE getAllRiskFromRepository

@customerId varchar(50),
@projectId varchar(50)

as
begin

SELECT ST.TITLE as SERVICE_TOWER_TITLE,RR.RISK_DESCRIPTION as DESCRIPTION,RR.RISK_IMPACT as IMPACT,RR.LIKELIHOOD as PROBABILITY_SCALE,
RR.CONSEQUENCES as IMPACT_SCALE,RR.RISK_TREATMENT_STRATEGY,RR.ID as RISK_REPOSITORY_ID,ST.ID as SERVICE_TOWER_ID
from RISK_REPOSITORY RR inner join RISK_REPOSITORY2SERVICE_TOWER RRS on RRS.RISK_REPOSITORY_ID = RR.ID
inner join PROCESS_SERVICE_AREA_PROJECT_MAPPING PSM on PSM.SERVICE_AREA_ID = RRS.SERVICE_TOWER_ID
inner join PROCESS_SERVICE_AREA_NEW ST on ST.ID = RRS.SERVICE_TOWER_ID

where PSM.CUST_ID = @customerId and PSM.PROJ_ID = @projectId and
ST.ISACTIVE=1 and RRS.ISACTIVE=1 and RR.ISACTIVE=1 and PSM.ISACTIVE=1
order by SERVICE_TOWER_TITLE, DESCRIPTION

end
GO
