IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getAllMasterKPIs' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[getAllMasterKPIs]
END
GO

CREATE Procedure getAllMasterKPIs  
  
AS  
  
BEGIN                        
                
select KT.ID as KPI_MASTER_ID,KT.ID as KPI_TARGET_MASTER_ID, K.MODE_ID,PSA.SERVICE_AREA_TYPE as SERVICE_AREA,   
K.KPI_NAME, KT.EXPECTED_SERVICE_LEVEL,KT.MINIMUM_SERVICE_LEVEL,K.SLA_TARGET_UNIT_OF_MEASUREMENT,                      
K.FREQUENCY,KT.SPECIFICATION_LIMIT AS SPECIFICATION_LIMIT,  
SLT.SERVICE_LEVEL,SLA.SLA_CATEGORY, KB.BASE_MEASURE_ID, RM.REFERENCE,  
KM.PRODUCT_SERVICE_LEVEL_METRICS_ID, K.GLOBAL_KPI_CATEGORY_ID , KT.START_DATE,KT.END_DATE                 
from   
KPI_MASTER K                        
inner join KPI_TARGET_MASTER KT on K.ID = KT.KPI_MASTER_ID    
inner join KPI_MASTER2PRODUCT_SERVICE_LEVEL_METRICS KM on KM.KPI_MASTER_ID = K.ID   
inner join KPI_MASTER2BASE_MEASURE_CONFIG KB on KB.KPI_MASTER_ID = K.ID   
inner join PRODUCT_SERVICE_LEVEL_METRICS PSL on PSL.ID = KM.PRODUCT_SERVICE_LEVEL_METRICS_ID        
inner join PRODUCTS_SERVICE_AREA PSA on PSL.SERVICE_AREA_TYPE_ID = PSA.ID                         
inner join PRODUCTS_SERVICE_LEVEL_TYPE SLT on PSL.SERVICE_LEVEL_TYPE_ID = SLT.ID                        
inner join PRODUCTS_SLA_CATEGORY SLA on PSL.SLA_CATEGORY_ID = SLA.ID                        
inner join REFERENCE_MASTER RM on PSL.REFERENCE_ID = RM.ID                  
  
where K.ISACTIVE=1 and KM.ISACTIVE=1 and KT.ISACTIVE = 1 and RM.ISACTIVE = 1     
                        
END       
GO

