IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getOverallKPIList' AND TYPE='P')
BEGIN
       DROP PROCEDURE getOverallKPIList
END
GO

CREATE PROCEDURE getOverallKPIList              

AS
BEGIN                    

Select KM.ID as KPI_ID, KM.KPI_NAME, KM.FREQUENCY, KM.SLA_TARGET_UNIT_OF_MEASUREMENT, KM.SERVICE_AREA, BM.ID as BASE_MEASURE_ID,
BM.NUMERATORDESCRIPTION, BM.DENOMINATORDESCRIPTION, BM.BASE_MEASURE_FORMULA_TYPE_ID, BMF.FORMULA_DESCRIPTION, BMF.FORMULA, BMF.SLA_FORMULA

from KPI_MASTER KM 
inner join KPI_MASTER2BASE_MEASURE_CONFIG KMB on KMB.KPI_MASTER_ID = KM.ID
inner join BASE_MEASURE BM on BM.ID = KMB.BASE_MEASURE_ID
inner join BASE_MEASURE_FORMULA_TYPE BMF on BMF.ID = BM.BASE_MEASURE_FORMULA_TYPE_ID
where KM.ISACTIVE=1 and KMB.ISACTIVE=1 and BM.ISACTIVE=1 and BMF.ISACTIVE=1
order by KM.KPI_NAME

END
GO
