IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getProcessModelReferences' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[getProcessModelReferences]
END
GO

CREATE Procedure getProcessModelReferences

as
Begin

select PM.TITLE as PROCESS_MODEL_NAME,
CONCAT_WS(' - ', PR.SECTION_REFERENCE, PR.CONTROL_REFERENCE) AS SECTION_REFERENCE,
PR.PROCESS_MODEL_ID,PR.ID as PROCESS_MODEL_REFERENCE_LIST
from PROCESS_MODEL_REFERENCE PR inner join PROCESS_MODEL PM on PM.ID = PR.PROCESS_MODEL_ID
where PR.ISACTIVE=1 and PM.ISACTIVE=1

End
Go
