
IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getProductMappedCSATProjects' AND TYPE='P')
BEGIN
       DROP PROCEDURE getProductMappedCSATProjects
END
GO

CREATE PROCEDURE getProductMappedCSATProjects

AS  
BEGIN  

SELECT DISTINCT CU.ID AS CUSTOMER_USER_ID, C.CUST_ID, C.CUST_NM, PR2.PROJECT_ID AS PROJ_ID, P.PROJ_NM,
PR1.CREATED_BY, PR1.CREATED_DATE,PR1.UPDATED_BY, PR1.UPDATED_DATE, PR1.ISACTIVE

FROM PRODUCT_RESPONSIBLE PR1
INNER JOIN PORTFOLIO_PRODUCTS PP ON PP.ID = PR1.PRODUCT_ID
INNER JOIN (SELECT PRODUCT_ID, PROJECT_ID FROM PRODUCT_RESPONSIBLE WHERE MANAGEMENT_TYPE = 7 AND ISACTIVE = 1) PR2
ON PR1.PRODUCT_ID = PR2.PRODUCT_ID
INNER JOIN CUSTOMER_USERS CU ON CU.EMAILID = PR1.EMP_ID
INNER JOIN PROJECT P ON P.PROJ_ID = PR2.PROJECT_ID 
INNER JOIN CUSTOMER C ON C.CUST_ID = PP.CUST_ID
LEFT JOIN CUSTOMER_PROJECTS CP ON CP.PROJ_ID = PR2.PROJECT_ID AND CP.CUST_ID = PP.CUST_ID AND CP.CUSTOMER_USER_ID = CU.ID
WHERE PR1.ISACTIVE = 1 AND PR1.MANAGEMENT_TYPE = 6 AND PR2.PROJECT_ID IS NOT NULL 

END
GO
