IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='reports_getServiceTowersMappedForProjects' AND TYPE='P')
BEGIN
 DROP PROCEDURE [dbo].reports_getServiceTowersMappedForProjects
END
GO

CREATE PROCEDURE dbo.reports_getServiceTowersMappedForProjects    
AS     
BEGIN     
SELECT  
 t.CUST_NM AS CUSTOMER,t.PROJ_ID AS PROJECT_ID,t.PROJ_NM AS PROJECT,ACCOUNT_OWNER,t.MANAGER,t.CSM,QA_SPOC, CASE WHEN t.CSV IS NULL THEN 'NO' ELSE 'YES' END SERVICE_TOWER_MAPPED,    
t.CSV AS SERVICE_TOWERS , t.CSM_MAIL_ID ,t.MANAGER_MAIL_ID ,t.QUALITY_PARTNER_MAIL_ID, case when QADOR is null then 'YES' else 'NO' end IS_QA_ACTIVE FROM(    
select C.CUST_NM, P.PROJ_ID,    
PROJ_NM  ,ACCOUNT_OWNER = case when proj_id like 'proj%'  then 'GSLab' else 'GAVS' end,     PM.FRST_NM +' '+ISNULL(PM.LAST_NM,'') AS MANAGER,   DM.FRST_NM +' '+ISNULL(DM.LAST_NM,'') AS CSM,PM.EMAIL_ID as MANAGER_MAIL_ID , DM.EMAIL_ID as CSM_MAIL_ID, qa.EMAIL_ID as QUALITY_PARTNER_MAIL_ID,  
QA.FRST_NM +' '+ISNULL(QA.LAST_NM,'') AS QA_SPOC,CSV= STUFF (( SELECT   ', ' +  TITLE  FROM    
 PROCESS_SERVICE_AREA_PROJECT_MAPPING PSMAP (NOLOCK)    
 INNER JOIN PROCESS_SERVICE_AREA_NEW S (NOLOCK)    
 ON PSMAP.SERVICE_AREA_ID =S.ID    
 WHERE p.PROJ_ID= PSMAP.PROJ_ID AND PSMAP.ISACTIVE=1 order by title    
  FOR XML PATH('')), 1, 2, ''), QA.DOR QADOR  
from PROJECT P (NOLOCK)      
INNER JOIN CUSTOMER C (NOLOCK) ON    
P.CUST_ID=C.CUST_ID    
INNER JOIN EMP_INFO PM (NOLOCK) ON    
P.PROJ_PM_EMP_ID =PM.EMP_ID    
INNER JOIN EMP_INFO DM (NOLOCK) ON    
P.PROJ_DM_EMP_ID =DM.EMP_ID    
INNER JOIN EMP_INFO QA (NOLOCK) ON    
P.QUALITY_SPOC =QA.EMP_ID   
WHERE ISNULL(P.PROJ_STATUS ,'') != 'Close'   
) as t    
ORDER BY CUST_NM,PROJ_NM    
    
 END  