//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITY_LOGS
    {
        public int ID { get; set; }
        public string EMAIL_ID { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string REQUEST_URL { get; set; }
        public string METHOD { get; set; }
        public string EXCEPTION { get; set; }
        public string INNER_EXCEPTION { get; set; }
        public string STACK_TRACE { get; set; }
    }
}
