//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNTRY_HOLIDAY
    {
        public int CNTRY_HOLIDAY_ID { get; set; }
        public short CNTRY_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual CNTRY_INFO CNTRY_INFO { get; set; }
    }
}
