//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURATION_EXT
    {
        public int ID { get; set; }
        public string KEY { get; set; }
        public string VALUE { get; set; }
        public string CUST_ID { get; set; }
        public string PROJ_ID { get; set; }
        public string COMMENTS { get; set; }
        public bool ISENCRYPT { get; set; }
        public bool ISACTIVE { get; set; }
    }
}
