//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATE_DIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATE_DIM()
        {
            this.PROJ_RESRC_TIME_ENTRY = new HashSet<PROJ_RESRC_TIME_ENTRY>();
            this.PROJ_REV = new HashSet<PROJ_REV>();
            this.PROJ_TIMESHEET = new HashSet<PROJ_TIMESHEET>();
            this.RESRC_REV = new HashSet<RESRC_REV>();
            this.RESRC_RIMBS = new HashSet<RESRC_RIMBS>();
            this.RESRC_RIMBS_OTHERS = new HashSet<RESRC_RIMBS_OTHERS>();
            this.RIMBS_FILES = new HashSet<RIMBS_FILES>();
        }
    
        public int DATE_ID { get; set; }
        public System.DateTime CLNDR_DATE { get; set; }
        public string CLNDR_DAY_NAME { get; set; }
        public short CLNDR_WK_NRB_IN_MTH { get; set; }
        public short CLNDR_WK_NBR_IN_YEAR { get; set; }
        public short CLNDR_MTH_NBR { get; set; }
        public System.DateTime CLNDR_MTH_START_DATE { get; set; }
        public System.DateTime CLDNR_MTH_END_DATE { get; set; }
        public string CLNDR_MTH_SHRT_DESC { get; set; }
        public string CLNDR_MTH_LONG_DESC { get; set; }
        public short CLNDR_QTR_NBR { get; set; }
        public System.DateTime CLNDR_QTR_START_DATE { get; set; }
        public System.DateTime CLDNR_QTR_END_DATE { get; set; }
        public string CLDNR_QTR_SHRT_DESC { get; set; }
        public string CLNDR_QTR_LONG_DESC { get; set; }
        public short CLNDR_YEAR { get; set; }
        public Nullable<short> FISCAL_MTH_NBR { get; set; }
        public Nullable<System.DateTime> FISCAL_MTH_START_DATE { get; set; }
        public Nullable<System.DateTime> FISCAL_MTH_END_DATE { get; set; }
        public string FISCAL_MTH_SHRT_DESC { get; set; }
        public string FISCAL_MTH_LONG_DESC { get; set; }
        public Nullable<short> FISCAL_QTR_NBR { get; set; }
        public Nullable<System.DateTime> FISCAL_QTR_START_DATE { get; set; }
        public Nullable<System.DateTime> FISCAL_QTR_END_DATE { get; set; }
        public string FISCAL_QTR_SHRT_DESC { get; set; }
        public string FISCAL_QTR_LONG_DESC { get; set; }
        public Nullable<short> FISCAL_YEAR { get; set; }
        public Nullable<System.DateTime> FISCAL_YEAR_START_DATE { get; set; }
        public Nullable<System.DateTime> FISCAL_YEAR_END_DATE { get; set; }
        public string WORK_DAY_FLAG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_RESRC_TIME_ENTRY> PROJ_RESRC_TIME_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_REV> PROJ_REV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_TIMESHEET> PROJ_TIMESHEET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_REV> RESRC_REV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_RIMBS> RESRC_RIMBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_RIMBS_OTHERS> RESRC_RIMBS_OTHERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIMBS_FILES> RIMBS_FILES { get; set; }
    }
}
