//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_SKILLSET_MATRIX
    {
        public int EMP_SS_MATRIX_ID { get; set; }
        public string EMP_ID { get; set; }
        public short SKILLSET_ID { get; set; }
        public string SKILL_CATEGORY { get; set; }
        public short EMP_SELF_RATING { get; set; }
        public Nullable<short> MANAGER_RATING { get; set; }
        public Nullable<short> EXP_MONTH { get; set; }
        public string LAST_USED_MONTH { get; set; }
        public string LAST_USED_YEAR { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
        public string SKILLSET_STATUS { get; set; }
    
        public virtual EMP_INFO EMP_INFO { get; set; }
        public virtual SKILLSET_INFO SKILLSET_INFO { get; set; }
    }
}
