//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJ_REV_APPRL_WF
    {
        public int PROJ_REV_APPRL_WF_ID { get; set; }
        public int PROJ_REV_ID { get; set; }
        public string APPR_EMP_ID { get; set; }
        public System.DateTime APPRL_DATE { get; set; }
        public string APPR_REMARK { get; set; }
        public string APPRL_STS { get; set; }
        public short APPRL_WF_LEVEL { get; set; }
        public string CURR_INDC { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
        public Nullable<bool> IS_FORECAST { get; set; }
    
        public virtual PROJ_REV PROJ_REV { get; set; }
    }
}
