//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJ_RESOURCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJ_RESOURCE()
        {
            this.PROJ_RESOURCE_ROLE_MAP_BILLING = new HashSet<PROJ_RESOURCE_ROLE_MAP_BILLING>();
            this.RESRC_REV = new HashSet<RESRC_REV>();
            this.PROJ_REV = new HashSet<PROJ_REV>();
            this.RESRC_RIMBS = new HashSet<RESRC_RIMBS>();
            this.RIMBS_FILES = new HashSet<RIMBS_FILES>();
        }
    
        public int PROJ_RESRC_ID { get; set; }
        public string PROJ_ID { get; set; }
        public string EMP_ID { get; set; }
        public Nullable<int> EMP_PROJ_ROLE_MAP_ID { get; set; }
        public string PROJ_RM_EMP_ID { get; set; }
        public string PROJ_REVIEWER_EMP_ID { get; set; }
        public System.DateTime START_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public bool BILL_FLG { get; set; }
        public decimal ALLCT_PCT { get; set; }
        public string RELEASE_REMARK { get; set; }
        public string PERF_REMARK { get; set; }
        public Nullable<short> PERF_RATING { get; set; }
        public string CURR_INDC { get; set; }
        public string COMMENTS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
        public string ROLE_MAPPED_STATUS { get; set; }
        public string ID { get; set; }
    
        public virtual EMP_INFO EMP_INFO { get; set; }
        public virtual EMP_INFO EMP_INFO1 { get; set; }
        public virtual EMP_INFO EMP_INFO2 { get; set; }
        public virtual EMP_INFO EMP_INFO3 { get; set; }
        public virtual EMP_INFO EMP_INFO4 { get; set; }
        public virtual EMP_INFO EMP_INFO5 { get; set; }
        public virtual EMP_PROJ_ROLE_MAP EMP_PROJ_ROLE_MAP { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_RESOURCE_ROLE_MAP_BILLING> PROJ_RESOURCE_ROLE_MAP_BILLING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_REV> RESRC_REV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_REV> PROJ_REV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_RIMBS> RESRC_RIMBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIMBS_FILES> RIMBS_FILES { get; set; }
    }
}
