//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJMGT_TEAM
    {
        public int ID { get; set; }
        public string CUST_ID { get; set; }
        public string PROJ_ID { get; set; }
        public Nullable<int> SUB_PROJ_ID { get; set; }
        public string EMP_ID { get; set; }
        public bool OWNER { get; set; }
        public bool ADMIN { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
        public bool ISACTIVE { get; set; }
    }
}
