//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJ_REV
    {
        public int PROJ_REV_ID { get; set; }
        public string PROJ_ID { get; set; }
        public int DATE_ID { get; set; }
        public decimal FRCT_REV_AMT { get; set; }
        public decimal FRCT_RIMBS_AMT { get; set; }
        public string FRCT_REMARK { get; set; }
        public decimal ACTL_REV_AMT { get; set; }
        public decimal ACTL_RIMBS_AMT { get; set; }
        public string ACTL_REMARK { get; set; }
        public string FRCT_UPDATED_BY { get; set; }
        public System.DateTime FRCT_UPDATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
        public Nullable<int> PROJ_RESRC_ID { get; set; }
    
        public virtual DATE_DIM DATE_DIM { get; set; }
        public virtual PROJ_RESOURCE PROJ_RESOURCE { get; set; }
        public virtual PROJ_REV_APPRL_WF PROJ_REV_APPRL_WF { get; set; }
        public virtual PROJECT PROJECT { get; set; }
    }
}
