//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESRC_RIMBS_OTHERS
    {
        public int OTH_RIMBS_ID { get; set; }
        public string PROJ_ID { get; set; }
        public Nullable<int> DATE_ID { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string REMARKS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual DATE_DIM DATE_DIM { get; set; }
        public virtual PROJECT PROJECT { get; set; }
    }
}
