//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESRC_RIMBS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESRC_RIMBS()
        {
            this.RIMBS_FILES = new HashSet<RIMBS_FILES>();
        }
    
        public int RESRC_RIMBS_ID { get; set; }
        public int PROJ_RESRC_ID { get; set; }
        public int DATE_ID { get; set; }
        public short RIMBS_TYPE_ID { get; set; }
        public decimal FRCT_AMT { get; set; }
        public string FRCT_REMARK { get; set; }
        public decimal ACTL_AMT { get; set; }
        public string ACTL_REMARK { get; set; }
        public Nullable<short> NBR_OF_DAYS { get; set; }
        public string FRCT_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> FRCT_UPDATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
        public Nullable<short> ACTL_NBR_OF_DAYS { get; set; }
        public Nullable<short> CNTRY_ID { get; set; }
    
        public virtual CNTRY_INFO CNTRY_INFO { get; set; }
        public virtual DATE_DIM DATE_DIM { get; set; }
        public virtual PROJ_RESOURCE PROJ_RESOURCE { get; set; }
        public virtual RIMBS_TYPE RIMBS_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIMBS_FILES> RIMBS_FILES { get; set; }
    }
}
