//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESRC_RQST_WF
    {
        public int RR_WF_ID { get; set; }
        public Nullable<short> RESRC_RQST_ID { get; set; }
        public Nullable<short> RR_WF_STAGE_ID { get; set; }
        public string STAGE_OWNER_EMP_ID { get; set; }
        public string TAG_EMP_ID { get; set; }
        public System.DateTime STAGE_START_DATE { get; set; }
        public Nullable<System.DateTime> STAGE_END_DATE { get; set; }
        public string STAGE_CURR_INDC { get; set; }
        public string STAGE_REMARK { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
    
        public virtual EMP_INFO EMP_INFO { get; set; }
        public virtual EMP_INFO EMP_INFO1 { get; set; }
        public virtual RESRC_RQST RESRC_RQST { get; set; }
        public virtual RR_WF_STAGE_INFO RR_WF_STAGE_INFO { get; set; }
    }
}
