//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISA_DETAILS
    {
        public int VISA_ID { get; set; }
        public int PASSPORT_ID { get; set; }
        public Nullable<short> CNTRY_ID { get; set; }
        public string CATEGORY { get; set; }
        public string VISA_TYPE { get; set; }
        public Nullable<System.DateTime> VALID_FROM { get; set; }
        public Nullable<System.DateTime> VALID_TO { get; set; }
        public string REMARKS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual CNTRY_INFO CNTRY_INFO { get; set; }
        public virtual EMP_PASSPORT EMP_PASSPORT { get; set; }
    }
}
