-- Cust_ID _BAS
USE CSP

-- ALTER Scripts for drop constraints
--NO

-- ALTER Scripts for drop Index
IF EXISTS(SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[dbo].[DASHBOARD_DETAILS]') AND name='IX_dashboard_details_CUST_ID')       BEGIN  DROP INDEX [dbo].[DASHBOARD_DETAILS].IX_dashboard_details_CUST_ID; END
IF EXISTS(SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[dbo].[KPI_GOALS]') AND name='GOAL_IDX')       BEGIN  DROP INDEX [dbo].[KPI_GOALS].GOAL_IDX; END
IF EXISTS(SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[dbo].[PM_PROJECT_SERVICE_AREA_PROCESS_MAPPING]') AND name='IX_PM_PROJECT_SERVICE_AREA_PROCESS_MAPPING')       BEGIN  DROP INDEX [dbo].[PM_PROJECT_SERVICE_AREA_PROCESS_MAPPING].IX_PM_PROJECT_SERVICE_AREA_PROCESS_MAPPING; END


-- Alter scripts for vacrchar
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='HIGHLIGHTS' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE HIGHLIGHTS  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='SQA_CHART_FILTER' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE SQA_CHART_FILTER  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CUSTOMER_PROJECTS_copy' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CUSTOMER_PROJECTS_copy  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT_ACTIONITEM' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT_ACTIONITEM  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='KPI' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE KPI  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='KPI_BACKUP_APRIL20_2022' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE KPI_BACKUP_APRIL20_2022  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='SUBPROJECT' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE SUBPROJECT  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PORTFOLIO_PROJECT' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PORTFOLIO_PROJECT  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='AUDIT_CHECKLIST_EXECUTION_SUMMARY_2021_07_05' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE AUDIT_CHECKLIST_EXECUTION_SUMMARY_2021_07_05  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROCESS_SERVICE_AREA_PROJECT_MAPPING' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROCESS_SERVICE_AREA_PROJECT_MAPPING  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CSS_BATCH_CUSTOMERS' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CSS_BATCH_CUSTOMERS  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='SUBPROJECT_TASK' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE SUBPROJECT_TASK  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CUSTOMER_FEEDBACK' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CUSTOMER_FEEDBACK  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='DASHBOARD_DETAILS' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE DASHBOARD_DETAILS  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='AUDIT_EXECUTION' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE AUDIT_EXECUTION  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='SQA_PROJECT_REPORTS' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE SQA_PROJECT_REPORTS  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROCESS_MODEL_PROJECT_CONFIG' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROCESS_MODEL_PROJECT_CONFIG  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='SQA_REPORT_FILES' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE SQA_REPORT_FILES  ALTER COLUMN CUSTOMER_ID varchar(50);  END
--IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='TT_DASHBOARD_DETAILS_TYPE_2DBCB4E6' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE TT_DASHBOARD_DETAILS_TYPE_2DBCB4E6  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='TASK_2021_09_24' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE TASK_2021_09_24  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='Task_Backup_11_07_2021' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE Task_Backup_11_07_2021  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='SQA_DUMP_ANALYSIS' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE SQA_DUMP_ANALYSIS  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT_CONFIGURATION_DATA' AND name='Cust_Id' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT_CONFIGURATION_DATA  ALTER COLUMN Cust_Id varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='AUDIT_CHECKLIST_EXECUTION_SUMMARY_Backup_11_07_2021' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE AUDIT_CHECKLIST_EXECUTION_SUMMARY_Backup_11_07_2021  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='SQA_PROJECT_CHART_PARAMS' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE SQA_PROJECT_CHART_PARAMS  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PM_PROJECT_SERVICE_AREA_PROCESS_MAPPING' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PM_PROJECT_SERVICE_AREA_PROCESS_MAPPING  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CRISP_SCORES_PROJECT_bk19Dec2019' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CRISP_SCORES_PROJECT_bk19Dec2019  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PORTFOLIO_PRODUCTS' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PORTFOLIO_PRODUCTS  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT_CSAT_DATA' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT_CSAT_DATA  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='AUDIT_CHECKLIST_EXECUTION_SUMMARY' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE AUDIT_CHECKLIST_EXECUTION_SUMMARY  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='AUDIT_CHECKLIST_PROJECT_EXECUTION' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE AUDIT_CHECKLIST_PROJECT_EXECUTION  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='FMEA_DATA' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE FMEA_DATA  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='FMEA_DATA_STAGE2' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE FMEA_DATA_STAGE2  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='KPI_BACKUP_2021' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE KPI_BACKUP_2021  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='SQA_PROJECT_CHARTS' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE SQA_PROJECT_CHARTS  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='TASK' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE TASK  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='REQ_LEVEL_MAPPING' AND name='MAPPED_ID_INT' AND system_type_id IN (56)) BEGIN ALTER TABLE REQ_LEVEL_MAPPING  ALTER COLUMN MAPPED_ID_INT varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CSS_BATCH_CUSTOMER_MONTHLY' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CSS_BATCH_CUSTOMER_MONTHLY  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROCESS_MODEL_QUESTIONS' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROCESS_MODEL_QUESTIONS  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CUSTOMER_PROJECTS' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CUSTOMER_PROJECTS  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CONTACTS' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CONTACTS  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CUSTOMER_REPORTS' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CUSTOMER_REPORTS  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='SQA_REPORT_FILES_old' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE SQA_REPORT_FILES_old  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PORTFOLIOS_OWNERS_PROJECT' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PORTFOLIOS_OWNERS_PROJECT  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CRISP_PROJECT_CATEGORY' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CRISP_PROJECT_CATEGORY  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='portfolio_ProjectDel' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE portfolio_ProjectDel  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CRISP_PROJECT_CRITERIA' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CRISP_PROJECT_CRITERIA  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='customer_projects_copy1' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE customer_projects_copy1  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CRISP_PROJECT_VALIDATIONS' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CRISP_PROJECT_VALIDATIONS  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CRISP_SCORES_PROJECT' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CRISP_SCORES_PROJECT  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='APP_ACCESS_CONTROLS' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE APP_ACCESS_CONTROLS  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='AUDIT_SCHEDULE' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE AUDIT_SCHEDULE  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='CRISP_SCORES_PROJECT_copy' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE CRISP_SCORES_PROJECT_copy  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='KPI_BACKUP_Apr04_2022' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE KPI_BACKUP_Apr04_2022  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='temptable' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE temptable  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='TASK_Backup_2022_06_14' AND name='CUST_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE TASK_Backup_2022_06_14  ALTER COLUMN CUST_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='KPI_GOALS' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE KPI_GOALS  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='AUDIT_CHECKLIST_PROJECT_SETUP' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE AUDIT_CHECKLIST_PROJECT_SETUP  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT_CSAT_DATA_old' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT_CSAT_DATA_old  ALTER COLUMN CUSTOMER_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='ENGAGEMENT_OVERVIEW' AND name='CUSTOMER_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE ENGAGEMENT_OVERVIEW  ALTER COLUMN CUSTOMER_ID varchar(50);  END



-- ALTER Scripts for drop Index
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[dbo].[DASHBOARD_DETAILS]') AND name='IX_dashboard_details_CUST_ID')       BEGIN CREATE INDEX IX_dashboard_details_CUST_ID ON [dbo].[DASHBOARD_DETAILS]([CUST_ID]); END
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[dbo].[KPI_GOALS]') AND name='GOAL_IDX')       BEGIN CREATE INDEX GOAL_IDX ON [dbo].[KPI_GOALS]([CUSTOMER_ID], [PROJECT_ID]); END
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[dbo].[PM_PROJECT_SERVICE_AREA_PROCESS_MAPPING]') AND name='IX_PM_PROJECT_SERVICE_AREA_PROCESS_MAPPING')       BEGIN CREATE INDEX IX_PM_PROJECT_SERVICE_AREA_PROCESS_MAPPING ON [dbo].[PM_PROJECT_SERVICE_AREA_PROCESS_MAPPING]([PROJ_ID]); END
-- ALTER Scripts for create constraints
--NO

