If NOT EXISTS(Select 1 from CONFIGURATION_EXT where [KEY] ='QUALITY_TEAM_MAIL')
BEGIN
INSERT into CONFIGURATION_EXT values('QUALITY_TEAM_MAIL','quality@gavstech.com','-1',null,null, 0,1,null,null,null,'104975',Getdate(),'104975',Getdate())
END
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getOpenFindingsForEachAudit' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[getOpenFindingsForEachAudit]
END
GO

CREATE procedure [dbo].getOpenFindingsForEachAudit 
        
@auditIds varchar(max)

AS

BEGIN

SELECT findings.AUDIT_ID, COUNT(*) as OPEN_FINDINGS
FROM AUDIT_CHECKLIST_PROJECT_FINDINGS findings  
INNER JOIN AUDIT_FINDING_STAGES_MAPPING AFM ON AFM.FINDING_ID = findings.ID AND AFM.ISACTIVE = 1  
LEFT JOIN AUDIT_FINDINGS_CAPA capa ON findings.id = capa.finding_id AND capa.isactive = 1 AND capa.issubmitted = 1  
WHERE capa.CORRECTIVE_ACTION_PLAN IS NULL AND capa.CAP_TARGET_DATE IS NULL   
    AND AFM.STAGE_ID = 1 AND AFM.STAGE_STATUS NOT IN ('Auditee Rejected')  
	AND findings.isactive = 1 AND findings.issubmitted = 1
	AND findings.AUDIT_ID in (SELECT * FROM [DBO].[FN_SPLITSTRING](@auditIds,','))   
GROUP BY findings.AUDIT_ID
ORDER BY findings.AUDIT_ID

END
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getOverallTaskDetails' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[getOverallTaskDetails]
END
GO

CREATE PROCEDURE getOverallTaskDetails

@START_DATE DATETIME,
@END_DATE DATETIME  ,
@CUSTOMER_ID varchar(MAX) = '-1',
@PROJECT_ID varchar(MAX) = '-1',
@TASK_CATEGORY varchar(MAX) = '-1'

AS
BEGIN

DECLARE @skipInternalAuditId INT = (SELECT ID FROM PROJECT_CONFIGURATION_SETTING WHERE SETTING_NAME = 'SKIP INTERNAL AUDIT' AND ISACTIVE = 1);

WITH AUDITS AS (
SELECT
T.CUST_ID, T.PROJ_ID, T.ID,T.DESCRIPTION, T.STATUS, T.DUE_DATE, TR.FREQUENCY
FROM
TASK T
LEFT JOIN AUDIT_SCHEDULE ASCH ON ASCH.TITLE = T.DESCRIPTION AND ASCH.CUST_ID = T.CUST_ID AND ASCH.PROJ_ID = T.PROJ_ID
AND ASCH.ISACTIVE = 1 AND (T.PARENT_TASK_ID = ASCH.TASK_ID OR T.ID = ASCH.TASK_ID)
LEFT JOIN TASK_RECURRENCE TR ON T.ID = TR.TASK_ID AND TR.ISACTIVE = 1
LEFT JOIN AUDIT_SCHEDULE_REF ASREF ON ASREF.AUDIT_SCHEDULE_ID = ASCH.ID AND ASREF.ISACTIVE = 1
LEFT JOIN AUDIT_CHECKLIST_EXECUTION_SUMMARY ACT ON T.ID = ACT.ASSESSMENT_ID AND ACT.ISACTIVE = 1
WHERE
T.STATUS NOT IN ('CANCELLED') AND T.ISACTIVE = 1 AND T.DUE_DATE IS NOT NULL
AND COALESCE(T.SCHEDULED_START_DATE, T.DUE_DATE) BETWEEN @START_DATE AND @END_DATE
GROUP BY
T.CUST_ID, T.PROJ_ID, T.ID,T.DESCRIPTION, T.STATUS, T.DUE_DATE, TR.FREQUENCY
)
SELECT
C.CUST_NM, P.PROJ_NM,
ISO_STANDARDS = STUFF((
SELECT ', ' + PIS.STANDARD_NAME
FROM PROJECT_ISO_STANDARD PIS
INNER JOIN PROJECT_ISO_STANDARD_MAPPING PIM ON PIS.ID = PIM.ISO_STANDARD_ID
WHERE PIM.PROJECT_ID = P.PROJ_ID AND PIS.ISACTIVE = 1
FOR XML PATH('')), 1, 2, ''),
CERTIFICATION_SCOPES = STUFF((
SELECT ', ' + PIS.STANDARD_NAME + ' - ' + PCS.SCOPE_NAME
FROM PROJECT_CERTIFICATION_SCOPE PCS
INNER JOIN PROJECT_CERTIFICATION_SCOPE_MAPPING PCM ON PCS.ID = PCM.CERTIFICATION_SCOPE_ID
INNER JOIN PROJECT_ISO_STANDARD PIS ON PIS.ID = PCS.ISO_STANDARD_ID
WHERE PCM.PROJECT_ID = P.PROJ_ID AND PCS.ISACTIVE = 1
FOR XML PATH('')), 1, 2, ''),
CONVERT(VARCHAR, P.START_DATE, 107) AS START_DATE,
CONVERT(VARCHAR, P.END_DATE, 107) AS END_DATE,
HEADCOUNT = (SELECT COUNT(*) FROM PROJ_RESOURCE PR WHERE PR.PROJ_ID = P.PROJ_ID AND PR.BILL_FLG =1 AND PR.CURR_INDC ='Y' AND PR.END_DATE >= GETDATE()),
AUDIT_TITLE = A.DESCRIPTION,
AUDIT_STATUS = A.STATUS,
LAST_AUDITED_DATE = CONVERT(VARCHAR, A.DUE_DATE, 107),
FREQUENCY = A.FREQUENCY,
AUDITS_PLANNED = (SELECT COUNT(ID) FROM AUDITS WHERE STATUS NOT IN ('CANCELLED','COMPLETED') AND CUST_ID = C.CUST_ID AND PROJ_ID = P.PROJ_ID),
AUDITS_COMPLETED = (SELECT COUNT(ID) FROM AUDITS WHERE STATUS IN ('COMPLETED') AND CUST_ID = C.CUST_ID AND PROJ_ID = P.PROJ_ID),
P.PROJ_ID, C.CUST_ID
FROM
PROJECT P
INNER JOIN
CUSTOMER C ON P.CUST_ID = C.CUST_ID
LEFT JOIN
AUDITS A ON A.PROJ_ID = P.PROJ_ID AND A.ID = (SELECT TOP 1 ID FROM AUDITS WHERE PROJ_ID = P.PROJ_ID ORDER BY ID DESC)
LEFT JOIN
TASK T ON T.ID = A.ID AND T.ISACTIVE = 1 AND ISNULL(T.STATUS,'')!='CANCELLED'
WHERE
P.PROJ_ID NOT IN (SELECT PROJ_ID FROM PROJECT_CONFIGURATION_DATA WHERE ISACTIVE = 1 AND IS_APPROVED = 1 AND CONFIGURATION_SETTING_ID = @skipInternalAuditId
AND END_DATE IS NULL OR END_DATE > GETDATE())
AND COALESCE(T.SCHEDULED_START_DATE, T.DUE_DATE) BETWEEN @START_DATE AND @END_DATE
AND ((@CUSTOMER_ID = '-1' AND @PROJECT_ID = '-1')
OR (@CUSTOMER_ID <> '-1' AND @PROJECT_ID = '-1' AND C.CUST_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@CUSTOMER_ID, ',')))
OR (@CUSTOMER_ID <> '-1' AND @PROJECT_ID <> '-1' AND P.PROJ_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJECT_ID, ','))))
AND (@TASK_CATEGORY = '-1' OR T.TASK_CATEGORY_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@TASK_CATEGORY, ',')))
GROUP BY
C.CUST_NM, P.PROJ_NM, P.START_DATE, P.END_DATE, P.PROJ_ID, C.CUST_ID, A.DESCRIPTION, A.STATUS, A.ID, A.DUE_DATE, A.FREQUENCY
ORDER BY
P.PROJ_NM, C.CUST_NM
END
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getTaskDetailsByDateRange' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[getTaskDetailsByDateRange]
END
GO

CREATE PROCEDURE [dbo].[getTaskDetailsByDateRange]            

@START_DATE DATETIME,            
@END_DATE DATETIME  ,          
@EMP_ID varchar(20)   ,
@CUSTOMER_ID varchar(MAX) = '-1',      
@PROJECT_ID varchar(MAX) = '-1',      
@TASK_CATEGORY varchar(MAX) = '-1',      
@Range varchar(1) ='Y'    

AS

BEGIN
   
DECLARE @skipInternalAuditId INT = (SELECT ID FROM PROJECT_CONFIGURATION_SETTING WHERE SETTING_NAME = 'SKIP INTERNAL AUDIT' AND ISACTIVE = 1)            

 IF @Range<>'A'      
 BEGIN       
 SELECT distinct  T.ID, DATEPART(M, coalesce(T.SCHEDULED_START_DATE, t.due_date)) MONTH_ID,      
 DATEPART(Q, coalesce(T.SCHEDULED_START_DATE, t.due_date)) QUARTER_ID,      
 DATEPART(WK, coalesce(T.SCHEDULED_START_DATE, t.due_date)) WEEK_ID,      
 DATEPART(D, coalesce(T.SCHEDULED_START_DATE, t.due_date)) DAY_ID,       
 DATENAME(dw,coalesce(T.SCHEDULED_START_DATE, t.due_date)) DATE_NAME,      
 cast(DATEADD( DAY , 2 - DATEPART(WEEKDAY, coalesce(T.SCHEDULED_START_DATE, t.due_date)), CAST (coalesce(T.SCHEDULED_START_DATE, t.due_date) AS DATE )) as varchar(10)) [Week_Start_Date],      
  cast(DATEADD( DAY , 8 - DATEPART(WEEKDAY, coalesce(T.SCHEDULED_START_DATE, t.due_date)), CAST (coalesce(T.SCHEDULED_START_DATE, t.due_date) AS DATE )) as varchar(10))  [Week_End_Date],      
 T.CUST_ID, C.CUST_NM, T.PROJ_ID, P.PROJ_NM, TT.ID TASK_TYPE_ID, TT.TITLE TASK_TYPE,TC.ID TASK_CATEGORY_ID, TC.TITLE TASK_CATEGORY, T.DESCRIPTION, T.STATUS,         
 T.SCHEDULED_START_DATE, T.SCHEDULED_DURATION, T.DUE_DATE, TC.COLOR_BG, TC.COLOR_MG, T.OWNER, T.Assigned_to, A.AUDITOR_EMP_ID           
 ,'' AS FREQUENCY       
 FROM [TASK] T   (NOLOCK)       
  INNER JOIN TASK_TYPE TT  (NOLOCK)  ON TT.ID =  T.TASK_TYPE_ID and T.ISACTIVE = 1       
  INNER JOIN TASK_CATEGORY TC  (NOLOCK)  ON TC.ID = T.TASK_CATEGORY_ID            
  LEFT JOIN AUDIT_SCHEDULE A   (NOLOCK) ON T.ID = A.TASK_ID          
  LEFT JOIN AUDIT_SCHEDULE_REF AE   (NOLOCK) on AE.AUDIT_SCHEDULE_ID = A.id and [key] = 'AUDITEE_EMP_ID'          
  LEFT JOIN CUSTOMER C   (NOLOCK) ON C.CUST_ID = T.CUST_ID            
  LEFT JOIN PROJECT P  (NOLOCK)  ON P.PROJ_ID = T.PROJ_ID            
  LEFT JOIN PROJ_RESOURCE PR on p.proj_id = pr.proj_id and pr.emp_id = @emp_id and pr.end_date > Getdate()     
 WHERE 
 P.PROJ_ID NOT IN (SELECT PROJ_ID FROM PROJECT_CONFIGURATION_DATA WHERE ISACTIVE = 1 AND IS_APPROVED = 1 AND CONFIGURATION_SETTING_ID = @skipInternalAuditId
					AND END_DATE IS NULL OR END_DATE > GETDATE()) AND 
 Due_Date is not null and ((coalesce(T.SCHEDULED_START_DATE, t.due_date) >= @START_DATE and  coalesce(T.SCHEDULED_START_DATE, t.due_date) <= @END_DATE  ))          
 and (@EMP_ID ='-99' OR t.OWNER= @EMP_ID OR T.ASSIGNED_TO= @EMP_ID OR A.AUDITOR_EMP_ID = @EMP_ID OR AE.VALUE= @EMP_ID or pr.emp_id = @emp_id)
AND (
    (@CUSTOMER_ID = '-1' AND @PROJECT_ID = '-1')
	OR
    (@CUSTOMER_ID <> '-1' AND @PROJECT_ID = '-1' AND C.CUST_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@CUSTOMER_ID, ',')))
    OR
    (@CUSTOMER_ID <> '-1' AND @PROJECT_ID <> '-1' AND P.PROJ_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJECT_ID, ','))))
AND (@TASK_CATEGORY = '-1' OR T.TASK_CATEGORY_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@TASK_CATEGORY, ',')))

END       
 
ELSE       
 
BEGIN       
       
 SELECT distinct  T.ID, DATEPART(M, coalesce(T.SCHEDULED_START_DATE, t.due_date)) MONTH_ID,      
 DATEPART(Q, coalesce(T.SCHEDULED_START_DATE, t.due_date)) QUARTER_ID,      
 DATEPART(WK, coalesce(T.SCHEDULED_START_DATE, t.due_date)) WEEK_ID,      
 DATEPART(D, coalesce(T.SCHEDULED_START_DATE, t.due_date)) DAY_ID,       
 DATENAME(dw,coalesce(T.SCHEDULED_START_DATE, t.due_date)) DATE_NAME,      
 cast(DATEADD( DAY , 2 - DATEPART(WEEKDAY, coalesce(T.SCHEDULED_START_DATE, t.due_date)), CAST (coalesce(T.SCHEDULED_START_DATE, t.due_date) AS DATE )) as varchar(10)) [Week_Start_Date],      
 cast(DATEADD( DAY , 8 - DATEPART(WEEKDAY, coalesce(T.SCHEDULED_START_DATE, t.due_date)), CAST (coalesce(T.SCHEDULED_START_DATE, t.due_date) AS DATE )) as varchar(10))  [Week_End_Date],      
 T.CUST_ID, C.CUST_NM, T.PROJ_ID, P.PROJ_NM, TT.ID TASK_TYPE_ID, TT.TITLE TASK_TYPE,TC.ID TASK_CATEGORY_ID, TC.TITLE TASK_CATEGORY, T.DESCRIPTION, T.STATUS,         
 T.SCHEDULED_START_DATE, T.SCHEDULED_DURATION, T.DUE_DATE, TC.COLOR_BG, TC.COLOR_MG, T.OWNER, T.Assigned_to, A.AUDITOR_EMP_ID     ,      
 ISNULL(TR.FREQUENCY ,'On-Going') AS FREQUENCY      
 FROM [TASK] T   (NOLOCK)       
  INNER JOIN TASK_TYPE TT  (NOLOCK)  ON TT.ID =  T.TASK_TYPE_ID and T.ISACTIVE = 1          
  INNER JOIN TASK_CATEGORY TC  (NOLOCK)  ON TC.ID = T.TASK_CATEGORY_ID            
  LEFT JOIN AUDIT_SCHEDULE A   (NOLOCK) ON T.ID = A.TASK_ID         
  LEFT JOIN AUDIT_SCHEDULE_REF AE   (NOLOCK) on AE.AUDIT_SCHEDULE_ID = A.id and [key] = 'AUDITEE_EMP_ID'          
  LEFT JOIN CUSTOMER C   (NOLOCK) ON C.CUST_ID = T.CUST_ID            
  LEFT JOIN PROJECT P  (NOLOCK)  ON P.PROJ_ID = T.PROJ_ID
  LEFT JOIN PROJ_RESOURCE PR on p.proj_id = pr.proj_id and pr.emp_id = @emp_id and pr.end_date > Getdate()            
  LEFT JOIN TASK_RECURRENCE TR (NOLOCK) ON T.ID =TR.TASK_ID      
 
WHERE 
 P.PROJ_ID NOT IN (SELECT PROJ_ID FROM PROJECT_CONFIGURATION_DATA WHERE ISACTIVE = 1 AND IS_APPROVED = 1 AND CONFIGURATION_SETTING_ID = @skipInternalAuditId
					AND END_DATE IS NULL OR END_DATE > GETDATE()) AND 
 Due_Date is not null and ((  coalesce(T.SCHEDULED_START_DATE, t.due_date) >= @START_DATE and       
coalesce(T.SCHEDULED_START_DATE, t.due_date) <= @END_DATE  )) AND t.TASK_TYPE_ID=1      
AND (
    (@CUSTOMER_ID = '-1' AND @PROJECT_ID = '-1')
	OR
    (@CUSTOMER_ID <> '-1' AND @PROJECT_ID = '-1' AND C.CUST_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@CUSTOMER_ID, ',')))
    OR
    (@CUSTOMER_ID <> '-1' AND @PROJECT_ID <> '-1' AND P.PROJ_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJECT_ID, ','))))
AND (@TASK_CATEGORY = '-1' OR T.TASK_CATEGORY_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@TASK_CATEGORY, ',')))

END 
 
END  
GO  

IF NOT EXISTS(Select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'RISK_REPOSITORY' AND COLUMN_NAME='THREATS')
BEGIN
ALTER TABLE RISK_REPOSITORY ADD THREATS VARCHAR(MAX) NULL
END
GO

IF NOT EXISTS(Select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'RISK_REPOSITORY' AND COLUMN_NAME='VULNERABILITIES')
BEGIN
ALTER TABLE RISK_REPOSITORY ADD VULNERABILITIES VARCHAR(MAX) NULL
END
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getAllRiskFromRepository' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[getAllRiskFromRepository]
END
GO
  
CREATE PROCEDURE getAllRiskFromRepository  
  
 @customerId varchar(50),
 @projectId varchar(50)
  
as  
begin  
  
SELECT ST.TITLE as SERVICE_TOWER_TITLE,RR.RISK_DESCRIPTION as DESCRIPTION,RR.RISK_IMPACT as IMPACT,RR.LIKELIHOOD as PROBABILITY_SCALE,  
RR.CONSEQUENCES as IMPACT_SCALE,RR.RISK_TREATMENT_STRATEGY,RR.THREATS as THREATS, RR.VULNERABILITIES as VULNERABILITIES, 
RR.ID as RISK_REPOSITORY_ID,ST.ID as SERVICE_TOWER_ID  
from RISK_REPOSITORY RR inner join RISK_REPOSITORY2SERVICE_TOWER RRS on RRS.RISK_REPOSITORY_ID = RR.ID  
inner join PROCESS_SERVICE_AREA_PROJECT_MAPPING PSM on PSM.SERVICE_AREA_ID = RRS.SERVICE_TOWER_ID  
inner join PROCESS_SERVICE_AREA_NEW ST on ST.ID = RRS.SERVICE_TOWER_ID  
  
where PSM.CUST_ID = @customerId and PSM.PROJ_ID = @projectId and  
ST.ISACTIVE=1 and RRS.ISACTIVE=1 and RR.ISACTIVE=1 and PSM.ISACTIVE=1  
order by SERVICE_TOWER_TITLE, DESCRIPTION  
  
end  
go

IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getRiskRepositoryData' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[getRiskRepositoryData]
END
GO

CREATE PROCEDURE [dbo].[getRiskRepositoryData] 
AS
Begin

SELECT 
    SERVICE_TOWERS,
    DESCRIPTION,
    IMPACT,
    PROBABILITY_SCALE,
    IMPACT_SCALE,
    RISK_TREATMENT_STRATEGY,
	THREATS,
	VULNERABILITIES,
    RISK_REPOSITORY_ID
FROM (
    SELECT 
        STUFF((
                SELECT ', ' + ST2.TITLE
                FROM PROCESS_SERVICE_AREA_NEW ST2
                INNER JOIN RISK_REPOSITORY2SERVICE_TOWER RRS2 ON ST2.ID = RRS2.SERVICE_TOWER_ID
                WHERE RRS2.RISK_REPOSITORY_ID = RR.ID and RRS2.ISACTIVE =1 and ST2.ISACTIVE = 1 
                FOR XML PATH('')), 1, 1, '') AS SERVICE_TOWERS,
        RR.RISK_DESCRIPTION AS DESCRIPTION,
        RR.RISK_IMPACT AS IMPACT,
        RR.LIKELIHOOD AS PROBABILITY_SCALE,
        RR.CONSEQUENCES AS IMPACT_SCALE,
        RR.RISK_TREATMENT_STRATEGY,
		RR.THREATS AS THREATS,
		RR.VULNERABILITIES AS VULNERABILITIES,
        RR.ID AS RISK_REPOSITORY_ID,
        ROW_NUMBER() OVER (PARTITION BY RR.ID ORDER BY RR.ID) AS RowNum
    FROM 
        RISK_REPOSITORY RR
    INNER JOIN 
        RISK_REPOSITORY2SERVICE_TOWER RRS ON RRS.RISK_REPOSITORY_ID = RR.ID
    INNER JOIN 
        PROCESS_SERVICE_AREA_NEW ST ON ST.ID = RRS.SERVICE_TOWER_ID
    WHERE 
        ST.ISACTIVE = 1 
        AND RRS.ISACTIVE = 1 
        AND RR.ISACTIVE = 1
) AS Subquery
WHERE 
    RowNum = 1
ORDER BY 
    SERVICE_TOWERS,
    DESCRIPTION,
	RISK_REPOSITORY_ID;

	END
	GO

IF NOT EXISTS(Select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'ASSESSMENT_STATUS_HISTORY' AND COLUMN_NAME='IS_RETAIN_CAPA')
BEGIN

ALTER TABLE ASSESSMENT_STATUS_HISTORY ADD IS_RETAIN_CAPA BIT NULL

END 
GO

IF NOT EXISTS(Select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = 'TASK' AND COLUMN_NAME='REASON_FOR_CANCEL')
BEGIN
ALTER TABLE TASK ADD REASON_FOR_CANCEL VARCHAR(MAX) NULL
END
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='reports_getCSSInitatedDetails' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[reports_getCSSInitatedDetails]
END
GO

CREATE PROCEDURE [dbo].[reports_getCSSInitatedDetails]  
@STARTDATE DATETIME,  
@ENDDATE DATETIME  
AS  
BEGIN  
SET @STARTDATE = CONVERT(DATETIME, CONVERT(VARCHAR(11),@STARTDATE, 111 ) + ' 00:00:00', 111)  
SET @ENDDATE = CONVERT(DATETIME, CONVERT(VARCHAR(11),@ENDDATE, 111 ) + ' 23:59:59', 111)  
SELECT C.CUST_NM,P.PROJ_NM,CSS.STATUS,  
CONVERT(VARCHAR(10), CSS.SURVEY_SENT_DATE, 110) AS CSS_SENT_DATE,  
CONVERT(VARCHAR(10), CSS.SURVEY_RECEIVED_DATE, 110) AS CSS_RECEIVED_DATE,  
(select top 1 frst_nm from emp_info where emp_id = p.QUALITY_SPOC) QUALITY_SPOC, (select top 1 frst_nm from emp_info where emp_id = p.PROJ_PM_EMP_ID) PM,  
(select top 1 frst_nm from emp_info where emp_id = p.PROJ_DM_EMP_ID) CSM,(select top 1 frst_nm from emp_info where emp_id = p.PROJ_AM_EMP_ID) AM     ,  
CSS.DISPLAY_NAME as CUSTOMER_NAME,CSS.EMAIL_ID as CUSTOMER_MAIL,  
[Year - Quarter] =  (select Left( frequency,1) + Convert(varchar,sequence) + ' - ' + Convert(varchar,  Year) from  CSS_BATCHES where id= b.id ),  
P.CUST_ID, P.PROJ_ID  
FROM PROJECT P  
LEFT OUTER JOIN CSS_BATCH_CUSTOMERS CSS ON CSS.PROJ_ID = P.PROJ_ID  
INNER JOIN CSS_BATCHES B ON B.ID = CSS.BATCH_ID AND B.START_DATE >= @STARTDATE AND B.END_DATE <= @ENDDATE  
INNER JOIN CUSTOMER C on C.CUST_ID = P.CUST_ID  
WHERE P.END_DATE > @STARTDATE AND PROJ_NM NOT LIKE 'INT-%' AND P.CUST_ID !='0' AND P.PROJ_ID = PARENT_PROJ_ID

union all

SELECT C.CUST_NM,P.PROJ_NM,CSS.STATUS,  
CONVERT(VARCHAR(10), CSS.SURVEY_SENT_DATE, 110) AS CSS_SENT_DATE,  
CONVERT(VARCHAR(10), CSS.SURVEY_RECEIVED_DATE, 110) AS CSS_RECEIVED_DATE,  
(select top 1 frst_nm from emp_info where emp_id = p.QUALITY_SPOC) QUALITY_SPOC, (select top 1 frst_nm from emp_info where emp_id = p.PROJ_PM_EMP_ID) PM,  
(select top 1 frst_nm from emp_info where emp_id = p.PROJ_DM_EMP_ID) CSM,(select top 1 frst_nm from emp_info where emp_id = p.PROJ_AM_EMP_ID) AM     ,  
CSS.DISPLAY_NAME as CUSTOMER_NAME,CSS.EMAIL_ID as CUSTOMER_MAIL,  
[Year - Quarter] =  (SELECT 
    CASE 
        WHEN month BETWEEN 4 AND 6 THEN 'Q1'
        WHEN month BETWEEN 7 AND 9 THEN 'Q2'
        WHEN month BETWEEN 10 AND 12 THEN 'Q3'
        ELSE 'Q4'
    END + ' - ' + CONVERT(varchar, Year) 
FROM CSS_BATCH_MONTHLY where id= b.id ),  
P.CUST_ID, P.PROJ_ID  
from CSS_BATCH_CUSTOMER_MONTHLY CSS 
INNER JOIN CSS_BATCH_MONTHLY B ON B.ID = CSS.BATCH_MONTHLY_ID AND B.START_DATE >= @STARTDATE AND B.END_DATE <= @ENDDATE
INNER JOIN CUSTOMER C on C.CUST_ID = CSS.CUST_ID 
LEFT JOIN PROJECT P on P.PROJ_ID = CSS.PROJ_ID
order by C.CUST_NM, P.PROJ_ID
end
go
