USE CSP
GO

IF NOT EXISTS(Select 1 from sys.tables where name ='FMEA_DATA' AND type='U')
  BEGIN

CREATE TABLE FMEA_DATA
(
[ID] [int] IDENTITY(1,1) NOT NULL,
[FMEA_TYPE_ID] [int] NOT NULL,
[SERVICE_AREA_ID] [int] NOT NULL,
[PROCESS_ID] [int] NOT NULL,
[SERVICE_LEVEL_IDENTIFIER_ID] [INT] NOT NULL,
[TASK_ID] [int] NOT NULL,
[FUNCTION_ACTIVITIES] NVARCHAR(MAX),
[POTENTIAL_FAILURE_MODE] NVARCHAR(MAX),
[POTENTIAL_FAILURE_EFFECT] NVARCHAR(MAX),
[POTENTIAL_CAUSE_FACTOR] [INT],
[POTENTIAL_CAUSE] NVARCHAR(MAX),
[RECOMMENDED_DETECTIVE_CONTROL] NVARCHAR(MAX),
[RECOMMENDED_PREVENTIVE_CONTROL] NVARCHAR(MAX),
[FMEA_STATUS] [INT] DEFAULT(0),
[CREATED_BY] [varchar](50) NOT NULL,
[CREATED_DATE] [datetime] NOT NULL DEFAULT (getdate()),
[UPDATED_BY] [varchar](50) NOT NULL,
[UPDATED_DATE] [datetime] NOT NULL DEFAULT (getdate()),
[ISACTIVE] [bit] NOT NULL DEFAULT ((1))
)

END

GO


IF NOT EXISTS(Select 1 from sys.tables where name ='SERVICE_LEVEL_IDENTIFIER' AND type='U')
  BEGIN

CREATE TABLE SERVICE_LEVEL_IDENTIFIER
(
[ID] [int] IDENTITY(1,1) NOT NULL,
[SERVICE_LEVEL_IDENTIFIER] VARCHAR(50) NOT NULL,
[SERVICE_LEVEL_TITLE] VARCHAR(50) NOT NULL,
[SERVICE_AREA_ID] [int] NOT NULL,
[CREATED_BY] [varchar](50) NOT NULL,
[CREATED_DATE] [datetime] NOT NULL DEFAULT (getdate()),
[UPDATED_BY] [varchar](50) NOT NULL,
[UPDATED_DATE] [datetime] NOT NULL DEFAULT (getdate()),
[ISACTIVE] [bit] NOT NULL DEFAULT ((1))
)

END

GO

IF NOT EXISTS(Select 1 from sys.tables where name ='FMEA_TASKS' AND type='U')
  BEGIN


CREATE TABLE FMEA_TASKS
(
[ID] [int] IDENTITY(1,1) NOT NULL,
[SERVICE_AREA_ID] [int] NOT NULL,
[PROCESS_ID] [int] NOT NULL,
[SERVICE_LEVEL_IDENTIFIER_ID] [INT] NOT NULL,
[TASK_TITLE] VARCHAR(MAX),
[TASK_CATEGORY_ID] [INT],
[ISACTIVE] [bit] NOT NULL DEFAULT ((1))
)
END

GO


IF EXISTS(Select 1 from sys.procedures where name ='USP_ADD_SERVICELEVELIDENTIFIER' AND type='P')
BEGIN
       DROP PROCEDURE [dbo].[USP_ADD_SERVICELEVELIDENTIFIER]
END
GO


CREATE PROCEDURE USP_ADD_SERVICELEVELIDENTIFIER
(
@SERVICE_LEVEL_IDENTIFIER VARCHAR(50),
@SERVICE_LEVEL_TITLE VARCHAR(50),
@SERVICE_AREA_ID INT,
@EMPID varchar(100)
)
AS
BEGIN
INSERT INTO SERVICE_LEVEL_IDENTIFIER(SERVICE_LEVEL_IDENTIFIER,SERVICE_LEVEL_TITLE,SERVICE_AREA_ID,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE,ISACTIVE)
SELECT @SERVICE_LEVEL_IDENTIFIER,@SERVICE_LEVEL_TITLE,@SERVICE_AREA_ID,@EMPID,GETDATE(),@EMPID,GETDATE(),1
END

GO


IF EXISTS(Select 1 from sys.procedures where name ='USP_FMEA_ADD_TASKS' AND type='P')
BEGIN
       DROP PROCEDURE [dbo].[USP_FMEA_ADD_TASKS]
END
GO

CREATE PROCEDURE USP_FMEA_ADD_TASKS
(
@SERVICE_AREA_ID int,
@PROCESS_ID int,
@SERVICE_LEVEL_IDENTIFIER_ID int,
@TASK_TITLE VARCHAR(MAX),
@TASK_CATEGORY_ID INT
)
AS
BEGIN
INSERT INTO FMEA_TASKS(SERVICE_AREA_ID,PROCESS_ID,SERVICE_LEVEL_IDENTIFIER_ID,TASK_TITLE,TASK_CATEGORY_ID)
SELECT @SERVICE_AREA_ID,@PROCESS_ID,@SERVICE_LEVEL_IDENTIFIER_ID,@TASK_TITLE,@TASK_CATEGORY_ID

END

GO


IF EXISTS(Select 1 from sys.procedures where name ='USP_GET_FMEA_DATA' AND type='P')
BEGIN
       DROP PROCEDURE [dbo].[USP_GET_FMEA_DATA]
END
GO


CREATE PROCEDURE USP_GET_FMEA_DATA
(
@FMEA_TYPE_ID INT,
@SERVICE_AREA_ID INT,
@PROCESS_ID INT,
@SERVICE_LEVEL_IDENTIFIER_ID INT,
@TASK_ID INT
)
AS
BEGIN
SELECT FD.[ID], FD.[FMEA_TYPE_ID], FD.[SERVICE_AREA_ID], PS.[TITLE] AS 'SERVICE_TOWER',FD.[PROCESS_ID], PA.TITLE AS 'PROCESS', 
FD.[SERVICE_LEVEL_IDENTIFIER_ID], SLI.SERVICE_LEVEL_IDENTIFIER AS 'SERVICE_LEVEL', 
FD.[TASK_ID], FT.TASK_TITLE AS 'TASK',(SELECT OPTIONS FROM PARAMETER_TABLE WHERE ID=FT.TASK_CATEGORY_ID) AS 'TASK_CATEGORY',
FD.[FUNCTION_ACTIVITIES],FD.[POTENTIAL_FAILURE_MODE],FD.[POTENTIAL_FAILURE_EFFECT],FD.[POTENTIAL_CAUSE_FACTOR],
PT.[OPTIONS] AS 'POTENTIAL_CAUSE_FACTOR_OPTIONS',
FD.[POTENTIAL_CAUSE],FD.[RECOMMENDED_DETECTIVE_CONTROL],FD.[RECOMMENDED_PREVENTIVE_CONTROL],
FD.[FMEA_STATUS],
FD.[CREATED_BY],FD.[CREATED_DATE],FD.[UPDATED_BY],FD.[UPDATED_DATE]
FROM FMEA_DATA FD JOIN FMEA_TASKS FT ON FD.TASK_ID = FT.ID JOIN 
PROCESS_SERVICE_AREA_NEW PS ON PS.ID = FD.SERVICE_AREA_ID  JOIN
PROCESS_AREA PA ON PA.ID = FD.PROCESS_ID JOIN
SERVICE_LEVEL_IDENTIFIER SLI ON SLI.ID = FD.SERVICE_LEVEL_IDENTIFIER_ID JOIN
PARAMETER_TABLE PT ON FD.[POTENTIAL_CAUSE_FACTOR] = PT.ID JOIN
PARAMETER_TABLE PT1 ON FD.FMEA_TYPE_ID = PT1.ID 
WHERE FD.FMEA_TYPE_ID = @FMEA_TYPE_ID AND FD.SERVICE_AREA_ID = @SERVICE_AREA_ID AND FD.PROCESS_ID = @PROCESS_ID AND 
FD.SERVICE_LEVEL_IDENTIFIER_ID = @SERVICE_LEVEL_IDENTIFIER_ID AND FD.TASK_ID = @TASK_ID
AND FD.POTENTIAL_CAUSE_FACTOR = PT.ID
END

GO

IF not exists(SELECT 1 FROM PARAMETER_TABLE where NAME ='FMEA_TYPE')
BEGIN
	INSERT INTO PARAMETER_TABLE(NAME,OPTIONS,SORT_ORDER,ISACTIVE) values
	( 'FMEA_TYPE','Product',1,1 ),
	( 'FMEA_TYPE','Service',1,1 ),
	( 'FMEA_TYPE','Process',1,1 ),
	( 'FMEA_TYPE','Software',1,1 )
END

GO


IF not exists(SELECT 1 FROM PARAMETER_TABLE where NAME ='TASK_CATEGORY')
BEGIN
INSERT INTO PARAMETER_TABLE(NAME,OPTIONS,SORT_ORDER,ISACTIVE) values
( 'TASK_CATEGORY','Call Handling',1,1),
( 'TASK_CATEGORY','Email Handling',1,1 ),
( 'TASK_CATEGORY','Incident Handling',1,1 ),
( 'TASK_CATEGORY','Status Reporting',1,1 )
END

GO



IF not exists(SELECT 1 FROM PARAMETER_TABLE where NAME ='POTENTIAL_CAUSE_FACTOR')
BEGIN
INSERT INTO PARAMETER_TABLE(NAME,OPTIONS,SORT_ORDER,ISACTIVE) values
(  'POTENTIAL_CAUSE_FACTOR','People[Who]',1,1 ),
(  'POTENTIAL_CAUSE_FACTOR','Equipment(H/W S/W) [What]',1,1 ),
(  'POTENTIAL_CAUSE_FACTOR','Environment[Condition]',1,1 ),
(  'POTENTIAL_CAUSE_FACTOR','Material[What]',1,1 ),
(  'POTENTIAL_CAUSE_FACTOR','Method[How]',1,1 ),
(  'POTENTIAL_CAUSE_FACTOR','Measure[Result]',1,1 )
END

GO


IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = 'process_model_id'
          AND Object_ID = Object_ID('audit_checklist_project_execution'))
BEGIN
    alter table audit_checklist_project_execution
    add process_model_id int not null  CONSTRAINT df_model
    DEFAULT 1
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = 'process_model_id'
          AND Object_ID = Object_ID('audit_checklist_project_findings'))
BEGIN
    alter table audit_checklist_project_findings
	add process_model_id int not null  CONSTRAINT df_find__model
	DEFAULT 1 
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = 'process_model_id'
          AND Object_ID = Object_ID('AUDIT_CHECKLIST_PROJECT_SAMPLES_AUDITED'))
BEGIN
  alter table AUDIT_CHECKLIST_PROJECT_SAMPLES_AUDITED
  add process_model_id int not null  CONSTRAINT df_sample__model
  DEFAULT 1
END

IF EXISTS(Select 1 from sys.procedures where name ='getAllFindingsByTypeforCustomer' AND type='P')
BEGIN
       DROP PROCEDURE [dbo].[getAllFindingsByTypeforCustomer]
END
GO


CREATE procedure   
  getAllFindingsByTypeforCustomer  
  as   
  begin  
 with cte1 as  
    (select find.ID, find.FINDING_TYPE, find.FINDING_DESCRIPTION, exe.CUSTOMER_ID, exe.PROJECT_ID, find.created_date, ROW_NUMBER() over (partition by find.id order by find.audit_id) as rn1 from AUDIT_CHECKLIST_PROJECT_FINDINGS find  
  inner join AUDIT_CHECKLIST_PROJECT_EXECUTION exe on find.AUDIT_ID = exe.AUDIT_ID and find.ISACTIVE = 1 and find.issubmitted = 1 and exe.ISACTIVE = 1  
  where Month(find.created_date) = Month(GETDATE()) and YEAR(find.created_date) = YEAR(GETDATE())   
    
  )  
  
  select * from cte1 where rn1 = 1  
  end

GO

IF EXISTS(Select 1 from sys.procedures where name ='getCheckPointsforProjectNew' AND type='P')
BEGIN
       DROP PROCEDURE [dbo].[getCheckPointsforProjectNew]
END
GO
                 
create PROCEDURE getCheckPointsforProjectNew                        
  @CUSTOMER_ID int,                          
  @PROJECT_ID varchar(50),                        
  @SERVICE_AREAS  varchar(max)                          
  AS                        
  BEGIN                        
                        
SELECT DISTINCT 0 AS ID,CONF.CUST_ID,CONF.PROJ_ID, area.id as SERVICE_AREA_ID, AREA.TITLE AS SERVICE_AREA_NAME, model.ID as PROCESS_MODEL_ID, model.DESCRIPTION as PROCESS_MODEL_DESCRIPTION, PROCESS.id as process_id, PROCESS.TITLE AS PROCESS_DESCRIPTION,  
  
    
NULL AS PLANNED_AUDIT_START_DATE,                      
NULL AS PLANNED_AUDIT_END_DATE,NULL AS ACTUAL_AUDIT_START_DATE,                          
NULL AS ACTUAL_AUDIT_END_DATE,NULL AS AUDIT_PLANNED_HOURS,NULL AS AUDIT_ACTUAL_HOURS,                          
NULL AS AUDIT_TITLE,NULL AS AUDITOR_NAME,WEIGHT.ID as WEIGHTAGE_ID, weight.WEIGHTAGE_SCORE, WEIGHT.WEIGHTAGE_TITLE,QUES.ID AS APPLICABLE_QUESTIONS,CHK.VERSION AS VERSIONID, QUES.TITLE AS LOOK_FOR,                      
CHK.status_list_id AS CHECKLIST_STATUS_LIST_ID,chk.FINDINGSTYPE_ID, chk.TITLE as CHECKLIST_NAME,chk.ID as CHECKLIST_ID, chk.VERSION as VERSIONID, chk.CORRECTIVE_ACTION_TRACKING as CORRECTIVE_ACTION_TRACKING,chk.IS_WEIGHTAGE_APPLICABLE ,  NULL AS STATUS,  
                   
NULL AS NOTES,NULL AS FINDINGS_ID,NULL AS CREATED_DATE,NULL AS CREATED_BY,NULL AS  UPDATED_DATE,                          
NULL AS UPDATED_BY,CAST(1 AS bit) AS ISACTIVE  FROM PM_PROJECT_SERVICE_AREA_PROCESS_MAPPING CONF                          
INNER JOIN PROCESS PROCESS on PROCESS.ID = CONF.PROCESS_ID AND PROCESS.ISACTIVE = 1                        
INNER JOIN PROCESS_MODEL_PROCESS_MAPPING PRO on PRO.PROCESS_ID = process.ID  AND PRO.ISACTIVE = 1 AND CONF.ISACTIVE = 1                        
INNER JOIN pm_process_questions_mapping MAPP on MAPP.PROCESS_ID = CONF.PROCESS_ID  and MAPP.SERVICE_AREA_ID = CONF.SERVICE_AREA_ID AND MAPP.ISACTIVE = 1                   
INNER JOIN PM_CHECKLIST_QUESTIONS QUES ON QUES.ID = MAPP.question_id AND QUES.ISACTIVE = 1                        
INNER JOIN PM_CHECKLIST CHK ON CHK.ID = QUES.CHECKLIST_ID AND CHK.ISACTIVE = 1                     
INNER JOIN PROCESS_SERVICE_AREA_NEW AREA on AREA.ID = CONF.SERVICE_AREA_ID  AND AREA.ISACTIVE = 1                 
AND (@SERVICE_AREAS = '' or (AREA.ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@SERVICE_AREAS,','))))                       
INNER JOIN PROCESS_MODEL MODEL on MODEL.ID = CONF.PROCESS_MODEL_ID  AND MODEL.ISACTIVE =1      
left JOIN AUDIT_CHECKLIST_WEIGHTAGE WEIGHT on WEIGHT.ID = QUES.WEIGHTAGE_ID                         
where CONF.PROJ_ID = @PROJECT_ID and CONF.CUST_ID = @CUSTOMER_ID                        
order by AREA.TITLE                      
                        
END  

GO

IF EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = 'Customer_Project_Name'
          AND Object_ID = Object_ID('CUST_REQ_REF'))
BEGIN
    alter table CUST_REQ_REF
    drop column Customer_Project_Name
END

GO


IF EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = 'Category_Id'
          AND Object_ID = Object_ID('CUST_REQ_REF'))
BEGIN
    alter table CUST_REQ_REF
    drop column Category_Id
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'CSM_GENERATED_COMMENTS' AND Object_ID = Object_ID('crisp_scores_project'))
BEGIN
   alter table crisp_scores_project add CSM_GENERATED_COMMENTS varchar(max)
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'CURRENT_STATUS' AND Object_ID = Object_ID('AUDIT_CHECKLIST_PROJECT_EXECUTION'))
BEGIN
   alter table AUDIT_CHECKLIST_PROJECT_EXECUTION add CURRENT_STATUS VARCHAR(250)
END

GO

IF NOT EXISTS(Select 1 from sys.tables where name ='CHECKLIST_SCORES_BY_AUDIT' AND type='U')
  BEGIN


CREATE TABLE [dbo].[CHECKLIST_SCORES_BY_AUDIT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CHECKLIST_ID] [int] NOT NULL,
	[AUDIT_ID] [int] NOT NULL,
	[SCORE] [decimal](10, 2) NULL,
	[PERCENTAGE_SCORE] [decimal](10, 2) NULL,
	[CREATED_BY] [varchar](250) NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[UPDATED_DATE] [datetime] NOT NULL,
	[UPDATED_BY] [varchar](250) NULL,
	[ISACTIVE] [bit] NOT NULL
)

END

IF EXISTS(Select 1 from sys.procedures where name ='getallassessment' AND type='P')
BEGIN
       DROP PROCEDURE [dbo].[getallassessment]
END
GO
                 
CREATE procedure    
getallassessment    
@custid int,    
@startdate datetime,    
@enddate datetime    
as    
begin    
 select t.*, c.CUST_NM, p.PROJ_NM  ,(select top 1 FRST_NM from BAS_TEST..EMP_INFO e where e.emp_id = t.OWNER) AS 'OWNER_NAME',  
 (select top 1 FRST_NM from BAS_TEST..EMP_INFO e where e.emp_id = t.ASSIGNED_TO) AS 'ASSIGNED_TO_NAME'  
  from task t    
 inner join bas_test..CUSTOMER c on t.CUST_ID = c.CUST_ID and t.CUST_ID = @custid    
 inner join BAS_TEST..PROJECT p on p.PROJ_ID = t.PROJ_ID    
   
 where t.SCHEDULED_START_DATE >= @startdate and t.SCHEDULED_START_DATE <= @enddate and t.ISACTIVE = 1    
end   

go

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'APPROACH' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
   alter table PROJECT_INNOVATION
    add APPROACH varchar(max)
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'BEFORE_CASES_COUNT' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
    alter table PROJECT_INNOVATION
    add  BEFORE_CASES_COUNT decimal(10, 1)
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'AFTER_CASES_COUNT' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
    alter table PROJECT_INNOVATION
    add  AFTER_CASES_COUNT decimal(10, 1)
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'BEFORE_FTECOST_HOUR' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
   alter table PROJECT_INNOVATION
   add  BEFORE_FTECOST_HOUR decimal(10, 2)
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'AFTER_FTECOST_HOUR' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
   alter table PROJECT_INNOVATION
   add  AFTER_FTECOST_HOUR decimal(10, 2)
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'BEFORE_FTECOST_MONTH' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
   alter table PROJECT_INNOVATION
    add  BEFORE_FTECOST_MONTH decimal(10, 2)
END

GO


IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'AFTER_FTECOST_MONTH' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
   alter table PROJECT_INNOVATION
    add  AFTER_FTECOST_MONTH decimal(10, 2)
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'CUSTOMER_PERSONHOUR_SAVINGS' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
   alter table PROJECT_INNOVATION
    add  CUSTOMER_PERSONHOUR_SAVINGS decimal(10, 2)
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'BEFORE_FTESPENT_MONTH' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
   alter table PROJECT_INNOVATION
   add  BEFORE_FTESPENT_MONTH decimal(10, 2)
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'AFTER_FTESPENT_MONTH' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
   alter table PROJECT_INNOVATION
   add  AFTER_FTESPENT_MONTH decimal(10, 2)
END

GO
IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'BEFORE_COST' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
   alter table PROJECT_INNOVATION
    add  BEFORE_COST varchar(500)
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'AFTER_COST' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
  alter table PROJECT_INNOVATION
  add  AFTER_COST varchar(500)
END

GO


IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'BEFORE_LEAD_TIME' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
  alter table PROJECT_INNOVATION
    add  BEFORE_LEAD_TIME decimal(10, 2)
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'AFTER_LEAD_TIME' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
  alter table PROJECT_INNOVATION
  add  AFTER_LEAD_TIME decimal(10, 2)
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'CUSTOMER_BUSINESS_VALUE' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
  alter table PROJECT_INNOVATION
 add CUSTOMER_BUSINESS_VALUE varchar(max)
END

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE Name = 'INTERNAL_SAVINGS' AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
  alter table PROJECT_INNOVATION
  add  INTERNAL_SAVINGS varchar(500)
END

GO



