USE CSP

IF EXISTS(Select 1 from sys.procedures where name ='getIdeasAndInnovationsDetails' AND type='P')
BEGIN
       DROP PROCEDURE [dbo].[getIdeasAndInnovationsDetails]
END
GO

CREATE PROCEDURE [dbo].[getIdeasAndInnovationsDetails]               
  AS                
  BEGIN    
  declare @startdate datetime  
  declare @enddate datetime  
  
  if(MONTH(GETDATE()) >= 4)  
   begin  
 set @startdate =  DATEFROMPARTS(year(getdate()), 4, 1);  
 set @enddate = DATEFROMPARTS(year(getdate()) + 1, 3 ,31);  
   end  
  else  
 begin  
  set @startdate =  DATEFROMPARTS(year(getdate())-1, 4, 1);  
  set @enddate = DATEFROMPARTS(year(getdate()), 3 ,31);      
 end      
           
    SELECT p.cust_id AS CUSTOMER_ID, [PROJECT_ID], pp.PORTFOLIO_ID, I.AUTOMATE AS AUTOMATIONS,   
 I.ISINNOVATION AS INNOVATIONS,         
  I.ISPROCESSIMPROVEMENT AS IMPROVMENTS,  I.CUSTOMER_PERSONHOUR_SAVINGS AS   EFFORTS_SAVED_PERSON_HOUR,      
  i.CUSTOMER_SAVINGS  AS DOLLARS ,  i.STATUS      
  FROM [CSP].[dbo].[PROJECT_INNOVATION] I              
  inner join BAS.dbo.project p on p.proj_id =  I.PROJECT_ID    and i.STATUS != 'Closed' and I.ISACTIVE = 1           
  LEFT OUTER JOIN portfolio_project pp on pp.proj_id =  I.PROJECT_ID        
  where p.end_date >= getdate()  and I.IDENTIFIED_DATE >= @startdate and I.IDENTIFIED_DATE <= @enddate  
             
  END 


  GO


  
IF EXISTS(Select 1 from sys.procedures where name ='GET_CI_TRACKER_DATA' AND type='P')
BEGIN
       DROP PROCEDURE [dbo].[GET_CI_TRACKER_DATA]
END
GO


CREATE PROCEDURE [dbo].[GET_CI_TRACKER_DATA]
@AUTOMATE BIT,
@CUSTOMER_SAVINGS BIT,
@STARTDATE DATETIME,
@ENDDATE DATETIME,
@PROJIDS VARCHAR(MAX),
@CUSTID int,
@INNOVATION bit,
@IMPROVEMENT bit,
@ALL bit

AS
BEGIN
if(@ALL = 1)
	SELECT C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE AS 'PORTFOLIO_NM', P.PROJ_ID, P.PROJ_NM, 
	SUM(CASE WHEN  PI.STATUS = 'Completed'  THEN 1 ELSE 0 END) 'COMPLETED',
	SUM(CASE WHEN  PI.STATUS in ('Planning', 'Execution', 'Identified')   THEN 1 ELSE 0 END) 'INPROGRESS',

	ABS(FLOOR(CASE WHEN SUM([BEFORE_ERROR]) > 0 THEN (SUM([BEFORE_ERROR]) -  SUM([AFTER_ERROR])) / SUM([BEFORE_ERROR]) 
	ELSE 0
	END * 100)) AS 'QUALITY_REDUCTION_OF_ERRORS',

	ABS(FLOOR(CASE WHEN SUM([BEFORE_LEAD_TIME]) > 0  THEN (SUM([BEFORE_LEAD_TIME])  -  SUM([AFTER_LEAD_TIME])) / SUM([BEFORE_LEAD_TIME]) 
	ELSE 0
	END * 100)) AS 'REDUCTION_IN_LEAD_TIME', 

	ABS(FLOOR(CASE WHEN SUM([BEFORE_CYCLE_TIME]) > 0  THEN (SUM([BEFORE_CYCLE_TIME])  -  SUM([AFTER_CYCLE_TIME])) / SUM([BEFORE_CYCLE_TIME]) 
	ELSE 0
	END * 100)) AS 'REDUCTION_IN_CYCLE_TIME', 

	--SUM([BEFORE_CYCLE_TIME])  -  SUM([AFTER_CYCLE_TIME])  AS 'REDUCTION_IN_CYCLE_TIME', 

	ABS(FLOOR(SUM(BEFORE_ERROR))) AS 'TOTAL_BEFORE_ERROR',
	ABS(FLOOR(SUM(AFTER_ERROR))) AS 'TOTAL_AFTER_ERROR',
	ABS(FLOOR(SUM(BEFORE_LEAD_TIME))) AS 'TOTAL_BEFORE_LEAD',
	ABS(FLOOR(SUM(AFTER_LEAD_TIME))) AS 'TOTAL_AFTER_LEAD',

	ABS(FLOOR(SUM(BEFORE_CYCLE_TIME))) AS 'TOTAL_BEFORE_CYCLE',
	ABS(FLOOR(SUM(AFTER_CYCLE_TIME))) AS 'TOTAL_AFTER_CYCLE',

	FLOOR(CASE WHEN SUM([BEFORE_EFFORT]) > 0 THEN (SUM([BEFORE_EFFORT]) - SUM(AFTER_EFFORT)) / SUM([BEFORE_EFFORT])
	ELSE 0 END  * 100) AS 'AUTOMATION_INDEX',
	SUM(BEFORE_EFFORT) AS 'BEFORE_EFFORT',
	SUM(AFTER_EFFORT) AS 'AFTER_EFFORT',

	ABS(FLOOR(SUM(CUSTOMER_PERSONHOUR_SAVINGS))) AS 'SAVING_PER_YEAR_EFFORT',   
	ABS(FLOOR(SUM(CAST(INTERNAL_SAVINGS AS NUMERIC(10, 2)))))  AS 'SAVINGS_IN_USD',
	ABS(FLOOR(SUM(CUSTOMER_SAVINGS)))  AS 'HARD_BENEFITS',
	' ' AS 'SOFT_BENEFITS',
	ABS(FLOOR(SUM(FINANCIAL_REVENUE))) AS 'REVENUE',
	ABS(FLOOR(SUM(FINANCIAL_OPERATING_COST))) AS 'OPERATING_COST',
	ABS(FLOOR(SUM(FINANCIAL_PROFITABILITY))) AS 'PROFITABILITY'
	FROM project_innovation PI 

	INNER JOIN [BAS].DBO.PROJECT P ON PI.PROJECT_ID = P.PROJ_ID 
	INNER JOIN [BAS].DBO.CUSTOMER C ON C.CUST_ID = P.CUST_ID
	LEFT JOIN  PORTFOLIO_PROJECT PP on PP.PROJ_ID = p.PROJ_ID and pp.ISACTIVE = 1
	left join PORTFOLIO port on port.ID = pp.PORTFOLIO_ID and port.ISACTIVE = 1

	WHERE PI.IDENTIFIED_DATE >= @STARTDATE and PI.IDENTIFIED_DATE <= @ENDDATE 
	AND (@CUSTID = -1 OR C.CUST_ID = @CUSTID) 
	AND (@PROJIDS = '' OR PI.PROJECT_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,','))) and PI.ISACTIVE = 1
	GROUP BY C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE, P.PROJ_ID, P.PROJ_NM
else
	SELECT C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE AS 'PORTFOLIO_NM', P.PROJ_ID, P.PROJ_NM, 
	SUM(CASE WHEN PI.STATUS = 'Completed'  THEN 1 ELSE 0 END) 'COMPLETED',
	SUM(CASE WHEN PI.STATUS in ('Planning', 'Execution', 'Identified') THEN 1 ELSE 0 END) 'INPROGRESS',

	ABS(FLOOR(CASE WHEN SUM([BEFORE_ERROR]) > 0 THEN (SUM([BEFORE_ERROR]) -  SUM([AFTER_ERROR])) / SUM([BEFORE_ERROR]) 
	ELSE 0
	END * 100)) AS 'QUALITY_REDUCTION_OF_ERRORS',

	ABS(FLOOR(CASE WHEN SUM([BEFORE_LEAD_TIME]) > 0  THEN (SUM([BEFORE_LEAD_TIME])  -  SUM([AFTER_LEAD_TIME])) / SUM([BEFORE_LEAD_TIME]) 
	ELSE 0
	END * 100)) AS 'REDUCTION_IN_LEAD_TIME', 

	ABS(FLOOR(CASE WHEN SUM([BEFORE_CYCLE_TIME]) > 0  THEN (SUM([BEFORE_CYCLE_TIME])  -  SUM([AFTER_CYCLE_TIME])) / SUM([BEFORE_CYCLE_TIME]) 
	ELSE 0
	END * 100)) AS 'REDUCTION_IN_CYCLE_TIME', 

	ABS(FLOOR(SUM(BEFORE_ERROR))) AS 'TOTAL_BEFORE_ERROR',
	ABS(FLOOR(SUM(AFTER_ERROR))) AS 'TOTAL_AFTER_ERROR',
	ABS(FLOOR(SUM(BEFORE_LEAD_TIME))) AS 'TOTAL_BEFORE_LEAD',
	ABS(FLOOR(SUM(AFTER_LEAD_TIME))) AS 'TOTAL_AFTER_LEAD',

	ABS(FLOOR(SUM(BEFORE_CYCLE_TIME))) AS 'TOTAL_BEFORE_CYCLE',
	ABS(FLOOR(SUM(AFTER_CYCLE_TIME))) AS 'TOTAL_AFTER_CYCLE',

	FLOOR(CASE WHEN SUM([BEFORE_EFFORT]) > 0 THEN (SUM([BEFORE_EFFORT]) - SUM(AFTER_EFFORT)) / SUM([BEFORE_EFFORT])
	ELSE 0 END  * 100) AS 'AUTOMATION_INDEX',
	SUM(BEFORE_EFFORT) AS 'BEFORE_EFFORT',
	SUM(AFTER_EFFORT) AS 'AFTER_EFFORT',

	ABS(FLOOR(SUM(CUSTOMER_PERSONHOUR_SAVINGS))) AS 'SAVING_PER_YEAR_EFFORT',   
	ABS(FLOOR(SUM(CAST(INTERNAL_SAVINGS AS NUMERIC(10, 2)))))  AS 'SAVINGS_IN_USD',
	ABS(FLOOR(SUM(CUSTOMER_SAVINGS)))  AS 'HARD_BENEFITS',
	' ' AS 'SOFT_BENEFITS',
	ABS(FLOOR(SUM(FINANCIAL_REVENUE))) AS 'REVENUE',
	ABS(FLOOR(SUM(FINANCIAL_OPERATING_COST))) AS 'OPERATING_COST',
	ABS(FLOOR(SUM(FINANCIAL_PROFITABILITY))) AS 'PROFITABILITY'
	FROM project_innovation PI 

	INNER JOIN [BAS].DBO.PROJECT P ON PI.PROJECT_ID = P.PROJ_ID 
	INNER JOIN [BAS].DBO.CUSTOMER C ON C.CUST_ID = P.CUST_ID
	LEFT JOIN  PORTFOLIO_PROJECT PP on PP.PROJ_ID = p.PROJ_ID and pp.ISACTIVE = 1
	left join PORTFOLIO port on port.ID = pp.PORTFOLIO_ID and port.ISACTIVE = 1

	WHERE PI.IDENTIFIED_DATE >= @STARTDATE and PI.IDENTIFIED_DATE <= @ENDDATE 
	AND (@CUSTID = -1 OR C.CUST_ID = @CUSTID) 
	AND (@PROJIDS = '' OR PI.PROJECT_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,','))) 
	AND PI.ISACTIVE = 1
	AND (
		(@AUTOMATE = 1 AND PI.AUTOMATE = @AUTOMATE) OR 
		(@INNOVATION = 1 AND PI.ISINNOVATION = @INNOVATION) OR
		(@IMPROVEMENT = 1 AND PI.ISPROCESSIMPROVEMENT = @IMPROVEMENT) OR
	    (@CUSTOMER_SAVINGS = 1 AND (PI.CUSTOMER_SAVINGS IS NOT NULL OR CUSTOMER_BUSINESS_VALUE IS NOT NULL))
		)

	GROUP BY C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE, P.PROJ_ID, P.PROJ_NM
END

GO

--- Ragu 

 
 

IF not exists(SELECT 1 FROM PARAMETER_TABLE where NAME ='UOM')
BEGIN
	INSERT INTO PARAMETER_TABLE(NAME,OPTIONS,SORT_ORDER,ISACTIVE,OPTIONS_ID) values
	( 'UOM','Minutes',1,1,1 ),
	( 'UOM','Hours',1,1,2 ),
	( 'UOM','Days',1,1,3 )	
END

GO
 
 
 DECLARE @FIRSTTIME BIT = 0;
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE NAME = 'BEFORE_TIME_TAKEN'
          AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
    SET @FIRSTTIME = 1
    ALTER TABLE PROJECT_INNOVATION
	ADD BEFORE_TIME_TAKEN DECIMAL(10,2) 
	DEFAULT 0 
END
 

GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE NAME = 'AFTER_TIME_TAKEN'
          AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
    ALTER TABLE PROJECT_INNOVATION
	ADD AFTER_TIME_TAKEN DECIMAL(10,2) 
	DEFAULT 0 
END


GO

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE NAME = 'BEFORE_CYCLE_TIME_UOM'
          AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
    ALTER TABLE PROJECT_INNOVATION
	ADD BEFORE_CYCLE_TIME_UOM INT 
	DEFAULT 1 
END

GO


IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE NAME = 'AFTER_CYCLE_TIME_UOM'
          AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
    ALTER TABLE PROJECT_INNOVATION
	ADD AFTER_CYCLE_TIME_UOM INT 
	DEFAULT 1 
END

GO


IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE NAME = 'BEFORE_LEAD_TIME_UOM'
          AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
    ALTER TABLE PROJECT_INNOVATION
	ADD BEFORE_LEAD_TIME_UOM INT 
	DEFAULT 1 
END

GO


IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE NAME = 'AFTER_LEAD_TIME_UOM'
          AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
    ALTER TABLE PROJECT_INNOVATION
	ADD AFTER_LEAD_TIME_UOM INT 
	DEFAULT 1 
END

GO


IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE NAME = 'BEFORE_TIME_TAKEN_UOM'
          AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
    ALTER TABLE PROJECT_INNOVATION
	ADD BEFORE_TIME_TAKEN_UOM INT 
	DEFAULT 1 
END

GO


IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE NAME = 'AFTER_TIME_TAKEN_UOM'
          AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
    ALTER TABLE PROJECT_INNOVATION
	ADD AFTER_TIME_TAKEN_UOM INT 
	DEFAULT 1 
END

GO



IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE NAME = 'IS_ONETIME'
          AND Object_ID = Object_ID('PROJECT_INNOVATION'))
BEGIN
    ALTER TABLE PROJECT_INNOVATION
	ADD IS_ONETIME BIT 
	DEFAULT 0
END

GO


IF EXISTS(Select 1 from sys.procedures where name ='getIdeasByProjectId' AND type='P')
BEGIN
       DROP PROCEDURE [dbo].[getIdeasByProjectId]
END

GO


CREATE procedure [dbo].[getIdeasByProjectId]          
  @PROJIDS VARCHAR(MAX)           
as              
begin               
 select distinct I.*, 
 
 ABS(CEILING(CASE WHEN ([BEFORE_ERROR]) > 0 THEN (([BEFORE_ERROR]) -  ([AFTER_ERROR])) / ([BEFORE_ERROR]) 
	ELSE 0
	END * 100)) AS 'QUALITY_REDUCTION_OF_ERRORS',    
	
	ABS(CEILING(CASE WHEN ([BEFORE_LEAD_TIME]) > 0  THEN (([BEFORE_LEAD_TIME])  -  ([AFTER_LEAD_TIME])) / ([BEFORE_LEAD_TIME]) 
	ELSE 0
	END * 100)) AS 'REDUCTION_IN_LEAD_TIME',  

	CASE 
	
	WHEN BEFORE_LEAD_TIME_UOM = 1 THEN  
	CAST(ABS(CEILING(CASE WHEN ([BEFORE_LEAD_TIME]) > 0  THEN (([BEFORE_LEAD_TIME])  -  ([AFTER_LEAD_TIME])) / ([BEFORE_LEAD_TIME]) 
	ELSE 0
	END * 100)) AS VARCHAR(50)) + ' mins' 
	
	
	WHEN BEFORE_LEAD_TIME_UOM = 2 THEN  
	CAST(ABS(CEILING(CASE WHEN ([BEFORE_LEAD_TIME]) > 0  THEN (([BEFORE_LEAD_TIME])  -  ([AFTER_LEAD_TIME])) / ([BEFORE_LEAD_TIME]) 
	ELSE 0
	END * 100)) AS VARCHAR(50)) + ' hrs'

	WHEN BEFORE_LEAD_TIME_UOM = 3 THEN  
	CAST(ABS(CEILING(CASE WHEN ([BEFORE_LEAD_TIME]) > 0  THEN (([BEFORE_LEAD_TIME])  -  ([AFTER_LEAD_TIME])) / ([BEFORE_LEAD_TIME]) 
	ELSE 0
	END * 100)) AS VARCHAR(50)) + ' days'	
	
	END AS 'REDUCTION_IN_LEAD_TIME_DATA',

	ABS(CEILING(CASE WHEN ([BEFORE_CYCLE_TIME]) > 0  THEN (([BEFORE_CYCLE_TIME])  -  ([AFTER_CYCLE_TIME])) / ([BEFORE_CYCLE_TIME]) 
	ELSE 0
	END * 100)) AS 'REDUCTION_IN_CYCLE_TIME', 

	CASE 
	
	WHEN BEFORE_CYCLE_TIME_UOM = 1 THEN
	CAST(ABS(CEILING(CASE WHEN ([BEFORE_CYCLE_TIME]) > 0  THEN (([BEFORE_CYCLE_TIME])  -  ([AFTER_CYCLE_TIME])) / ([BEFORE_CYCLE_TIME]) 
	ELSE 0
	END * 100)) AS VARCHAR(50)) + ' mins'

	WHEN BEFORE_CYCLE_TIME_UOM = 2 THEN
	CAST(ABS(CEILING(CASE WHEN ([BEFORE_CYCLE_TIME]) > 0  THEN (([BEFORE_CYCLE_TIME])  -  ([AFTER_CYCLE_TIME])) / ([BEFORE_CYCLE_TIME]) 
	ELSE 0
	END * 100)) AS VARCHAR(50)) + ' hrs'


	WHEN BEFORE_CYCLE_TIME_UOM = 3 THEN
	CAST(ABS(CEILING(CASE WHEN ([BEFORE_CYCLE_TIME]) > 0  THEN (([BEFORE_CYCLE_TIME])  -  ([AFTER_CYCLE_TIME])) / ([BEFORE_CYCLE_TIME]) 
	ELSE 0
	END * 100)) AS VARCHAR(50)) + ' days'

	END AS 'REDUCTION_IN_CYCLE_TIME_DATA',

 ABS(CEILING((CUSTOMER_PERSONHOUR_SAVINGS))) AS 'SAVING_PER_YEAR_EFFORT',

 ABS(CEILING(CASE WHEN ([BEFORE_LEAD_TIME]) > 0  THEN (([BEFORE_EFFORT])  -  ([AFTER_EFFORT])) / ([BEFORE_EFFORT]) 
	ELSE 0
	END * 100)) AS 'AUTOMATION_INDEX', 

 ABS(CEILING((CAST(INTERNAL_SAVINGS AS NUMERIC(10, 2)))))  AS 'SAVINGS_IN_USD',
	ABS(CEILING((CUSTOMER_SAVINGS)))  AS 'HARD_BENEFITS',

ABS(CEILING((FINANCIAL_REVENUE))) AS 'REVENUE',
	ABS(CEILING((FINANCIAL_OPERATING_COST))) AS 'OPERATING_COST',
	ABS(CEILING((FINANCIAL_PROFITABILITY))) AS 'PROFITABILITY',
              
 P.CUST_ID, PP.PORTFOLIO_ID, PF.TITLE AS PORTFOLIO_NM, P.PROJ_NM              
 FROM PROJECT_INNOVATION I              
 INNER JOIN BAS_TEST.dbo.PROJECT P ON I.PROJECT_ID = P.PROJ_ID and  P.PROJ_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,','))   AND  I.ISACTIVE = 1                   
 LEFT OUTER JOIN PORTFOLIO_PROJECT PP ON PP.PROJ_ID = P.PROJ_ID              
 LEFT OUTER JOIN PORTFOLIO PF ON PF.ID = PP.PORTFOLIO_ID              
              
 ORDER BY I.IDENTIFIED_DATE desc            
End




GO


--IF @FIRSTTIME =  1 

--BEGIN

--update PROJECT_INNOVATION
--set BEFORE_TIME_TAKEN = BEFORE_LEAD_TIME,
--BEFORE_TIME_TAKEN_UOM = 1



--Update PROJECT_INNOVATION
--set AFTER_TIME_TAKEN = AFTER_LEAD_TIME,
--AFTER_TIME_TAKEN_UOM = 1


--update PROJECT_INNOVATION
--set BEFORE_LEAD_TIME = null,
--AFTER_LEAD_TIME = null

--END

--go

--merge
IF EXISTS(Select 1 from sys.procedures where name ='getIdeasAndInnovationsDetails' AND type='P')
BEGIN
       DROP PROCEDURE [dbo].[getIdeasAndInnovationsDetails]
END
GO

CREATE PROCEDURE [dbo].[getIdeasAndInnovationsDetails]               
  AS                
  BEGIN    
  declare @startdate datetime  
  declare @enddate datetime  
  
  if(MONTH(GETDATE()) >= 4)  
   begin  
 set @startdate =  DATEFROMPARTS(year(getdate()), 4, 1);  
 set @enddate = DATEFROMPARTS(year(getdate()) + 1, 3 ,31);  
   end  
  else  
 begin  
  set @startdate =  DATEFROMPARTS(year(getdate())-1, 4, 1);  
  set @enddate = DATEFROMPARTS(year(getdate()), 3 ,31);      
 end      
           
    SELECT p.cust_id AS CUSTOMER_ID, [PROJECT_ID], pp.PORTFOLIO_ID, I.AUTOMATE AS AUTOMATIONS,   
 I.ISINNOVATION AS INNOVATIONS,         
  I.ISPROCESSIMPROVEMENT AS IMPROVMENTS,  I.CUSTOMER_PERSONHOUR_SAVINGS AS   EFFORTS_SAVED_PERSON_HOUR,      
  i.CUSTOMER_SAVINGS  AS DOLLARS ,  i.STATUS      
  FROM [CSP].[dbo].[PROJECT_INNOVATION] I              
  inner join BAS.dbo.project p on p.proj_id =  I.PROJECT_ID    and i.STATUS != 'Closed' and I.ISACTIVE = 1           
  LEFT OUTER JOIN portfolio_project pp on pp.proj_id =  I.PROJECT_ID        
  where p.end_date >= getdate()  and I.IDENTIFIED_DATE >= @startdate and I.IDENTIFIED_DATE <= @enddate  
             
  END 

  GO

IF not exists(SELECT 1 FROM PARAMETER_TABLE where NAME ='AUDIT_CATEGORY' and OPTIONS = 12)
BEGIN
INSERT INTO PARAMETER_TABLE(NAME,OPTIONS,SORT_ORDER,ISACTIVE,OPTIONS_ID) values
('AUDIT_CATEGORY', 12, 1, 1, 0)
END

IF EXISTS(Select 1 from sys.procedures where name ='getProcessByServiceArea' AND type='P')
BEGIN
       DROP PROCEDURE [dbo].[getProcessByServiceArea]
END
GO

CREATE PROCEDURE [dbo].[getProcessByServiceArea]        
@SERVICE_AREA_ID int        
        
AS        
BEGIN           
;        
WITH PMIDS AS (        
SELECT DISTINCT PM.ID, PM.TITLE FROM PROCESS_MODEL_PROCESS_MAPPING  MP      
INNER JOIN PROCESS_MODEL PM ON PM.ID = PROCESS_MODEL_ID     and pm.ISACTIVE =1  AND MP.ISACTIVE =1  
WHERE PROCESS_ID IN(SELECT PROCESS_ID FROM PROCESS_SERVICE_AREA_MAPPING    
WHERE SERVICE_AREA_ID = @SERVICE_AREA_ID    and ISACTIVE =1    
) )        
    
        
SELECT distinct PROCESS_MODEL_ID, PM.TITLE PROCESS_MODEL_TITLE        
, P.PROCESS_AREA_ID, PA.TITLE PROCESS_AREA_TITLE        
, PROCESS_ID, P.TITLE PROCESS_TITLE, P.DESCRIPTION PROCESS_DESCRIPTION        
FROM PROCESS_MODEL_PROCESS_MAPPING MP        
INNER JOIN PROCESS_MODEL PM ON PM.ID = PROCESS_MODEL_ID AND MP.ISACTIVE =1 AND PM.ISACTIVE =1  
INNER JOIN PROCESS P ON PROCESS_ID = P.ID  AND P.ISACTIVE =1       
INNER JOIN PROCESS_AREA PA ON PA.ID = P.PROCESS_AREA_ID AND PA.ISACTIVE =1  
WHERE  PROCESS_MODEL_ID IN (SELECT ID FROM PMIDS)        
     
        
END
GO

IF not exists(Select 1 from sys.tables where name ='CHECKLIST_EXECUTION_CC_DETAILS' AND type='U')
BEGIN

CREATE TABLE [dbo].[CHECKLIST_EXECUTION_CC_DETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ASSESSMENT_ID] [int] NOT NULL,
	[CC_EMP_ID] [int] NULL,
	[TO_EMP_ID] [int] NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[CREATED_BY] [int] NULL,
	[UPDATED_BY] [int] NULL,
	[ISACTIVE] [bit] NULL,
	[UPDATED_DATE] [datetime] NOT NULL
)

END
GO



IF not exists(Select 1 from sys.tables where name ='PROJECT_CONFIGURATION_SETTING' AND type='U')
BEGIN

CREATE TABLE [dbo].[PROJECT_CONFIGURATION_SETTING](

	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Setting_Name] [varchar](100) NOT NULL,
	[Setting_Type] [int] NOT NULL,
	[Min_Threshhold] [int] NULL,
	[Max_Threshhold] [int] NULL,
	[Values_Collection] [varchar](max) NOT NULL,
	[isActive] [bit] NOT NULL,
	[Created_Date] [datetime] NOT NULL,
	[Created_By] [varchar](25) NOT NULL,
	[Updated_Date] [datetime] NOT NULL,
	[Updated_By] [varchar](25) NOT NULL
)

END
GO

IF not exists(Select 1 from sys.tables where name ='PROJECT_CONFIGURATION_DATA' AND type='U')
BEGIN

	CREATE TABLE [dbo].[PROJECT_CONFIGURATION_DATA](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Cust_Id] [int] NOT NULL,
	[Proj_Id] [varchar](50) NOT NULL,
	[Configuration_Setting_Id] [int] NOT NULL,
	[Int_Value] [int] NULL,
	[Bit_Value] [bit] NULL,
	[String_Value] [varchar](max) NULL,
	[Is_Approved] [bit]  NULL,
	[Comments] [varchar](max) NOT NULL,
	[Approved_By] [varchar](50) NULL,
	[Approval_Comments] [varchar](max) NULL,
	[End_date] [datetime] NULL,
	[isActive] [bit] NOT NULL,
	[Created_Date] [datetime] NOT NULL,
	[Created_By] [varchar](25) NOT NULL,
	[Updated_Date] [datetime] NOT NULL,
	[Updated_By] [varchar](25) NOT NULL
)

END
GO


IF not exists(select 1 from [CSP].[dbo].[APP_CONTROLS] where RESOURCE_ID=47)
BEGIN

INSERT INTO [CSP].[dbo].[APP_CONTROLS]
           ([RESOURCE_ID],[RESOURCE_TYPE],[RESOURCE_NAME],[COMMENTS],[CREATED_BY],[CREATED_DATE],[UPDATED_BY],[UPDATED_DATE],[ISACTIVE])
     VALUES(47, 'Control', 'Settings > PROJECT SETTINGS', null, 103724, GETDATE(), 103724, GETDATE(),1)

END
GO

IF not exists(select 1 from [CSP].[dbo].[APP_CONTROL_FEATURES] where RESOURCE_ID=47 and FEATURE='VIEW')
BEGIN

insert into csp.dbo.APP_CONTROL_FEATURES values (47,'VIEW', null, 103724, GETDATE(), 103724, GETDATE(),1)

END
GO

IF not exists(select 1 from [CSP].[dbo].[APP_ACCESS_CONTROLS] where RESOURCE_ID=47)
BEGIN

insert into csp.dbo.APP_ACCESS_CONTROLS
values (47, 1, 1, '',null,'', 0,0,0,0,0,null , 103724, GETDATE(), 103724, GETDATE(),1),
(47, 1, 2, '',null,'',  0,0,0,0,0,null , 103724, GETDATE(), 103724, GETDATE(),1),
(47, 1, 3, '',null,'',  0,0,0,0,0,null , 103724, GETDATE(), 103724, GETDATE(),1),
(47, 1, 4, '',null,'',  0,0,0,0,0,null , 103724, GETDATE(), 103724, GETDATE(),1),
(47, 1, 5, '',null,'',  0,0,0,0,0,null , 103724, GETDATE(), 103724, GETDATE(),1),
(47, 1, 6, '',null,'',  0,0,0,0,0,null , 103724, GETDATE(), 103724, GETDATE(),1),
(47, 1, 7, '',null,'',  0,0,0,0,0,null , 103724, GETDATE(), 103724, GETDATE(),1),
(47, 1, 8, '',null,'',  0,0,0,0,0,null , 103724, GETDATE(), 103724, GETDATE(),1),
(47, 1, 9, '',null,'',  0,0,0,0,0,null , 103724, GETDATE(), 103724, GETDATE(),1),
(47, 1, 10, '',null,'',  0,0,0,0,0,null , 103724, GETDATE(), 103724, GETDATE(),1),
(47, 1, 11, '',null,'',  0,0,0,0,0,null , 103724, GETDATE(), 103724, GETDATE(),1)

END
GO