IF NOT EXISTS(Select 1 from sys.tables where name ='KPI_MASTER' AND type='U')
BEGIN

CREATE TABLE KPI_MASTER
(
	ID int IDENTITY(1,1) NOT NULL,
	SERVICE_AREA varchar(100) NOT NULL,
	ABBREVIATION varchar(100) NULL,
	KPI_NAME varchar(100) NOT NULL,
	SUPPORT_WINDOW varchar(100) NULL,
	FREQUENCY varchar(100) NOT NULL,
	PRIORITY varchar(100) NULL,
	SLA_TARGET_UNIT_OF_MEASUREMENT varchar(100) NOT NULL,
	GLOBAL_KPI_CATEGORY_ID int NULL,
	MODE_ID int NULL,
	CREATED_BY varchar(20) NOT NULL,
	CREATED_DATE Datetime NOT NULL,
	UPDATED_BY varchar(20) NOT NULL,
	UPDATED_DATE Datetime NOT NULL,
	ISACTIVE bit NOT NULL
)

END
GO

IF NOT EXISTS(Select 1 from sys.tables where name ='KPI_TARGET_MASTER' AND type='U')
BEGIN

CREATE TABLE KPI_TARGET_MASTER
(
	ID int IDENTITY(1,1) NOT NULL,
	KPI_MASTER_ID int NOT NULL,
	START_DATE Datetime NOT NULL,
	END_DATE Datetime NOT NULL,
	SLA_TARGET_VERYHIGH_DESCRIPTION varchar(100) NULL,
	SLA_TARGET_VERYHIGH_OPERATOR varchar(100) NULL,
	SLA_TARGET_VERYHIGH_VALUE decimal(9,2) NULL,
	SLA_TARGET_HIGH_DESCRIPTION varchar(100) NULL,
	SLA_TARGET_HIGH_OPERATOR varchar(100) NULL,
	SLA_TARGET_HIGH_VALUE decimal(9,2) NULL,
	SLA_TARGET_MEDIUM_DESCRIPTION varchar(100) NULL,
	SLA_TARGET_MEDIUM_OPERATOR varchar(100) NULL,
	SLA_TARGET_MEDIUM_VALUE decimal(9,2) NULL,
	SLA_TARGET_LOW_DESCRIPTION varchar(100) NULL,
	SLA_TARGET_LOW_OPERATOR varchar(100) NULL,
	SLA_TARGET_LOW_VALUE decimal(9,2) NULL,
	EXPECTED_SERVICE_LEVEL decimal(9,2) NULL,
    MINIMUM_SERVICE_LEVEL decimal(9,2) NULL,
	SPECIFICATION_LIMIT varchar(100) NULL,
	CREATED_BY varchar(20) NOT NULL,
	CREATED_DATE Datetime NOT NULL,
	UPDATED_BY varchar(20) NOT NULL,
	UPDATED_DATE Datetime NOT NULL,
	ISACTIVE bit NOT NULL
)

END
GO

IF NOT EXISTS(Select 1 from sys.tables where name ='KPI_MASTER2PRODUCT_SERVICE_LEVEL_METRICS' AND type='U')
BEGIN

CREATE TABLE KPI_MASTER2PRODUCT_SERVICE_LEVEL_METRICS
(
	ID int IDENTITY(1,1) NOT NULL,
	KPI_MASTER_ID int NOT NULL,
	PRODUCT_SERVICE_LEVEL_METRICS_ID int NOT NULL,
	CREATED_BY varchar(20) NOT NULL,
	CREATED_DATE Datetime NOT NULL,
	UPDATED_BY varchar(20) NOT NULL,
	UPDATED_DATE Datetime NOT NULL,
	ISACTIVE bit NOT NULL
)

END
GO


IF NOT EXISTS(Select 1 from sys.tables where name ='KPI_MASTER2BASE_MEASURE_CONFIG' AND type='U')
BEGIN

CREATE TABLE KPI_MASTER2BASE_MEASURE_CONFIG
(
	ID int IDENTITY(1,1) NOT NULL,
	BASE_MEASURE_ID int NOT NULL,
	KPI_MASTER_ID int NOT NULL,
	DISPLAY_ORDER int NULL,
	CREATED_BY varchar(20) NOT NULL,
	CREATED_DATE Datetime NOT NULL,
	UPDATED_BY varchar(20) NOT NULL,
	UPDATED_DATE Datetime NOT NULL,
	ISACTIVE bit NOT NULL
)

END
GO

IF NOT EXISTS(Select 1 from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME ='KPI2PRODUCT_SERVICE_LEVEL_METRICS' AND COLUMN_NAME='MASTER_ID')
BEGIN
ALTER TABLE KPI2PRODUCT_SERVICE_LEVEL_METRICS ADD MASTER_ID INT NULL
END
GO

IF NOT EXISTS(Select 1 from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME ='SERVICE_LEVEL_MEASUREMENT_2_BASE_MEASURE_CONFIG' AND COLUMN_NAME='MASTER_ID')
BEGIN
ALTER TABLE SERVICE_LEVEL_MEASUREMENT_2_BASE_MEASURE_CONFIG ADD MASTER_ID INT NULL
END
GO

IF NOT EXISTS(Select 1 from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME ='KPI' AND COLUMN_NAME='KPI_MASTER_ID')
BEGIN
ALTER TABLE KPI ADD KPI_MASTER_ID INT NULL
END
GO

IF NOT EXISTS(Select 1 from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME ='KPI_TARGETS' AND COLUMN_NAME='KPI_TARGET_MASTER_ID')
BEGIN
ALTER TABLE KPI_TARGETS ADD KPI_TARGET_MASTER_ID INT NULL
END
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getAllMasterKPIs' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[getAllMasterKPIs]
END
GO

CREATE Procedure getAllMasterKPIs  
  
AS  
  
BEGIN                        
                
select KT.ID as KPI_MASTER_ID,KT.ID as KPI_TARGET_MASTER_ID, K.MODE_ID,PSA.SERVICE_AREA_TYPE as SERVICE_AREA,   
K.KPI_NAME, KT.EXPECTED_SERVICE_LEVEL,KT.MINIMUM_SERVICE_LEVEL,K.SLA_TARGET_UNIT_OF_MEASUREMENT,                      
K.FREQUENCY,KT.SPECIFICATION_LIMIT AS SPECIFICATION_LIMIT,  
SLT.SERVICE_LEVEL,SLA.SLA_CATEGORY, KB.BASE_MEASURE_ID, RM.REFERENCE,  
KM.PRODUCT_SERVICE_LEVEL_METRICS_ID, K.GLOBAL_KPI_CATEGORY_ID , KT.START_DATE,KT.END_DATE                 
from   
KPI_MASTER K                        
inner join KPI_TARGET_MASTER KT on K.ID = KT.KPI_MASTER_ID    
inner join KPI_MASTER2PRODUCT_SERVICE_LEVEL_METRICS KM on KM.KPI_MASTER_ID = K.ID   
inner join KPI_MASTER2BASE_MEASURE_CONFIG KB on KB.KPI_MASTER_ID = K.ID   
inner join PRODUCT_SERVICE_LEVEL_METRICS PSL on PSL.ID = KM.PRODUCT_SERVICE_LEVEL_METRICS_ID        
inner join PRODUCTS_SERVICE_AREA PSA on PSL.SERVICE_AREA_TYPE_ID = PSA.ID                         
inner join PRODUCTS_SERVICE_LEVEL_TYPE SLT on PSL.SERVICE_LEVEL_TYPE_ID = SLT.ID                        
inner join PRODUCTS_SLA_CATEGORY SLA on PSL.SLA_CATEGORY_ID = SLA.ID                        
inner join REFERENCE_MASTER RM on PSL.REFERENCE_ID = RM.ID                  
  
where K.ISACTIVE=1 and KM.ISACTIVE=1 and KT.ISACTIVE = 1 and RM.ISACTIVE = 1     
                        
END       
GO

IF NOT EXISTS (SELECT 1 from FILTER_PREFERENCE WHERE TABLE_NAME='KPI_MASTER')
BEGIN

INSERT into FILTER_PREFERENCE values
('KPI_MASTER','kpI_NAME','KPI Name','string',1,0,0,NULL,'104859',GETDATE(),'104859',GETDATE(),1),
('KPI_MASTER','servicE_AREA','Service Area','number',1,0,0,NULL,'104859',GETDATE(),'104859',GETDATE(),1),
('KPI_MASTER','servicE_LEVEL','Service Level','number',1,0,0,NULL,'104859',GETDATE(),'104859',GETDATE(),1),
('KPI_MASTER','frequency','Frequency','number',1,0,0,NULL,'104859',GETDATE(),'104859',GETDATE(),1),
('KPI_MASTER','slA_CATEGORY','SLA Category	','number',1,0,0,NULL,'104859',GETDATE(),'104859',GETDATE(),1)

END
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getProductWiseCAPACount' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].getProductWiseCAPACount
END
GO

CREATE PROCEDURE getProductWiseCAPACount

@customerId  varchar(50),          
@startDate datetime,          
@endDate datetime,          
@productId int = 0  ,          
@iscustomer bit = 0          
    
AS       
BEGIN          

declare @quarterStartDate Datetime          
declare @quarterEndDate datetime          
set @quarterStartDate = (Select dbo.Fn_GetQuarterDates(@startDate,0));          
set @quarterEndDate = (Select dbo.Fn_GetQuarterDates(@startDate,1));          
;with CTE AS          
(      
select PP.ID as Product_ID,PM.MODE_ID,PP.PRODUCT_TITLE,KD.ID as KPI_DETAILS_ID,        
[RESUBMITTED] = (select Count(DISTINCT CAPA.KPI_DETAILS_ID) from AUDIT_FINDING_STAGES_MAPPING AFSM where AFSM.KPI_DETAILS_ID = KD.ID and AFSM.ISCOMPLETE=0 and AFSM.STAGE_STATUS='Corrective Action Plan Resubmit' and AFSM.ISACTIVE=1),      
[SUBMITTED] = (select Count(DISTINCT CAPA.KPI_DETAILS_ID) from AUDIT_FINDINGS_CAPA CAPA where CAPA.KPI_DETAILS_ID = KD.ID and CAPA.ISACTIVE=1 and CAPA.ISSUBMITTED=1 ),          
[REVIEW] =  (select COUNT(DISTINCT R.KPI_DETAILS_ID) from AUDIT_FINDING_CAPA_REVIEW R  where R.KPI_DETAILS_ID = KD.ID and R.ISACTIVE = 1 and R.ISAPPROVED=1),          
[IMPLEMENTATION] = (select COUNT(DISTINCT IMP.KPI_DETAILS_ID) from AUDIT_FINDING_CAPA_IMPLEMENTATION  IMP where IMP.KPI_DETAILS_ID = KD.ID and IMP.ISACTIVE = 1 and IMP.ISIMPLEMENTED=1),          
[VERIFICATION] = (select COUNT(DISTINCT VER.KPI_DETAILS_ID)  from AUDIT_FINDING_CAPA_VERIFICATION VER Where VER.KPI_DETAILS_ID = KD.ID and VER.ISACTIVE = 1 and VER.ISVERIFIED=1),          
[CUSTOMER_APPROVAL] = (select COUNT(DISTINCT CUST_APPROVAL.CAPA_ID) from CUSTOMER_CAPA_APPROVAL CUST_APPROVAL where  CUST_APPROVAL.CAPA_ID = MAX(CAPA.ID) and CUST_APPROVAL.ISACTIVE = 1 and CUST_APPROVAL.STATUS_ID=1) ,      
(select max(stage_ID) from AUDIT_FINDING_STAGES_MAPPING AFSM where KPI_DETAILS_ID = KD.ID and ISCOMPLETE = 1 and isactive = 1) as CAPA_STAGE,       
(select max(stage_ID) from AUDIT_FINDING_STAGES_MAPPING AFSM where AFSM.KPI_DETAILS_ID = KD.ID and AFSM.ISCOMPLETE=0 and AFSM.STAGE_STATUS='Corrective Action Plan Resubmit' and AFSM.ISACTIVE=1) as RESUBMISSION         
      
from          
PORTFOLIO_PRODUCTS PP          
left join KPI_DETAILS KD  on  KD.PRODUCT_ID = PP.ID   and PP.ISACTIVE = 1  and ( @iscustomer =0 or ISNULL(PP.IS_SERVICE_COMMENCED ,0) = 1   )          
join KPI K on KD.KPI_ID = K.ID and  K.ISACTIVE = 1          
join AUDIT_FINDINGS_CAPA CAPA on CAPA.KPI_DETAILS_ID = KD.ID AND CAPA.ISACTIVE = 1          
join PRODUCT_MODE_MAPPING PM on PM.PRODUCT_ID = PP.ID and PM.ISACTIVE = 1      
where KD.SLA_STATUS = 'Not Met'  and isnull(kd.isdraft,0) = 0  and PP.CUST_ID = @customerId and (KD.EXCLUSION_SLA_STATUS!='Met' or KD.EXCLUSION_SLA_STATUS IS NULL)    
and (K.PRODUCT_ID = @productId or @productId =0 or @productId = -1) and          
((K.FREQUENCY in ('Monthly','Release') and  KD.PERIOD  between @startDate  and @endDate)          
or K.FREQUENCY='Quarterly' and  KD.PERIOD  between   @quarterStartDate   and  @quarterEndDate )          
group by PP.ID ,PP.PRODUCT_TITLE,KD.ID,PM.MODE_ID,KD.EXCLUSION_SLA_STATUS    
)          
select Product_ID,MODE_ID,PRODUCT_TITLE,Count(KPI_DETAILS_ID) as NOT_MET,       
[DUE_FOR_SUBMISSION] = SUM(case when RESUBMISSION = 1 then RESUBMITTED else 0 End),      
[DUE_FOR_REVIEW] = SUM(case when CAPA_STAGE = 1 then SUBMITTED else 0 End),          
[DUE_FOR_CUSTOMER_APPROVAL] = SUM(case when CAPA_STAGE = 2 then REVIEW else 0 End),        
[DUE_FOR_IMPLEMENTATION] = SUM(case when CAPA_STAGE = 5 and IMPLEMENTATION = 0 and VERIFICATION = 0 then CUSTOMER_APPROVAL else 0 End),      
[DUE_FOR_VERIFICATION] = SUM(case when CAPA_STAGE = 5 and IMPLEMENTATION = 1 and VERIFICATION = 0 then IMPLEMENTATION else 0 End),          
[CLOSED] = SUM(case when CAPA_STAGE = 5 and IMPLEMENTATION = 1 and VERIFICATION = 1 then VERIFICATION else 0 End)   
from CTE          
group by Product_ID,MODE_ID,PRODUCT_TITLE          
order by PRODUCT_TITLE       
END
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getProductsbyPorfolio' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[getProductsbyPorfolio]
END
GO

CREATE procedure getProductsbyPorfolio 
 
@portfolio integer ,
@custid varchar(25) 
  
as       
begin       
 
select pp.ID, PORTFOLIO_ID,p.TITLE as Portfolio,pp.CUST_ID,c.CUST_NM,PRODUCT_TITLE,pp.SERVICE_AREA_TYPE_ID,psa.SERVICE_AREA_TYPE,pp.TIER_ID,
pt.MTTR ,pmm.MODE_ID , pslm.MODE_TITLE,pslm.MODE_TYPE, IS_SERVICE_COMMENCED,
SERVICE_COMMENCEMENT_DATE = case when IS_SERVICE_COMMENCED= 0 then NULL else PP.SERVICE_COMMENCEMENT_DATE end,
pp.CREATED_BY,pp.UPDATED_BY,pp.CREATED_DATE,pp.UPDATED_DATE,pp.ISACTIVE 
from PORTFOLIO_PRODUCTS pp     (NOLOCK)   
inner join PORTFOLIO p  (NOLOCK) on p.ID=pp.PORTFOLIO_ID       
left  join CUSTOMER c   (NOLOCK) on c.CUST_ID=pp.CUST_ID       
left join PRODUCT_MODE_MAPPING pmm on pmm.PRODUCT_ID = pp.ID 
left join PRODUCT_TIER pt on pt.TIER_ID=pp.TIER_ID 
left join PRODUCTS_SERVICE_LEVEL_MODE pslm on pslm.ID=pmm.MODE_ID 
inner join PRODUCTS_SERVICE_AREA psa on psa.ID=pp.SERVICE_AREA_TYPE_ID 
where (@portfolio IS NULL OR PORTFOLIO_ID=@portfolio)  and pp.CUST_ID = @custid and pp.ISACTIVE=1 and p.ISACTIVE=1 order by PRODUCT_TITLE     

END
Go
