USE BAS
GO

IF NOT EXISTS (
    SELECT *
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'Configuration_ext'
    AND COLUMN_NAME = 'DESCRIPTION'
)
BEGIN
ALTER TABLE CONFIGURATION_EXT
ADD [DESCRIPTION] VARCHAR(255) default null

END

IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getConfigExtDetails' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].getConfigExtDetails
END
GO

CREATE proc getConfigExtDetails  
as    
 begin    
 select ID,[KEY], [VALUE] , [DESCRIPTION], case when c.CUST_NM is null then 'All' else c.CUST_NM end   as CUSTOMER_NAME , ce.CUST_ID, ce.PROJ_ID, p.PROJ_NM as PROJECT_NAME ,COMMENTS ,     
ISENCRYPT,ISACTIVE,ce.START_DATE, ce.END_DATE from CONFIGURATION_EXT ce   left join CUSTOMER c on c.CUST_ID = ce.CUST_ID    
left join PROJECT p on p.PROJ_ID = ce.PROJ_ID  
where ce.ISACTIVE=1  order by [key]  
end 
 
go


Declare @RESOURCEID int = 89
Declare @EMPID varchar(10) = '104864'
Declare @RescourceName varchar(250) = 'Settings > Configuration_EXT'

if not exists(select 1 from APP_CONTROLS where RESOURCE_NAME = @RescourceName)
begin insert into APP_CONTROLS (RESOURCE_ID,RESOURCE_TYPE,RESOURCE_NAME,COMMENTS,CREATED_BY,UPDATED_BY,ISACTIVE,CREATED_DATE,UPDATED_DATE)
values (@RESOURCEID,'Control',@RescourceName,null,@EMPID,@EMPID,1,GETDATE(),GETDATE()) set @RESOURCEID = (select RESOURCE_ID from APP_CONTROLS where RESOURCE_NAME = @RescourceName )
end

if not exists(select 1 from APP_ACCESS_CONTROLS where RESOURCE_ID = @RESOURCEID)
begin insert into APP_ACCESS_CONTROLS
(RESOURCE_ID,ROLE_ID,EMP_ID,CUST_ID,PROJ_ID,COMMENTS,CREATED_BY,UPDATED_BY,VIEW_ACCESS,CREATE_ACCESS,
EDIT_ACCESS,DELETE_ACCESS,DEFAULT_ACCESS,ISACTIVE,CREATED_DATE,UPDATED_DATE,ACCESS_LEVEL)
values (@RESOURCEID,1,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,2,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,3,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,4,'','','',null,@EMPID,@EMPID,1,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,5,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,6,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,7,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,8,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,9,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,10,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,11,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,12,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,13,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1)
end

if not exists (select 1 from APP_CONTROL_FEATURES where RESOURCE_ID = @RESOURCEID)
begin insert into APP_CONTROL_FEATURES (RESOURCE_ID,FEATURE,COMMENTS,CREATED_BY,UPDATED_BY,ISACTIVE,CREATED_DATE,UPDATED_DATE)
values  
(@RESOURCEID,'VIEW',null,@EMPID,@EMPID,1,GETDATE(),GETDATE()) 
end
GO



Declare @RESOURCEID int = 91
Declare @EMPID varchar(10) = '104864'
Declare @RescourceName varchar(250) = 'Settings > Edit Configuration_EXT'

if not exists(select 1 from APP_CONTROLS where RESOURCE_NAME = @RescourceName)
begin insert into APP_CONTROLS (RESOURCE_ID,RESOURCE_TYPE,RESOURCE_NAME,COMMENTS,CREATED_BY,UPDATED_BY,ISACTIVE,CREATED_DATE,UPDATED_DATE)
values (@RESOURCEID,'Control',@RescourceName,null,@EMPID,@EMPID,1,GETDATE(),GETDATE()) set @RESOURCEID = (select RESOURCE_ID from APP_CONTROLS where RESOURCE_NAME = @RescourceName )
end


if not exists(select 1 from APP_ACCESS_CONTROLS where RESOURCE_ID = @RESOURCEID)
begin insert into APP_ACCESS_CONTROLS
(RESOURCE_ID,ROLE_ID,EMP_ID,CUST_ID,PROJ_ID,COMMENTS,CREATED_BY,UPDATED_BY,VIEW_ACCESS,CREATE_ACCESS,
EDIT_ACCESS,DELETE_ACCESS,DEFAULT_ACCESS,ISACTIVE,CREATED_DATE,UPDATED_DATE,ACCESS_LEVEL)
values (@RESOURCEID,1,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,2,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,3,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,4,'','','',null,@EMPID,@EMPID,0,0,1,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,5,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,6,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,7,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,8,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,9,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,10,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,11,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,12,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,13,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1)
end

if not exists (select 1 from APP_CONTROL_FEATURES where RESOURCE_ID = @RESOURCEID)
begin insert into APP_CONTROL_FEATURES (RESOURCE_ID,FEATURE,COMMENTS,CREATED_BY,UPDATED_BY,ISACTIVE,CREATED_DATE,UPDATED_DATE)
values  
(@RESOURCEID,'EDIT',null,@EMPID,@EMPID,1,GETDATE(),GETDATE()) 
end
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getAuditQualityStandards' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].getAuditQualityStandards
END
GO

CREATE Procedure getAuditQualityStandards

As  
Begin

Select E.EMP_ID,E.FRST_NM,
PROCESS_MODEL_ID = STUFF((SELECT ',' + convert(varchar(10),AQ.QUALIFIED_STANDARDS) FROM AUDITOR_QUALIFIED_STANDARDS AQ   
inner join PROCESS_MODEL PM on PM.ID = AQ.QUALIFIED_STANDARDS   
where AQ.EMP_ID = E.EMP_ID and AQ.ISACTIVE=1 order by PM.TITLE FOR XML PATH('')), 1, 1, ''),
PROCESS_MODEL = STUFF((SELECT ', ' + PM.TITLE FROM AUDITOR_QUALIFIED_STANDARDS AQ   
inner join PROCESS_MODEL PM on PM.ID = AQ.QUALIFIED_STANDARDS   
where AQ.EMP_ID = E.EMP_ID and AQ.ISACTIVE=1 order by 1 FOR XML PATH('')), 1, 1, ''),
EFFECTIVE_FROM = (Select top 1 EFFECTIVE_FROM from AUDITOR_QUALIFIED_STANDARDS AQ inner join PROCESS_MODEL PM on PM.ID = AQ.QUALIFIED_STANDARDS where AQ.EMP_ID = E.EMP_ID and AQ.ISACTIVE=1)
from  EMP_INFO E where E.CSM_TITLE_ID=7 and DOR IS NULL and EMP_ID not like '900%' order by E.FRST_NM,PROCESS_MODEL

end
Go

IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getAuditorDetailsByCertifiedStandards' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].getAuditorDetailsByCertifiedStandards
END
GO

CREATE procedure [dbo].[getAuditorDetailsByCertifiedStandards] 

@custid varchar(50),    
@projid varchar(500)    
as    
begin    
    
with cte as    
(    
select distinct process_model_id from pm_project_service_area_process_mapping    
where cust_id = @custid and proj_id = @projid and isactive = 1    
)    
    
select distinct EI.* from AUDITOR_QUALIFIED_STANDARDS PMAD    
inner join EMP_INFO EI on PMAD.EMP_ID = EI.EMP_ID and PMAD.QUALIFICATION_STATUS = 'Active' and PMAD.EFFECTIVE_FROM <= GETDATE() and PMAD.INACTIVE_FROM is null    
where PMAD.QUALIFIED_STANDARDS in (select process_model_id from cte) and EI.DOR IS NULL and PMAD.ISACTIVE=1  
order by frst_nm  
end
GO

Declare @RESOURCEID int = 90
Declare @EMPID varchar(10) = '104859'
Declare @RescourceName varchar(250) = 'Settings > Auditor Qualified Standards'

If not exists(select 1 from APP_CONTROLS where RESOURCE_NAME = @RescourceName)
begin insert into APP_CONTROLS (RESOURCE_ID,RESOURCE_TYPE,RESOURCE_NAME,COMMENTS,CREATED_BY,UPDATED_BY,ISACTIVE,CREATED_DATE,UPDATED_DATE)
values (@RESOURCEID,'Control',@RescourceName,null,@EMPID,@EMPID,1,GETDATE(),GETDATE()) 
set @RESOURCEID = (select RESOURCE_ID from APP_CONTROLS where RESOURCE_NAME = @RescourceName )
end

If not exists(select 1 from APP_ACCESS_CONTROLS where RESOURCE_ID = @RESOURCEID)
begin insert into APP_ACCESS_CONTROLS
(RESOURCE_ID,ROLE_ID,EMP_ID,CUST_ID,PROJ_ID,COMMENTS,CREATED_BY,UPDATED_BY,VIEW_ACCESS,CREATE_ACCESS,
EDIT_ACCESS,DELETE_ACCESS,DEFAULT_ACCESS,ISACTIVE,CREATED_DATE,UPDATED_DATE,ACCESS_LEVEL)
values (@RESOURCEID,1,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,2,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,3,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,4,'','','',null,@EMPID,@EMPID,1,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,5,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,6,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,7,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,8,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,9,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,10,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,11,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,12,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,13,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1)
end

If not exists (select 1 from APP_CONTROL_FEATURES where RESOURCE_ID = @RESOURCEID)
begin insert into APP_CONTROL_FEATURES (RESOURCE_ID,FEATURE,COMMENTS,CREATED_BY,UPDATED_BY,ISACTIVE,CREATED_DATE,UPDATED_DATE)
values  
(@RESOURCEID,'VIEW',null,@EMPID,@EMPID,1,GETDATE(),GETDATE()) 
end
GO

USE BAS
GO


Declare @RESOURCEID int = 93
Declare @EMPID varchar(10) = '104864'
Declare @RescourceName varchar(250) = 'Customer Success Survey > Add Batch'

if not exists(select 1 from APP_CONTROLS where RESOURCE_NAME = @RescourceName)
begin insert into APP_CONTROLS (RESOURCE_ID,RESOURCE_TYPE,RESOURCE_NAME,COMMENTS,CREATED_BY,UPDATED_BY,ISACTIVE,CREATED_DATE,UPDATED_DATE)
values (@RESOURCEID,'Control',@RescourceName,null,@EMPID,@EMPID,1,GETDATE(),GETDATE()) set @RESOURCEID = (select RESOURCE_ID from APP_CONTROLS where RESOURCE_NAME = @RescourceName )
end


if not exists(select 1 from APP_ACCESS_CONTROLS where RESOURCE_ID = @RESOURCEID)
begin insert into APP_ACCESS_CONTROLS
(RESOURCE_ID,ROLE_ID,EMP_ID,CUST_ID,PROJ_ID,COMMENTS,CREATED_BY,UPDATED_BY,VIEW_ACCESS,CREATE_ACCESS,
EDIT_ACCESS,DELETE_ACCESS,DEFAULT_ACCESS,ISACTIVE,CREATED_DATE,UPDATED_DATE,ACCESS_LEVEL)
values (@RESOURCEID,1,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,2,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,3,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,4,'','','',null,@EMPID,@EMPID,1,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,5,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,6,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,7,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,8,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,9,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,10,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,11,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,12,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,13,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1)
end

if not exists (select 1 from APP_CONTROL_FEATURES where RESOURCE_ID = @RESOURCEID)
begin insert into APP_CONTROL_FEATURES (RESOURCE_ID,FEATURE,COMMENTS,CREATED_BY,UPDATED_BY,ISACTIVE,CREATED_DATE,UPDATED_DATE)
values  
(@RESOURCEID,'VIEW',null,@EMPID,@EMPID,1,GETDATE(),GETDATE()) 
end
GO

USE BAS
GO


Declare @RESOURCEID int = 92
Declare @EMPID varchar(10) = '104864'
Declare @RescourceName varchar(250) = 'CSAT Monthly > Add Batch'

if not exists(select 1 from APP_CONTROLS where RESOURCE_NAME = @RescourceName)
begin insert into APP_CONTROLS (RESOURCE_ID,RESOURCE_TYPE,RESOURCE_NAME,COMMENTS,CREATED_BY,UPDATED_BY,ISACTIVE,CREATED_DATE,UPDATED_DATE)
values (@RESOURCEID,'Control',@RescourceName,null,@EMPID,@EMPID,1,GETDATE(),GETDATE()) set @RESOURCEID = (select RESOURCE_ID from APP_CONTROLS where RESOURCE_NAME = @RescourceName )
end


if not exists(select 1 from APP_ACCESS_CONTROLS where RESOURCE_ID = @RESOURCEID)
begin insert into APP_ACCESS_CONTROLS
(RESOURCE_ID,ROLE_ID,EMP_ID,CUST_ID,PROJ_ID,COMMENTS,CREATED_BY,UPDATED_BY,VIEW_ACCESS,CREATE_ACCESS,
EDIT_ACCESS,DELETE_ACCESS,DEFAULT_ACCESS,ISACTIVE,CREATED_DATE,UPDATED_DATE,ACCESS_LEVEL)
values (@RESOURCEID,1,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,2,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,3,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,4,'','','',null,@EMPID,@EMPID,1,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,5,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,6,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,7,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,8,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,9,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,10,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,11,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,12,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1),
(@RESOURCEID,13,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,GETDATE(),GETDATE(),1)
end

if not exists (select 1 from APP_CONTROL_FEATURES where RESOURCE_ID = @RESOURCEID)
begin insert into APP_CONTROL_FEATURES (RESOURCE_ID,FEATURE,COMMENTS,CREATED_BY,UPDATED_BY,ISACTIVE,CREATED_DATE,UPDATED_DATE)
values  
(@RESOURCEID,'VIEW',null,@EMPID,@EMPID,1,GETDATE(),GETDATE()) 
end
GO



IF EXISTS(SELECT 1 FROM sys.objects WHERE name ='vwSurveyQRatings' )
BEGIN
DROP View vwSurveyQRatings          
END
GO

CREATE View vwSurveyQRatings 
AS
SELECT  ID,survey_ID,
   [1] As Q1, [2] AS Q2, [3] AS Q3, [4]  AS Q4,[5] AS Q5,[6] AS Q6,[7] AS Q7,[8] AS Q8,[9] AS Q9,[10] AS Q10,
   [11] AS Q11,[12] AS Q12,[13] AS Q13,[14] AS Q14,[15] AS Q15
FROM  
(
  SELECT S.ID,s.survey_ID,QUESTION_ID, Rating   
  FROM CSS_QUESTION_REPLIES q (NOLOCK)
  INNER JOIN CSS_SURVEY_ITERATION s (NOLOCK)
  ON q.survey_ID=s.survey_ID
) AS SourceTable  
PIVOT  
(  
  AVG(Rating)  
  FOR QUESTION_ID IN ([1], [2], [3], [4]  ,[5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15])  
) AS PivotTable;  
 
GO


IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getCSSTableForProjects' AND TYPE='P')
BEGIN
DROP PROCEDURE getCSSTableForProjects          
END
GO

 -- [dbo].[getCSSTableForProjects]  '01/01/2023' , '03/31/2023', null
CREATE PROCEDURE [dbo].[getCSSTableForProjects]  
@startDate Date,
@endDate Date,
@projIds varchar(max) =NULL
AS  
BEGIN   
 
 SELECT 
 ID,SURVEY_ID,PROJECT_ID,PROJECT_NAME,CUSTOMER_ID,CUSTOMER_Name,CSM_EMP_ID,DELIVERY_HEAD_EMP_ID,RESPONDENT_NAME,CSAT_RECIEVED_DATE,YEAR_QUARTER,REGION,RESPONSIVENESS,NPS_SCORE,COMMENTS 
 ,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15 
 , CASE WHEN Q1 IS NULL THEN (CASE WHEN Q8 IS NULL THEN  (Q5+Q6+Q7)/3   ELSE ((Q8+Q9+Q10+Q11+Q12)/5) END ) ELSE (Q1+Q2+Q3)/3 END AS  [MIN_SCORE]    --, IIF(OVERALL_QUALITY_OF_DELIVERABLE<ENABLING_SUCCESS,IIF (OVERALL_QUALITY_OF_DELIVERABLE < VALUE_ADDS,OVERALL_QUALITY_OF_DELIVERABLE, VALUE_ADDS),IIF (ENABLING_SUCCESS < VALUE_ADDS,ENABLING_SUCCESS, VALUE_ADDS)) [MIN_SCORE]  
 FROM   
 (  
 SELECT   
  0 ID,vw.SURVEY_ID, CB.PROJ_ID [PROJECT_ID],p.PROJ_NM [PROJECT_NAME], CB.CUST_ID [CUSTOMER_ID],C.CUST_NM [CUSTOMER_Name], P.PROJ_DM_EMP_ID [CSM_EMP_ID], P.PROJ_BUHEAD_EMP_ID [DELIVERY_HEAD_EMP_ID]  
  , CB.DISPLAY_NAME RESPONDENT_NAME, SURVEY_RECEIVED_DATE [CSAT_RECIEVED_DATE], 'Q' + CAST(B.SEQUENCE AS VARCHAR) + ' ' + CAST(B.YEAR AS VARCHAR) + '-' + CAST(B.YEAR - 1999 AS VARCHAR) YEAR_QUARTER  
  , CASE WHEN P.PROJ_ID LIKE '201%' THEN 'India' WHEN P.PROJ_ID LIKE '202%' THEN 'US' WHEN P.PROJ_ID LIKE '206%' THEN 'Oman' WHEN P.PROJ_ID LIKE '207%' THEN 'Dubai' WHEN P.PROJ_ID LIKE '209%' THEN 'Saudi Arabia' ELSE '' END AS REGION  
  , NULL [RESPONSIVENESS] 
  , Q4 AS [NPS_SCORE]   
  ,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15  
   ,CASE WHEN Q1 IS NULL THEN (SELECT TOP 1 RATING_DESCRIPTION FROM CSS_QUESTION_REPLIES R (NOLOCK) WHERE CB.ID = R.BATCH_CUSTOMER_ID AND QUESTION_ID = 15) ELSE (SELECT TOP 1 RATING_DESCRIPTION FROM CSS_QUESTION_REPLIES R (NOLOCK) WHERE CB.ID = R.BATCH_CUSTOMER_ID AND QUESTION_ID = 5)  END  AS [COMMENTS]  
  FROM [CSS_BATCH_CUSTOMERS] CB (NOLOCK)  
  INNER JOIN PROJECT P (NOLOCK) on p.proj_id = CB.proj_id  
  INNER JOIN CUSTOMER C (NOLOCK) on c.cust_id = CB.cust_id  
  INNER JOIN CSS_BATCHES B (NOLOCK) ON B.ID = CB.BATCH_ID  
  INNER JOIN vwSurveyQRatings vw ON vw.ID = CB.SURVEY_ID
  WHERE CB.STATUS = 'COMPLETED' AND 
  (B.START_DATE between @startDate AND @endDate
  OR B.END_DATE  between @startDate AND @endDate)
  AND ( ISNULL(@projIds ,'')='' OR CB.proj_id in (SELECT * FROM [DBO].[FN_SPLITSTRING](@projIds,',')))  

  UNION ALL

  SELECT   
  0 ID, vw.SURVEY_ID,p.proj_id [PROJECT_ID],'Premier Healthcare Solutions' [PROJECT_NAME], CB.CUST_ID [CUSTOMER_ID],C.CUST_NM [CUSTOMER_Name],'' [CSM_EMP_ID], '' [DELIVERY_HEAD_EMP_ID]  
  , CB.DISPLAY_NAME RESPONDENT_NAME, SURVEY_RECEIVED_DATE [CSAT_RECIEVED_DATE], 'M' + CAST(B.MONTH AS VARCHAR) + ' ' + CAST(B.YEAR AS VARCHAR) + '-' + CAST(B.YEAR - 1999 AS VARCHAR) YEAR_QUARTER  
  , '' AS REGION  
  ,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15  
  , NULL [RESPONSIVENESS]  
  , (SELECT TOP 1 AVG(RATING) FROM CSS_QUESTION_REPLIES R (NOLOCK) WHERE CB.ID = R.Batch_Customer_Monthly_id AND QUESTION_MODEL_ID = 4) AS [NPS_SCORE]   
  ,CASE WHEN Q1 IS NULL THEN (SELECT TOP 1 RATING_DESCRIPTION FROM CSS_QUESTION_REPLIES R (NOLOCK) WHERE CB.ID = R.Batch_Customer_Monthly_id AND QUESTION_ID = 15) ELSE (SELECT TOP 1 RATING_DESCRIPTION FROM CSS_QUESTION_REPLIES R (NOLOCK) WHERE CB.ID = R.Batch_Customer_Monthly_id AND QUESTION_ID = 5)  END  AS [COMMENTS]  
 -- , '' [COMMENTS]  
  FROM [CSS_BATCH_CUSTOMER_MONTHLY] CB (NOLOCK)  
  INNER JOIN PROJECT P (NOLOCK) on p.proj_id   in ((SELECT top 1 PROJ_ID FROM PROJECT
  WHERE CUST_ID='212100001' and ( ISNULL(@projIds ,'')='' OR proj_id in (SELECT * FROM [DBO].[FN_SPLITSTRING](@projIds,',')))))
  INNER JOIN CUSTOMER C (NOLOCK) on c.cust_id = CB.cust_id  
  INNER JOIN CSS_BATCH_monthly B (NOLOCK) ON B.ID = CB.BATCH_MONTHLY_ID  
  INNER JOIN vwSurveyQRatings vw ON vw.ID = CB.SURVEY_ID
   WHERE CB.STATUS = 'COMPLETED' AND 
  (B.START_DATE between @startDate AND @endDate
  OR B.END_DATE  between @startDate AND @endDate)
   ) TBL   

END  


GO


IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getKPIDataAcrossProjects' AND TYPE='P')
BEGIN
DROP PROCEDURE getKPIDataAcrossProjects          
END
GO  
  
CREATE PROCEDURE [dbo].[getKPIDataAcrossProjects]              
      
@Startdate Date,              
@Enddate Date,              
@GlobalKpis varchar(max),            
@Customerids varchar(max),            
@Projectids  varchar(max)            
  
AS            
BEGIN            
  SET @Enddate=DATEADD(d,1,@Enddate);
  Select DISTINCT per.ID as PERSPECTIVE_ID, per.SHORT_DESC  as KPI_CATEGORY, kpicat.ID AS GLOBAL_KPI_ID, kpicat.SHORT_DESC AS GLOBAL_KPI_NAME, k.customer_id AS CUST_ID, c.CUST_NM, k.project_id AS PROJ_ID,    
   p.PROJ_NM,e.FRST_NM as CSM_NAME, p.PROJ_DM_EMP_ID     
as CSM_EMP_ID,              
   k.goal_id, GOALS.DESCRIPTION AS GOAL_DESC, k.ID AS KPI_ID, k.KPI_NAME, details.PERIOD, details.PERIOD_TYPE, k.ABBREVIATION, k.SERVICE_AREA,     
       
     (SELECT top 1 SLA_TARGET_VERYHIGH_VALUE FROM KPI_TARGETS (NOLOCK) WHERE details.PERIOD >= START_DATE AND details.PERIOD <= END_DATE AND  KPI_ID = details.KPI_ID)     as SLA_TARGET_VERYHIGH_VALUE    
       ,(SELECT top 1 SLA_TARGET_VERYHIGH_OPERATOR FROM KPI_TARGETS (NOLOCK) WHERE details.PERIOD >= START_DATE AND details.PERIOD <= END_DATE AND   KPI_ID = details.KPI_ID)     as SLA_TARGET_VERYHIGH_OPERATOR            
       ,(SELECT top 1 SLA_TARGET_VERYHIGH_DESCRIPTION FROM KPI_TARGETS (NOLOCK) WHERE details.PERIOD >= START_DATE AND details.PERIOD <= END_DATE AND KPI_ID = details.KPI_ID)     as SLA_TARGET_VERYHIGH_DESCRIPTION            
  
    ,(SELECT top 1 SLA_TARGET_HIGH_VALUE FROM KPI_TARGETS (NOLOCK) WHERE details.PERIOD >= START_DATE AND details.PERIOD <= END_DATE AND  KPI_ID = details.KPI_ID)     as SLA_TARGET_HIGH_VALUE    
       ,(SELECT top 1 SLA_TARGET_HIGH_OPERATOR FROM KPI_TARGETS (NOLOCK) WHERE details.PERIOD >= START_DATE AND details.PERIOD <= END_DATE AND KPI_ID = details.KPI_ID)     as SLA_TARGET_HIGH_OPERATOR            
       ,(SELECT top 1 SLA_TARGET_HIGH_DESCRIPTION FROM KPI_TARGETS (NOLOCK) WHERE details.PERIOD >= START_DATE AND details.PERIOD <= END_DATE AND KPI_ID = details.KPI_ID)     as SLA_TARGET_HIGH_DESCRIPTION            
  
    ,(SELECT top 1 SLA_TARGET_MEDIUM_VALUE FROM KPI_TARGETS (NOLOCK) WHERE details.PERIOD >= START_DATE AND details.PERIOD <= END_DATE AND  KPI_ID = details.KPI_ID)     as SLA_TARGET_MEDIUM_VALUE    
       ,(SELECT top 1 SLA_TARGET_MEDIUM_OPERATOR FROM KPI_TARGETS (NOLOCK) WHERE details.PERIOD >= START_DATE AND details.PERIOD <= END_DATE AND    KPI_ID = details.KPI_ID)     as SLA_TARGET_MEDIUM_OPERATOR            
       ,(SELECT top 1 SLA_TARGET_MEDIUM_DESCRIPTION FROM KPI_TARGETS (NOLOCK) WHERE details.PERIOD >= START_DATE AND details.PERIOD <= END_DATE AND KPI_ID = details.KPI_ID)     as SLA_TARGET_MEDIUM_DESCRIPTION            
  
    ,(SELECT top 1 SLA_TARGET_LOW_VALUE FROM KPI_TARGETS (NOLOCK) WHERE details.PERIOD >= START_DATE AND details.PERIOD <= END_DATE AND  KPI_ID = details.KPI_ID)     as SLA_TARGET_LOW_VALUE    
       ,(SELECT top 1 SLA_TARGET_LOW_OPERATOR FROM KPI_TARGETS (NOLOCK) WHERE details.PERIOD >= START_DATE AND details.PERIOD <= END_DATE AND  KPI_ID = details.KPI_ID)     as SLA_TARGET_LOW_OPERATOR            
       ,(SELECT top 1 SLA_TARGET_LOW_DESCRIPTION FROM KPI_TARGETS (NOLOCK) WHERE details.PERIOD >= START_DATE AND details.PERIOD <= END_DATE AND  KPI_ID = details.KPI_ID)     as SLA_TARGET_LOW_DESCRIPTION            
    
       ,CASE WHEN details.PERIOD_TYPE = 'Week1' then     
                     CONVERT(CHAR(3),CONVERT(datetime,     
                                     SWITCHOFFSET(CONVERT(datetimeoffset,     
                                                                           details.PERIOD),     
                                                              DATENAME(TzOffset, SYSDATETIMEOFFSET()))) , 0)     
                                                    
       ELSE CONVERT(CHAR(3), details.[PERIOD], 0)  END AS MONTH_NM       
                    
   ,YEAR(details.[PERIOD]) AS YEAR  ,                       
    details.KPI_ACTUAL, k.SLA_TARGET_UNIT_OF_MEASUREMENT, k.PRIORITY, k.SUPPORT_WINDOW, k.IS_SOW_COMMITMENT, details.ISFLAG    
    from KPI_DETAILS details              
              
 inner join KPI K on k.ID = details.KPI_ID and details.ISACTIVE = 1  and (@GlobalKpis = '' or k.GLOBAL_KPI_CATEGORY_ID in (SELECT * FROM [DBO].[FN_SPLITSTRING](@GlobalKpis,',')) )          
 inner join KPI_TARGETS target on k.ID = target.KPI_ID and target.ISACTIVE = 1              
 inner join KPI_GOALS goals on k.GOAL_ID = goals.ID and goals.ISACTIVE = 1              
 inner join GLOBAL_PERSPECTIVE_KPI_CATEGORY_MAPPING kpimap on k.GLOBAL_KPI_CATEGORY_ID = kpimap.GLOBAL_KPI_CATEGORY_ID and k.ISACTIVE = 1 and kpimap.ISACTIVE = 1              
 inner join GLOBAL_PERSPECTIVE per on per.ID = kpimap.GLOBAL_PERSPECTIVE_ID and per.ISACTIVE = 1              
 inner join GLOBAL_KPI_CATEGORY kpicat on kpimap.GLOBAL_KPI_CATEGORY_ID = kpicat.ID and kpicat.ISACTIVE = 1              
 inner join CUSTOMER c on c.CUST_ID = k.CUSTOMER_ID  and  (@Customerids = '' or k.CUSTOMER_ID in (SELECT * FROM [DBO].[FN_SPLITSTRING](@Customerids,',')))            
 inner join PROJECT p on p.PROJ_ID = k.PROJECT_ID   and (@Projectids = '' or p.PROJ_ID in (SELECT * FROM [DBO].[FN_SPLITSTRING](@Projectids,','))  )           
 inner join EMP_INFO e on e.EMP_ID = p.PROJ_DM_EMP_ID              
           
 where details.PERIOD between @Startdate and @Enddate    
    
 order by k.CUSTOMER_ID, k.PROJECT_ID, k.ID, details.PERIOD        
           
 end    

 GO


 
IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getIssuesForProjects' AND TYPE='P')
BEGIN
DROP PROCEDURE getIssuesForProjects          
END
GO

CREATE procedure [dbo].[getIssuesForProjects]  
@startDate Date,
@EndDate Date,
@PROJIDS VARCHAR(MAX) 

as                
begin                 
select I.ID, PROJECT_ID, RAG, DESCRIPTION, IMPACT_SUMMARY, IS_POTENTIAL_RISK, BUSINESS_IMPACT, GEO_LOCATION, ISSUE_TYPE, SEVERITY, ACTION_PLAN,                
ASSIGNED_TO,IDENTIFIED_BY,REPORTED_BY, LEVEL, IDENTIFIED_DATE, TARGET_DATE, STATUS, ISSUE_RESOLVED_DATE, I.COMMENTS,                
I.CREATED_BY, I.CREATED_DATE, I.UPDATED_BY, I.UPDATED_DATE, I.ISACTIVE,                
P.CUST_ID, PP.PORTFOLIO_ID, PF.TITLE AS PORTFOLIO_NM, P.PROJ_NM             
FROM PROJECT_ISSUE I (NOLOCK)             
INNER JOIN PROJECT P (NOLOCK) ON I.PROJECT_ID = P.PROJ_ID and P.PROJ_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,',')) AND  I.ISACTIVE =1                    
LEFT OUTER JOIN PORTFOLIO_PROJECT PP (NOLOCK) ON PP.PROJ_ID = P.PROJ_ID                
LEFT OUTER JOIN PORTFOLIO PF (NOLOCK)  ON PF.ID = PP.PORTFOLIO_ID   
WHERE I.IDENTIFIED_DATE BETWEEN @startDate AND @EndDate
OR  I.CREATED_DATE BETWEEN @startDate AND @EndDate
OR  I.ISSUE_RESOLVED_DATE BETWEEN @startDate AND @EndDate
ORDER BY I.IDENTIFIED_DATE DESC               

end   


GO



IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getActionItemsForProjects' AND TYPE='P')
BEGIN
DROP PROCEDURE getActionItemsForProjects          
END
GO

CREATE PROCEDURE [dbo].[getActionItemsForProjects]        
@startDate Date,
@EndDate Date,
@PROJIDS VARCHAR(MAX)  
  AS            
  BEGIN            
          
  SELECT P.CUST_ID AS CUST_ID, [PROJECT_ID] AS PROJ_ID, P.PROJ_NM, PP.PORTFOLIO_ID, PF.TITLE AS PORTFOLIO_NAME, A.ID AS ACTION_ITEM_ID, A.RAG, A.DESCRIPTION, A.SOURCE, A.OWNER, A.IDENTIFIED_DATE, A.TARGET_DATE, A.STATUS,            
  A.PRIORITY, A.COMPLETION_DATE, A.COMMENTS, A.CREATED_DATE, A.CREATED_BY, A.UPDATED_BY, A.UPDATED_DATE,            
            
   CASE WHEN (A.TARGET_DATE < GETDATE() AND A.STATUS  IN ('Planned' , 'Started')) THEN 'PAST_DUE_DATE'      
		WHEN  (A.TARGET_DATE >= GETDATE() AND A.STATUS  IN ('Planned' , 'Started')) THEN 'DUE_FOR_CLOSURE'      
      
   END  AS STATUS_TYPE, A.ISACTIVE            
    FROM [PROJECT_ACTIONITEM] A  (NOLOCK) 
    INNER JOIN PROJECT P  (NOLOCK) ON a.PROJECT_ID = p.PROJ_ID AND P.PROJ_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,','))  AND A.ISACTIVE = 1       
    LEFT OUTER JOIN PORTFOLIO_PROJECT PP (NOLOCK) ON PP.PROJ_ID =  A.PROJECT_ID            
    LEFT OUTER JOIN PORTFOLIO PF  (NOLOCK) ON PF.ID = PP.PORTFOLIO_ID            
  WHERE A.IDENTIFIED_DATE BETWEEN @startDate AND @EndDate
  OR  A.CREATED_DATE BETWEEN @startDate AND @EndDate
  OR  A.COMPLETION_DATE BETWEEN @startDate AND @EndDate
    ORDER BY A.IDENTIFIED_DATE desc      
 END 
GO



IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getRisksForProjects' AND TYPE='P')
BEGIN
DROP PROCEDURE getRisksForProjects          
END
GO
  
CREATE PROCEDURE [dbo].[getRisksForProjects]        
@startDate Date,
@EndDate Date,
@PROJIDS VARCHAR(MAX)   
AS              
BEGIN              
  SELECT C.CUST_ID, CUST_NM, PORT.ID PORTFOLIO_ID, PORT.TITLE PORTFOLIO_NM, P.PROJ_NM, R.[ID]              
      ,[PROJECT_ID]              
      ,[RAG]              
      ,[DESCRIPTION]              
      ,[IMPACT]              
      ,[PROBABILITY_SCALE]              
      ,[IMPACT_SCALE]              
      ,[OWNER]              
      ,[AREA]              
      ,[IDENTIFIED_BY]              
      ,[IDENTIFIED_DATE]              
      ,[RISK_TREATMENT_STRATEGY]              
      ,[TARGET_DATE]              
      ,[ACTUAL_DATE]              
      ,[STATUS]              
      ,[ACTION_TAKEN]              
      ,R.[CREATED_BY]              
      ,R.[CREATED_DATE]              
      ,R.[UPDATED_BY]              
      ,R.[UPDATED_DATE]              
      ,R.[ISACTIVE]         
   , isnull(E.FRST_NM, [OWNER]) as OWNER_NAME         
   ,R.ACCEPT_TILL FROM PROJECT_RISK R   (NOLOCK)               
  INNER JOIN PROJECT P (NOLOCK) ON R.PROJECT_ID = p.PROJ_ID AND P.PROJ_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,','))  and R.ISACTIVE = 1              
  INNER JOIN CUSTOMER C (NOLOCK) ON C.CUST_ID = P.CUST_ID              
  LEFT JOIN EMP_INFO e (NOLOCK)  on r.OWNER  =  convert(varchar,e.EMAIL_ID) or r.owner = convert(varchar, e.emp_id)       
  LEFT OUTER JOIN PORTFOLIO_PROJECT PP (NOLOCK) ON PP.PROJ_ID = P.PROJ_ID              
  LEFT OUTER JOIN PORTFOLIO PORT (NOLOCK) ON PORT.ID = PP.PORTFOLIO_ID
  WHERE R.IDENTIFIED_DATE BETWEEN @startDate AND @EndDate
  OR  R.CREATED_DATE BETWEEN @startDate AND @EndDate
  OR  R.ACTUAL_DATE BETWEEN @startDate AND @EndDate
  order by [IDENTIFIED_DATE] desc        
              
END   
GO




IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getContractStatusForProjects' AND TYPE='P')
BEGIN
DROP PROCEDURE getContractStatusForProjects          
END
GO
  
CREATE PROCEDURE [dbo].[getContractStatusForProjects]        
@startDate Date,
@EndDate Date,
@PROJIDS VARCHAR(MAX)  
AS            
BEGIN   

SELECT 
E.EMP_ID, E.FRST_NM EMP_NAME,
P.PROJ_ID,P.PROJ_NM,
E.TITLE,P.END_DATE, M.FRST_NM MNGR_NM
FROM PROJ_RESOURCE PR (NOLOCK)
INNER JOIN PROJECT P (NOLOCK)
ON PR.PROJ_ID = p.PROJ_ID 
INNER JOIN EMP_INFO E (NOLOCK)
ON E.EMP_ID= PR.EMP_ID
INNER JOIN EMP_INFO M  (NOLOCK)
ON E.MANAGER_EMP_ID =M.EMP_ID
Where PR.BILL_FLG = 1 AND PR.END_DATE > getdate()  
and P.PROJ_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,','))                  
AND (P.END_DATE BETWEEN @startDate AND @EndDate )
ORDER BY P.END_DATE  desc      

END 
GO


IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getMonthActionItems' AND TYPE='P')
BEGIN
DROP PROCEDURE getMonthActionItems          
END
GO
  
CREATE PROCEDURE [dbo].[getMonthActionItems]                
 @ProjIds VARCHAR(MAX)   
 AS  
 BEGIN  
 DECLARE @fromDate date= Dateadd(Month, Datediff(Month, 0, DATEADD(m, -6, current_timestamp)), 0); 
 SELECT  DATENAME(MM,A.COMPLETION_DATE) AS MONTH_NAME,COUNT(A.STATUS) AS STATUS                
 FROM [PROJECT_ACTIONITEM] A  (NOLOCK)              
    INNER JOIN PROJECT P   (NOLOCK) ON a.PROJECT_ID = p.PROJ_ID AND   
 P.PROJ_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,','))  AND A.ISACTIVE = 1           
 and A.STATUS = 'Completed' and A.COMPLETION_DATE >= DATEADD(M,-6,GETDATE())  
 LEFT OUTER JOIN PORTFOLIO_PROJECT PP  (NOLOCK) ON PP.PROJ_ID =  A.PROJECT_ID                
 LEFT OUTER JOIN PORTFOLIO PF  (NOLOCK) ON PF.ID = PP.PORTFOLIO_ID       
  WHERE A.COMPLETION_DATE BETWEEN @fromDate AND GETDATE()
    group by DATENAME(MM,A.COMPLETION_DATE)  
 ORDER BY DATENAME(MM,A.COMPLETION_DATE)  
    
 END  
 GO

 
IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getMonthlyRisksData' AND TYPE='P')
BEGIN
DROP PROCEDURE getMonthlyRisksData          
END
GO
  
CREATE procedure [dbo].[getMonthlyRisksData]          
@ProjIds VARCHAR(MAX)   
AS          
BEGIN          
DECLARE @fromDate date= Dateadd(Month, Datediff(Month, 0, DATEADD(m, -6, current_timestamp)), 0);     
SELECT DATENAME(MM,r.IDENTIFIED_DATE) AS MONTH_NAME,COUNT(r.STATUS) AS STATUS                
FROM [PROJECT_RISK] r (NOLOCK) 
inner join project p  (NOLOCK) on p.proj_id =  r.PROJECT_ID       
and P.PROJ_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@ProjIds,','))  
AND r.STATUS = 'Identified'  and r.ISACTIVE =1        
LEFT OUTER JOIN portfolio_project pp  (NOLOCK) on pp.proj_id =  r.PROJECT_ID            
LEFT OUTER JOIN PORTFOLIO PF  (NOLOCK) ON PF.ID = PP.PORTFOLIO_ID    
WHERE r.IDENTIFIED_DATE BETWEEN @fromDate AND GETDATE()
group by DATENAME(MM,r.IDENTIFIED_DATE)  
ORDER BY DATENAME(MM,r.IDENTIFIED_DATE)  
    
END   

GO



IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getMonthlyIssuesData' AND TYPE='P')
BEGIN
DROP PROCEDURE getMonthlyIssuesData          
END
GO
  
CREATE procedure [dbo].[getMonthlyIssuesData]          
@ProjIds VARCHAR(MAX)   
AS          
BEGIN          
DECLARE @fromDate date= Dateadd(Month, Datediff(Month, 0, DATEADD(m, -6, current_timestamp)), 0); 
SELECT DATENAME(MM,I.ISSUE_RESOLVED_DATE) AS MONTH_NAME,COUNT(I.STATUS) AS STATUS                
FROM [PROJECT_ISSUE] I   (NOLOCK)         
inner join project p (NOLOCK) on p.proj_id =  I.PROJECT_ID       
and P.PROJ_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@ProjIds,','))  
AND I.STATUS = 'Identified'  and I.ISACTIVE =1        
LEFT OUTER JOIN portfolio_project pp  (NOLOCK) on pp.proj_id =  I.PROJECT_ID            
LEFT OUTER JOIN PORTFOLIO PF  (NOLOCK) ON PF.ID = PP.PORTFOLIO_ID   
WHERE ISSUE_RESOLVED_DATE BETWEEN @fromDate AND GETDATE()
group by DATENAME(MM,I.ISSUE_RESOLVED_DATE)  
ORDER BY DATENAME(MM,I.ISSUE_RESOLVED_DATE)  
    
END   
  
GO


Declare  @RESOURCEID int = 88
Declare @EMPID varchar(10) = '105683'
Declare @RescourceName varchar(250) = 'Settings > COO Dashboard'

if not exists(select 1 from  APP_CONTROLS where RESOURCE_NAME = @RescourceName)
begin 
insert into APP_CONTROLS (RESOURCE_ID,RESOURCE_TYPE,RESOURCE_NAME,COMMENTS,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE,ISACTIVE)
values (@RESOURCEID,'Control',@RescourceName,null,@EMPID,GETDATE(),@EMPID,GETDATE(),1)

set @RESOURCEID = (select RESOURCE_ID from  APP_CONTROLS where RESOURCE_NAME = @RescourceName )

end 

if not exists(select 1 from  APP_ACCESS_CONTROLS where RESOURCE_ID = @RESOURCEID)
begin insert into  APP_ACCESS_CONTROLS
(RESOURCE_ID,ROLE_ID,EMP_ID,CUST_ID,PROJ_ID,COMMENTS,CREATED_BY,UPDATED_BY,VIEW_ACCESS,CREATE_ACCESS,
EDIT_ACCESS,DELETE_ACCESS,DEFAULT_ACCESS,ISACTIVE,ACCESS_LEVEL,CREATED_DATE,UPDATED_DATE)
values (@RESOURCEID,1,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,2,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,3,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,4,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,5,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,6,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,7,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,8,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,9,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,10,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,11,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,12,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,13,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate())
end

if not exists (select 1 from  APP_CONTROL_FEATURES where RESOURCE_ID = @RESOURCEID)
begin insert into  APP_CONTROL_FEATURES (RESOURCE_ID,FEATURE,COMMENTS,CREATED_BY,UPDATED_BY,ISACTIVE,CREATED_DATE,UPDATED_DATE)
values  
(@RESOURCEID,'VIEW',null,@EMPID,@EMPID,1,GETDATE(),GETDATE()) 
end

GO


IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getKPIDetails' AND TYPE='P')
BEGIN
DROP PROCEDURE getKPIDetails          
END
GO
      --[getKPIDetails] '06/01/2022','06/30/2022','202P000133-03'
CREATE PROCEDURE [dbo].[getKPIDetails]            
@START_DATE datetime,            
@END_DATE datetime,
@ProjIds VARCHAR(MAX)   =NULL
AS            
BEGIN            
SELECT KD.[ID],KD.[KPI_ID],KD.[PERIOD], MONTH(KD.[PERIOD]) AS MONTH_VAL, CONVERT(CHAR(3), KD.[PERIOD], 0) AS MONTH_NM            
 ,YEAR(KD.[PERIOD]) AS YEAR            
 ,DATEFROMPARTS(YEAR(KD.[PERIOD]), MONTH(KD.[PERIOD]), 1) AS MONTH_YEAR            
 ,K.[KPI_NAME], K.[PRIORITY], K.[SUPPORT_WINDOW]            
 ,KD.[PERIOD_TYPE],KD.[KPI_ACTUAL],KD.[KPI_METRIC],KD.[HIGHLIGHTS],KD.[CREATED_BY],KD.[CREATED_DATE],KD.[UPDATED_BY],KD.[UPDATED_DATE],KD.[ISACTIVE],KD.[ISFLAG]            
 ,K.CUSTOMER_ID, C.CUST_NM CUSTOMER_NM, K.PROJECT_ID, P.PROJ_NM PROJECT_NM, K.GOAL_ID            
 ,K.GLOBAL_KPI_CATEGORY_ID            
 ,GKC.SHORT_DESC GLOBAL_KPI_CATEGORY_NM            
 ,(SELECT GLOBAL_PERSPECTIVE_ID FROM GLOBAL_PERSPECTIVE_KPI_CATEGORY_MAPPING  (NOLOCK) WHERE GLOBAL_KPI_CATEGORY_ID = K.GLOBAL_KPI_CATEGORY_ID AND GLOBAL_PERSPECTIVE_ID IN (SELECT ID FROM GLOBAL_PERSPECTIVE  (NOLOCK) WHERE GROUP_CODE = 'KPI')) as GLOBAL_KPI_PERSPECTIVE_ID   
  
    
      
        
          
            
 ,IS_SOW_COMMITMENT, K.SERVICE_AREA,            
 K.SLA_TARGET_UNIT_OF_MEASUREMENT            
,(SELECT top 1 SLA_TARGET_VERYHIGH_VALUE FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_VERYHIGH_VALUE               
,(SELECT top 1 SLA_TARGET_VERYHIGH_OPERATOR FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_VERYHIGH_OPERATOR            
,(SELECT top 1 SLA_TARGET_VERYHIGH_DESCRIPTION FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_VERYHIGH_DESCRIPTION               
,(SELECT top 1 SLA_TARGET_HIGH_VALUE FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_HIGH_VALUE              
,(SELECT top 1 SLA_TARGET_HIGH_OPERATOR FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_HIGH_OPERATOR            
,(SELECT top 1 SLA_TARGET_HIGH_DESCRIPTION FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_HIGH_DESCRIPTION            
,(SELECT top 1 SLA_TARGET_MEDIUM_VALUE FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_MEDIUM_VALUE               
,(SELECT top 1 SLA_TARGET_MEDIUM_OPERATOR FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_MEDIUM_OPERATOR            
,(SELECT top 1 SLA_TARGET_MEDIUM_DESCRIPTION FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_MEDIUM_DESCRIPTION            
,(SELECT top 1 SLA_TARGET_LOW_VALUE FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_LOW_VALUE               
,(SELECT top 1 SLA_TARGET_LOW_OPERATOR FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_LOW_OPERATOR            
,(SELECT top 1 SLA_TARGET_LOW_DESCRIPTION FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_LOW_DESCRIPTION            
            
FROM KPI_DETAILS KD  (NOLOCK)            
            
INNER JOIN KPI K (NOLOCK) ON K.ID = KD.KPI_ID AND K.ISACTIVE = 1    
INNER JOIN KPI_GOALS GOALS  (NOLOCK) ON GOALS.ID = K.GOAL_ID AND GOALS.ISACTIVE = 1     
INNER JOIN PROJECT P  (NOLOCK) ON P.PROJ_ID = K.PROJECT_ID             
INNER JOIN CUSTOMER C  (NOLOCK) ON C.CUST_ID = K.CUSTOMER_ID             
INNER JOIN GLOBAL_KPI_CATEGORY GKC (NOLOCK)  ON K.GLOBAL_KPI_CATEGORY_ID = GKC.ID            
WHERE PERIOD BETWEEN @START_DATE AND @END_DATE AND KD.ISFLAG=0  AND KD.ISACTIVE =1  and isnull(p.PROJ_STATUS,'') != 'Close' 
AND (ISNULL(@PROJIDS,'')='' OR K.PROJECT_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,',')))
ORDER BY C.CUST_NM, P.PROJ_NM    
END    

GO

