IF EXISTS(Select 1 from sys.objects where name ='GET_CI_TRACKER_DATA' AND type='P')
BEGIN
       DROP PROCEDURE [dbo].[GET_CI_TRACKER_DATA]
END

GO

CREATE PROCEDURE [dbo].[GET_CI_TRACKER_DATA]        
@AUTOMATE BIT,        
@CUSTOMER_SAVINGS BIT,        
@STARTDATE DATETIME,        
@ENDDATE DATETIME,        
@PROJIDS VARCHAR(MAX),        
@CUSTID int,        
@INNOVATION bit,        
@IMPROVEMENT bit,        
@ALL bit,        
@VIEWBY int = 0,        
@IISTATUS VARCHAR(50)        
        
AS        
BEGIN        
        
        
DECLARE @statuS_IDENTIFIED INT = 0        
DECLARE @statuS_PLANNING INT = 0        
DECLARE @statuS_EXECUTION INT = 0        
DECLARE @statuS_COMPLETED INT = 0        
        
select @statuS_IDENTIFIED = item from [DBO].[FN_SPLITSTRING](@IISTATUS,',') where item=1        
select @statuS_PLANNING = item from [DBO].[FN_SPLITSTRING](@IISTATUS,',') where item=2        
select @statuS_EXECUTION = item from [DBO].[FN_SPLITSTRING](@IISTATUS,',') where item=3        
select @statuS_COMPLETED = item from [DBO].[FN_SPLITSTRING](@IISTATUS,',') where item=4        
        
        
if(@ALL = 1)        
 SELECT C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE AS 'PORTFOLIO_NM', P.PROJ_ID, P.PROJ_NM,         
 SUM(CASE WHEN @statuS_COMPLETED = 4 AND PI.STATUS = 'Completed' AND (PI.ACTUAL_DATE >= @STARTDATE AND PI.ACTUAL_DATE <= @ENDDATE)  THEN 1 ELSE 0 END) 'COMPLETED',        
 SUM(CASE WHEN @statuS_IDENTIFIED = 1 AND PI.STATUS = 'Identified' THEN 1         
          WHEN @statuS_PLANNING = 2   AND PI.STATUS = 'Planning' THEN 1           
       WHEN @statuS_EXECUTION = 3   AND PI.STATUS = 'Execution' THEN 1         
       ELSE 0 END) 'INPROGRESS',        
        
 ABS(FLOOR(CASE WHEN SUM([BEFORE_ERROR]) > 0 THEN (SUM([BEFORE_ERROR]) -  SUM([AFTER_ERROR])) / SUM([BEFORE_ERROR])         
 ELSE 0        
 END * 100)) AS 'QUALITY_REDUCTION_OF_ERRORS',        
         
        
 ABS(FLOOR(CASE WHEN SUM([BEFORE_LEAD_TIME]) > 0  THEN (SUM(dbo.getminutes([BEFORE_LEAD_TIME],[BEFORE_LEAD_TIME_UOM]))  -  SUM(dbo.getminutes([AFTER_LEAD_TIME],[AFTER_LEAD_TIME_UOM]))) / SUM(dbo.getminutes([BEFORE_LEAD_TIME],[BEFORE_LEAD_TIME_UOM]))      
  
   
 ELSE 0        
 END * 100)) AS 'REDUCTION_IN_LEAD_TIME',          
        
 ABS(FLOOR(CASE WHEN SUM([BEFORE_CYCLE_TIME]) > 0  THEN (SUM(dbo.getminutes([BEFORE_CYCLE_TIME],[BEFORE_CYCLE_TIME_UOM]))  -  SUM(dbo.getminutes([AFTER_CYCLE_TIME],[AFTER_CYCLE_TIME_UOM]))) / SUM(dbo.getminutes([BEFORE_CYCLE_TIME],[BEFORE_CYCLE_TIME_UOM])
         
)         
 ELSE 0        
 END * 100)) AS 'REDUCTION_IN_CYCLE_TIME',         
        
 ABS(FLOOR(SUM(BEFORE_ERROR))) AS 'TOTAL_BEFORE_ERROR',        
 ABS(FLOOR(SUM(AFTER_ERROR))) AS 'TOTAL_AFTER_ERROR',        
 ABS(FLOOR(SUM(BEFORE_LEAD_TIME))) AS 'TOTAL_BEFORE_LEAD',        
 ABS(FLOOR(SUM(AFTER_LEAD_TIME))) AS 'TOTAL_AFTER_LEAD',        
        
 ABS(FLOOR(SUM(BEFORE_CYCLE_TIME))) AS 'TOTAL_BEFORE_CYCLE',        
 ABS(FLOOR(SUM(AFTER_CYCLE_TIME))) AS 'TOTAL_AFTER_CYCLE',        
 ABS(FLOOR(SUM(CASE WHEN IS_ONETIME = 1 THEN BEFORE_EFFORT    
     ELSE (BEFORE_EFFORT * BEFORE_OCCOURANCE_COUNT)    
     END))) AS [BEFORE_EFFORT],    
 ABS(FLOOR(SUM(CASE WHEN IS_ONETIME = 1 THEN AFTER_EFFORT    
     ELSE (AFTER_EFFORT * AFTER_OCCOURANCE_COUNT)    
     END))) AS [AFTER_EFFORT],     
        
 ABS(FLOOR(SUM(CUSTOMER_PERSONHOUR_SAVINGS))) AS 'SAVING_PER_YEAR_EFFORT',          
        
 ABS(FLOOR(SUM( CASE WHEN INTERNAL_SAVINGS <> 'NaN' then CAST(INTERNAL_SAVINGS AS NUMERIC(10, 2))        
 ELSE 0 END        
 )))  AS 'SAVINGS_IN_USD',         
         
 ABS(FLOOR(SUM(CUSTOMER_SAVINGS)))  AS 'HARD_BENEFITS',        
 ' ' AS 'SOFT_BENEFITS',        
 ABS(FLOOR(SUM(FINANCIAL_REVENUE))) AS 'REVENUE',        
 ABS(FLOOR(SUM(FINANCIAL_OPERATING_COST))) AS 'OPERATING_COST',        
 ABS(FLOOR(SUM(FINANCIAL_PROFITABILITY))) AS 'PROFITABILITY'        
 FROM project_innovation PI         
        
 INNER JOIN [BAS].DBO.PROJECT P ON PI.PROJECT_ID = P.PROJ_ID         
 INNER JOIN [BAS].DBO.CUSTOMER C ON C.CUST_ID = P.CUST_ID        
 LEFT JOIN  PORTFOLIO_PROJECT PP on PP.PROJ_ID = p.PROJ_ID and pp.ISACTIVE = 1        
 left join PORTFOLIO port on port.ID = pp.PORTFOLIO_ID and port.ISACTIVE = 1         
         
 WHERE         
         
 (((@statuS_IDENTIFIED = 1 and pi.STATUS = 'Identified') or (@statuS_PLANNING = 2 and pi.STATUS = 'Planning') or
	(@statuS_EXECUTION = 3 and pi.STATUS = 'Execution')
 ) OR  (@statuS_COMPLETED = 4 and pi.status = 'Completed' and (pi.actual_date >= @STARTDATE and pi.actual_date <= @ENDDATE)) )         
 AND PI.IDENTIFIED_DATE <= @ENDDATE AND PI.STATUS NOT IN ('Cancelled','Suspended')        
 AND (@CUSTID = -1 OR C.CUST_ID = @CUSTID)         
 AND (@PROJIDS = '' OR PI.PROJECT_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,','))) and PI.ISACTIVE = 1        
 GROUP BY C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE, P.PROJ_ID, P.PROJ_NM        
        
ELSE        
         
 SELECT C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE AS 'PORTFOLIO_NM', P.PROJ_ID, P.PROJ_NM,         
 SUM(CASE WHEN @statuS_COMPLETED = 4 AND PI.STATUS = 'Completed' AND (PI.ACTUAL_DATE >= @STARTDATE AND PI.ACTUAL_DATE <= @ENDDATE)  THEN 1 ELSE 0 END) 'COMPLETED',        
 SUM(CASE WHEN @statuS_IDENTIFIED = 1 AND PI.STATUS = 'Identified' THEN 1         
          WHEN @statuS_PLANNING = 2   AND PI.STATUS = 'Planning' THEN 1           
       WHEN @statuS_EXECUTION = 3   AND PI.STATUS = 'Execution' THEN 1         
       ELSE 0 END) 'INPROGRESS',        
        
 ABS(FLOOR(CASE WHEN SUM([BEFORE_ERROR]) > 0 THEN (SUM([BEFORE_ERROR]) -  SUM([AFTER_ERROR])) / SUM([BEFORE_ERROR])         
 ELSE 0        
 END * 100)) AS 'QUALITY_REDUCTION_OF_ERRORS',        
        
 ABS(FLOOR(CASE WHEN SUM([BEFORE_LEAD_TIME]) > 0  THEN (SUM(dbo.getminutes([BEFORE_LEAD_TIME],[BEFORE_LEAD_TIME_UOM]))  -  SUM(dbo.getminutes([AFTER_LEAD_TIME],[AFTER_LEAD_TIME_UOM]))) / SUM(dbo.getminutes([BEFORE_LEAD_TIME],[BEFORE_LEAD_TIME_UOM]))      
  
   
 ELSE 0        
 END * 100)) AS 'REDUCTION_IN_LEAD_TIME',          
        
 ABS(FLOOR(CASE WHEN SUM([BEFORE_CYCLE_TIME]) > 0  THEN (SUM(dbo.getminutes([BEFORE_CYCLE_TIME],[BEFORE_CYCLE_TIME_UOM]))  -  SUM(dbo.getminutes([AFTER_CYCLE_TIME],[AFTER_CYCLE_TIME_UOM]))) / SUM(dbo.getminutes([BEFORE_CYCLE_TIME],[BEFORE_CYCLE_TIME_UOM])
        
)         
 ELSE 0        
 END * 100)) AS 'REDUCTION_IN_CYCLE_TIME',        
        
 ABS(FLOOR(SUM(BEFORE_ERROR))) AS 'TOTAL_BEFORE_ERROR',        
 ABS(FLOOR(SUM(AFTER_ERROR))) AS 'TOTAL_AFTER_ERROR',        
 ABS(FLOOR(SUM(BEFORE_LEAD_TIME))) AS 'TOTAL_BEFORE_LEAD',        
 ABS(FLOOR(SUM(AFTER_LEAD_TIME))) AS 'TOTAL_AFTER_LEAD',        
        
 ABS(FLOOR(SUM(BEFORE_CYCLE_TIME))) AS 'TOTAL_BEFORE_CYCLE',        
 ABS(FLOOR(SUM(AFTER_CYCLE_TIME))) AS 'TOTAL_AFTER_CYCLE',        
 ABS(FLOOR(SUM(CASE WHEN IS_ONETIME = 1 THEN BEFORE_EFFORT    
     ELSE (BEFORE_EFFORT * BEFORE_OCCOURANCE_COUNT)    
     END))) AS [BEFORE_EFFORT],    
 ABS(FLOOR(SUM(CASE WHEN IS_ONETIME = 1 THEN AFTER_EFFORT    
     ELSE (AFTER_EFFORT * AFTER_OCCOURANCE_COUNT)    
     END))) AS [AFTER_EFFORT],    
   
        
 ABS(FLOOR(SUM(CUSTOMER_PERSONHOUR_SAVINGS))) AS 'SAVING_PER_YEAR_EFFORT',          
        
         
 ABS(FLOOR(SUM( CASE WHEN INTERNAL_SAVINGS <> 'NaN' then CAST(INTERNAL_SAVINGS AS NUMERIC(10, 2))        
 ELSE 0 END        
 )))  AS 'SAVINGS_IN_USD',         
         
 ABS(FLOOR(SUM(CUSTOMER_SAVINGS)))  AS 'HARD_BENEFITS',        
 ' ' AS 'SOFT_BENEFITS',        
 ABS(FLOOR(SUM(FINANCIAL_REVENUE))) AS 'REVENUE',        
 ABS(FLOOR(SUM(FINANCIAL_OPERATING_COST))) AS 'OPERATING_COST',        
 ABS(FLOOR(SUM(FINANCIAL_PROFITABILITY))) AS 'PROFITABILITY'        
 FROM project_innovation PI         
        
 INNER JOIN [BAS].DBO.PROJECT P ON PI.PROJECT_ID = P.PROJ_ID         
 INNER JOIN [BAS].DBO.CUSTOMER C ON C.CUST_ID = P.CUST_ID        
 LEFT JOIN  PORTFOLIO_PROJECT PP on PP.PROJ_ID = p.PROJ_ID and pp.ISACTIVE = 1        
 left join PORTFOLIO port on port.ID = pp.PORTFOLIO_ID and port.ISACTIVE = 1        
        
 WHERE         
         
 (((@statuS_IDENTIFIED = 1 and pi.STATUS = 'Identified') or (@statuS_PLANNING = 2 and pi.STATUS = 'Planning') or
	(@statuS_EXECUTION = 3 and pi.STATUS = 'Execution')
 ) OR  (@statuS_COMPLETED = 4 and pi.status = 'Completed' and (pi.actual_date >= @STARTDATE and pi.actual_date <= @ENDDATE)) )         
 AND PI.IDENTIFIED_DATE <= @ENDDATE AND PI.STATUS NOT IN ('Cancelled','Suspended')         
 AND (@CUSTID = -1 OR C.CUST_ID = @CUSTID)         
 AND (@PROJIDS = '' OR PI.PROJECT_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,',')))        
 AND PI.ISACTIVE = 1        
 AND (        
  (@AUTOMATE = 1 AND PI.AUTOMATE = @AUTOMATE) OR         
  (@INNOVATION = 1 AND PI.ISINNOVATION = @INNOVATION) OR        
  (@IMPROVEMENT = 1 AND PI.ISPROCESSIMPROVEMENT = @IMPROVEMENT) OR        
     (@CUSTOMER_SAVINGS = 1 AND (PI.CUSTOMER_SAVINGS IS NOT NULL OR CUSTOMER_BUSINESS_VALUE IS NOT NULL))        
  )        
        
 GROUP BY C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE, P.PROJ_ID, P.PROJ_NM        
END   

GO

IF EXISTS(Select 1 from sys.objects where name ='GET_CI_TRACKER_DATA' AND type='P')
BEGIN
       DROP PROCEDURE [dbo].[GET_CI_TRACKER_DATA]
END

GO

CREATE PROCEDURE [dbo].[GET_CI_TRACKER_DATA]          
@AUTOMATE BIT,          
@CUSTOMER_SAVINGS BIT,          
@STARTDATE DATETIME,          
@ENDDATE DATETIME,          
@PROJIDS VARCHAR(MAX),          
@CUSTID int,          
@INNOVATION bit,          
@IMPROVEMENT bit,          
@ALL bit,          
@VIEWBY int = 0,          
@IISTATUS VARCHAR(50)          
          
AS          
BEGIN          
          
DECLARE @statuS_IDENTIFIED INT = 0          
DECLARE @statuS_PLANNING INT = 0          
DECLARE @statuS_EXECUTION INT = 0          
DECLARE @statuS_COMPLETED INT = 0          
          
select @statuS_IDENTIFIED = item from [DBO].[FN_SPLITSTRING](@IISTATUS,',') where item=1          
select @statuS_PLANNING = item from [DBO].[FN_SPLITSTRING](@IISTATUS,',') where item=2          
select @statuS_EXECUTION = item from [DBO].[FN_SPLITSTRING](@IISTATUS,',') where item=3          
select @statuS_COMPLETED = item from [DBO].[FN_SPLITSTRING](@IISTATUS,',') where item=4          
          
          
if(@ALL = 1)          
 SELECT C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE AS 'PORTFOLIO_NM', P.PROJ_ID, P.PROJ_NM,           
 SUM(CASE WHEN @statuS_COMPLETED = 4 AND PI.STATUS = 'Completed' AND (PI.ACTUAL_DATE >= @STARTDATE AND PI.ACTUAL_DATE <= @ENDDATE)  THEN 1 ELSE 0 END) 'COMPLETED',          
 SUM(CASE WHEN @statuS_IDENTIFIED = 1 AND PI.STATUS = 'Identified' THEN 1           
          WHEN @statuS_PLANNING = 2   AND PI.STATUS = 'Planning' THEN 1             
       WHEN @statuS_EXECUTION = 3   AND PI.STATUS = 'Execution' THEN 1           
       ELSE 0 END) 'INPROGRESS',          
          
 ABS(FLOOR(CASE WHEN SUM([BEFORE_ERROR]) > 0 THEN (SUM([BEFORE_ERROR]) -  SUM([AFTER_ERROR])) / SUM([BEFORE_ERROR])           
 ELSE 0          
 END * 100)) AS 'QUALITY_REDUCTION_OF_ERRORS',          
         
 ABS(FLOOR(SUM(BEFORE_ERROR))) AS 'TOTAL_BEFORE_ERROR',          
 ABS(FLOOR(SUM(AFTER_ERROR))) AS 'TOTAL_AFTER_ERROR',          
 ABS(FLOOR(SUM(dbo.getminutes([BEFORE_LEAD_TIME],[BEFORE_LEAD_TIME_UOM])))) AS 'TOTAL_BEFORE_LEAD',          
 ABS(FLOOR(SUM(dbo.getminutes([AFTER_LEAD_TIME],[AFTER_LEAD_TIME_UOM])))) AS 'TOTAL_AFTER_LEAD',          
          
 ABS(FLOOR(SUM(dbo.getminutes([BEFORE_CYCLE_TIME],[BEFORE_CYCLE_TIME_UOM])))) AS 'TOTAL_BEFORE_CYCLE',          
 ABS(FLOOR(SUM(dbo.getminutes([AFTER_CYCLE_TIME],[AFTER_CYCLE_TIME_UOM])))) AS 'TOTAL_AFTER_CYCLE',           
 ABS(FLOOR(SUM(CASE WHEN IS_ONETIME = 1 THEN BEFORE_EFFORT  
   ELSE (
	CASE WHEN BEFORE_TIME_TAKEN_UOM = 1 THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) / 60, 0)
		 WHEN  BEFORE_TIME_TAKEN_UOM = 2 THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT), 0)
		 WHEN  BEFORE_TIME_TAKEN_UOM = 3 THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) * 8, 0)
	END
   )  
  END))) AS [BEFORE_EFFORT],      
 ABS(FLOOR(SUM(CASE WHEN IS_ONETIME = 1 THEN AFTER_EFFORT   
   ELSE (CASE WHEN AFTER_TIME_TAKEN_UOM = 1 THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) / 60, 0)
			  WHEN  AFTER_TIME_TAKEN_UOM = 2 THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT), 0)
			  WHEN  AFTER_TIME_TAKEN_UOM = 3 THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) * 8, 0)
	END)  
  END))) AS [AFTER_EFFORT],    
  ABS(FLOOR(SUM(CASE WHEN (IS_ONETIME = 1 AND AUTOMATE = 1) THEN BEFORE_EFFORT  
   ELSE (
	CASE WHEN  (BEFORE_TIME_TAKEN_UOM = 1 AND AUTOMATE = 1) THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) / 60, 0)
		 WHEN  (BEFORE_TIME_TAKEN_UOM = 2 AND AUTOMATE = 1) THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT), 0)
		 WHEN  (BEFORE_TIME_TAKEN_UOM = 3 AND AUTOMATE = 1) THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) * 8, 0)
	END
   )  
  END))) AS [BEFORE_EFFORT_AUTOMATION],      
 ABS(FLOOR(SUM(CASE WHEN (IS_ONETIME = 1 AND AUTOMATE = 1) THEN AFTER_EFFORT   
   ELSE (CASE WHEN (AFTER_TIME_TAKEN_UOM = 1 AND AUTOMATE = 1) THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) / 60, 0)
		 WHEN  (AFTER_TIME_TAKEN_UOM = 2 AND AUTOMATE = 1) THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT), 0)
		 WHEN  (AFTER_TIME_TAKEN_UOM = 3 AND AUTOMATE = 1) THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) * 8, 0)
	END)  
  END))) AS [AFTER_EFFORT_AUTOMATION],    
            
 ABS(FLOOR(SUM( CASE WHEN INTERNAL_SAVINGS <> 'NaN' then CAST(INTERNAL_SAVINGS AS NUMERIC(10, 2))          
 ELSE 0 END          
 )))  AS 'SAVINGS_IN_USD',           
      
 ABS(FLOOR(SUM(CUSTOMER_SAVINGS)))  AS 'HARD_BENEFITS',          
 ' ' AS 'SOFT_BENEFITS',          
 ABS(FLOOR(SUM(FINANCIAL_REVENUE))) AS 'REVENUE',          
 ABS(FLOOR(SUM(FINANCIAL_OPERATING_COST))) AS 'OPERATING_COST',          
 ABS(FLOOR(SUM(FINANCIAL_PROFITABILITY))) AS 'PROFITABILITY'          
 FROM project_innovation PI           
          
 INNER JOIN [BAS].DBO.PROJECT P ON PI.PROJECT_ID = P.PROJ_ID           
 INNER JOIN [BAS].DBO.CUSTOMER C ON C.CUST_ID = P.CUST_ID          
 LEFT JOIN  PORTFOLIO_PROJECT PP on PP.PROJ_ID = p.PROJ_ID and pp.ISACTIVE = 1          
 left join PORTFOLIO port on port.ID = pp.PORTFOLIO_ID and port.ISACTIVE = 1           
           
 WHERE           
           
 (((@statuS_IDENTIFIED = 1 and pi.STATUS = 'Identified') OR (@statuS_PLANNING = 2 and pi.STATUS = 'Planning') OR 
 (@statuS_EXECUTION = 3 and pi.STATUS = 'Execution')  
 ) OR  (@statuS_COMPLETED = 4 and pi.status = 'Completed' and (pi.actual_date >= @STARTDATE and pi.actual_date <= @ENDDATE)) )           
 AND PI.IDENTIFIED_DATE <= @ENDDATE AND PI.STATUS NOT IN ('Cancelled','Suspended')          
 AND (@CUSTID = -1 OR C.CUST_ID = @CUSTID)           
 AND (@PROJIDS = '' OR PI.PROJECT_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,','))) and PI.ISACTIVE = 1          
 GROUP BY C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE, P.PROJ_ID, P.PROJ_NM          
          
ELSE          
           
 SELECT C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE AS 'PORTFOLIO_NM', P.PROJ_ID, P.PROJ_NM,           
 SUM(CASE WHEN @statuS_COMPLETED = 4 AND PI.STATUS = 'Completed' AND (PI.ACTUAL_DATE >= @STARTDATE AND PI.ACTUAL_DATE <= @ENDDATE)  THEN 1 ELSE 0 END) 'COMPLETED',          
 SUM(CASE WHEN @statuS_IDENTIFIED = 1 AND PI.STATUS = 'Identified' THEN 1           
          WHEN @statuS_PLANNING = 2   AND PI.STATUS = 'Planning' THEN 1             
       WHEN @statuS_EXECUTION = 3   AND PI.STATUS = 'Execution' THEN 1           
       ELSE 0 END) 'INPROGRESS',          
          
 ABS(FLOOR(CASE WHEN SUM([BEFORE_ERROR]) > 0 THEN (SUM([BEFORE_ERROR]) -  SUM([AFTER_ERROR])) / SUM([BEFORE_ERROR])           
 ELSE 0          
 END * 100)) AS 'QUALITY_REDUCTION_OF_ERRORS',          
         
 ABS(FLOOR(SUM(BEFORE_ERROR))) AS 'TOTAL_BEFORE_ERROR',          
 ABS(FLOOR(SUM(AFTER_ERROR))) AS 'TOTAL_AFTER_ERROR',          
 ABS(FLOOR(SUM(dbo.getminutes([BEFORE_LEAD_TIME],[BEFORE_LEAD_TIME_UOM])))) AS 'TOTAL_BEFORE_LEAD',          
 ABS(FLOOR(SUM(dbo.getminutes([AFTER_LEAD_TIME],[AFTER_LEAD_TIME_UOM])))) AS 'TOTAL_AFTER_LEAD',          
          
 ABS(FLOOR(SUM(dbo.getminutes([BEFORE_CYCLE_TIME],[BEFORE_CYCLE_TIME_UOM])))) AS 'TOTAL_BEFORE_CYCLE',          
 ABS(FLOOR(SUM(dbo.getminutes([AFTER_CYCLE_TIME],[AFTER_CYCLE_TIME_UOM])))) AS 'TOTAL_AFTER_CYCLE',          
 ABS(FLOOR(SUM(CASE WHEN IS_ONETIME = 1 THEN BEFORE_EFFORT  
   ELSE (
	CASE WHEN BEFORE_TIME_TAKEN_UOM = 1 THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) / 60, 0)
		 WHEN  BEFORE_TIME_TAKEN_UOM = 2 THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT), 0)
		 WHEN  BEFORE_TIME_TAKEN_UOM = 3 THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) * 8, 0)
	END
   )  
  END))) AS [BEFORE_EFFORT],      
 ABS(FLOOR(SUM(CASE WHEN IS_ONETIME = 1 THEN AFTER_EFFORT   
   ELSE (CASE WHEN AFTER_TIME_TAKEN_UOM = 1 THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) / 60, 0)
		 WHEN  AFTER_TIME_TAKEN_UOM = 2 THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT), 0)
		 WHEN  AFTER_TIME_TAKEN_UOM = 3 THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) * 8, 0)
	END)  
  END))) AS [AFTER_EFFORT],      
    ABS(FLOOR(SUM(CASE WHEN (IS_ONETIME = 1 AND AUTOMATE = 1) THEN BEFORE_EFFORT  
   ELSE (
	CASE WHEN  (BEFORE_TIME_TAKEN_UOM = 1 AND AUTOMATE = 1) THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) / 60, 0)
		 WHEN  (BEFORE_TIME_TAKEN_UOM = 2 AND AUTOMATE = 1) THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT), 0)
		 WHEN  (BEFORE_TIME_TAKEN_UOM = 3 AND AUTOMATE = 1) THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) * 8, 0)
	END
   )  
  END))) AS [BEFORE_EFFORT_AUTOMATION],      
 ABS(FLOOR(SUM(CASE WHEN (IS_ONETIME = 1 AND AUTOMATE = 1) THEN AFTER_EFFORT   
   ELSE (CASE WHEN (AFTER_TIME_TAKEN_UOM = 1 AND AUTOMATE = 1) THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) / 60, 0)
		 WHEN  (AFTER_TIME_TAKEN_UOM = 2 AND AUTOMATE = 1) THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT), 0)
		 WHEN  (AFTER_TIME_TAKEN_UOM = 3 AND AUTOMATE = 1) THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) * 8, 0)
	END)  
  END))) AS [AFTER_EFFORT_AUTOMATION],    
           
 ABS(FLOOR(SUM( CASE WHEN INTERNAL_SAVINGS <> 'NaN' then CAST(INTERNAL_SAVINGS AS NUMERIC(10, 2))          
 ELSE 0 END          
 )))  AS 'SAVINGS_IN_USD',           
           
 ABS(FLOOR(SUM(CUSTOMER_SAVINGS)))  AS 'HARD_BENEFITS',          
 ' ' AS 'SOFT_BENEFITS',          
 ABS(FLOOR(SUM(FINANCIAL_REVENUE))) AS 'REVENUE',          
 ABS(FLOOR(SUM(FINANCIAL_OPERATING_COST))) AS 'OPERATING_COST',          
 ABS(FLOOR(SUM(FINANCIAL_PROFITABILITY))) AS 'PROFITABILITY'          
 FROM project_innovation PI           
          
 INNER JOIN [BAS].DBO.PROJECT P ON PI.PROJECT_ID = P.PROJ_ID           
 INNER JOIN [BAS].DBO.CUSTOMER C ON C.CUST_ID = P.CUST_ID          
 LEFT JOIN  PORTFOLIO_PROJECT PP on PP.PROJ_ID = p.PROJ_ID and pp.ISACTIVE = 1          
 left join PORTFOLIO port on port.ID = pp.PORTFOLIO_ID and port.ISACTIVE = 1          
          
 WHERE           
           
 (((@statuS_IDENTIFIED = 1 and pi.STATUS = 'Identified') OR (@statuS_PLANNING = 2 and pi.STATUS = 'Planning') OR
 (@statuS_EXECUTION = 3 and pi.STATUS = 'Execution')  
 ) OR  (@statuS_COMPLETED = 4 and pi.status = 'Completed' and (pi.actual_date >= @STARTDATE and pi.actual_date <= @ENDDATE)) )           
 AND PI.IDENTIFIED_DATE <= @ENDDATE AND PI.STATUS NOT IN ('Cancelled','Suspended')           
 AND (@CUSTID = -1 OR C.CUST_ID = @CUSTID)           
 AND (@PROJIDS = '' OR PI.PROJECT_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,',')))          
 AND PI.ISACTIVE = 1          
 AND (          
  (@AUTOMATE = 1 AND PI.AUTOMATE = @AUTOMATE) OR           
  (@INNOVATION = 1 AND PI.ISINNOVATION = @INNOVATION) OR          
  (@IMPROVEMENT = 1 AND PI.ISPROCESSIMPROVEMENT = @IMPROVEMENT) OR          
     (@CUSTOMER_SAVINGS = 1 AND (PI.CUSTOMER_SAVINGS IS NOT NULL OR CUSTOMER_BUSINESS_VALUE IS NOT NULL))          
  )          
          
 GROUP BY C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE, P.PROJ_ID, P.PROJ_NM          
END 

GO

IF EXISTS(Select 1 from sys.objects where name ='GET_CI_TRACKER_DATA' AND type='P')
BEGIN
       DROP PROCEDURE [dbo].[GET_CI_TRACKER_DATA]
END

GO

CREATE PROCEDURE [dbo].[GET_CI_TRACKER_DATA]              
@AUTOMATE BIT,              
@CUSTOMER_SAVINGS BIT,              
@STARTDATE DATETIME,              
@ENDDATE DATETIME,              
@PROJIDS VARCHAR(MAX),              
@CUSTID int,              
@INNOVATION bit,              
@IMPROVEMENT bit,              
@ALL bit,              
@VIEWBY int = 0,              
@IISTATUS VARCHAR(50)              
              
AS              
BEGIN              
              
DECLARE @statuS_IDENTIFIED INT = 0              
DECLARE @statuS_PLANNING INT = 0              
DECLARE @statuS_EXECUTION INT = 0              
DECLARE @statuS_COMPLETED INT = 0              
              
select @statuS_IDENTIFIED = item from [DBO].[FN_SPLITSTRING](@IISTATUS,',') where item=1              
select @statuS_PLANNING = item from [DBO].[FN_SPLITSTRING](@IISTATUS,',') where item=2              
select @statuS_EXECUTION = item from [DBO].[FN_SPLITSTRING](@IISTATUS,',') where item=3              
select @statuS_COMPLETED = item from [DBO].[FN_SPLITSTRING](@IISTATUS,',') where item=4              
              
              
if(@ALL = 1)              
 SELECT C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE AS 'PORTFOLIO_NM', P.PROJ_ID, P.PROJ_NM,               
 SUM(CASE WHEN @statuS_COMPLETED = 4 AND PI.STATUS = 'Completed' AND (PI.ACTUAL_DATE >= @STARTDATE AND PI.ACTUAL_DATE <= @ENDDATE)  THEN 1 ELSE 0 END) 'COMPLETED',              
 SUM(CASE WHEN @statuS_IDENTIFIED = 1 AND PI.STATUS = 'Identified' THEN 1               
          WHEN @statuS_PLANNING = 2   AND PI.STATUS = 'Planning' THEN 1                 
       WHEN @statuS_EXECUTION = 3   AND PI.STATUS = 'Execution' THEN 1               
       ELSE 0 END) 'INPROGRESS',              
              
 ABS(FLOOR(CASE WHEN SUM([BEFORE_ERROR]) > 0 THEN (SUM([BEFORE_ERROR]) -  SUM([AFTER_ERROR])) / SUM([BEFORE_ERROR])               
 ELSE 0              
 END * 100)) AS 'QUALITY_REDUCTION_OF_ERRORS',              
             
 ABS(FLOOR(SUM(BEFORE_ERROR))) AS 'TOTAL_BEFORE_ERROR',              
 ABS(FLOOR(SUM(AFTER_ERROR))) AS 'TOTAL_AFTER_ERROR',              
 ABS(FLOOR(SUM(dbo.getminutes([BEFORE_LEAD_TIME],[BEFORE_LEAD_TIME_UOM])))) AS 'TOTAL_BEFORE_LEAD',              
 ABS(FLOOR(SUM(dbo.getminutes([AFTER_LEAD_TIME],[AFTER_LEAD_TIME_UOM])))) AS 'TOTAL_AFTER_LEAD',              
              
 ABS(FLOOR(SUM(dbo.getminutes([BEFORE_CYCLE_TIME],[BEFORE_CYCLE_TIME_UOM])))) AS 'TOTAL_BEFORE_CYCLE',              
 ABS(FLOOR(SUM(dbo.getminutes([AFTER_CYCLE_TIME],[AFTER_CYCLE_TIME_UOM])))) AS 'TOTAL_AFTER_CYCLE',               
 ABS(FLOOR(SUM(CASE WHEN IS_ONETIME = 1 THEN BEFORE_EFFORT      
   ELSE (    
 CASE WHEN BEFORE_TIME_TAKEN_UOM = 1 THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) / 60, 0)    
   WHEN  BEFORE_TIME_TAKEN_UOM = 2 THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT), 0)    
   WHEN  BEFORE_TIME_TAKEN_UOM = 3 THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) * 8, 0)    
 END    
   )      
  END))) AS [BEFORE_EFFORT],          
 ABS(FLOOR(SUM(CASE WHEN IS_ONETIME = 1 THEN AFTER_EFFORT       
   ELSE (CASE WHEN AFTER_TIME_TAKEN_UOM = 1 THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) / 60, 0)    
     WHEN  AFTER_TIME_TAKEN_UOM = 2 THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT), 0)    
     WHEN  AFTER_TIME_TAKEN_UOM = 3 THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) * 8, 0)    
 END)      
  END))) AS [AFTER_EFFORT],        
  ABS(FLOOR(SUM(CASE WHEN (IS_ONETIME = 1 AND AUTOMATE = 1) THEN BEFORE_EFFORT      
   ELSE (    
 CASE WHEN  (BEFORE_TIME_TAKEN_UOM = 1 AND AUTOMATE = 1) THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) / 60, 0)    
   WHEN  (BEFORE_TIME_TAKEN_UOM = 2 AND AUTOMATE = 1) THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT), 0)    
   WHEN  (BEFORE_TIME_TAKEN_UOM = 3 AND AUTOMATE = 1) THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) * 8, 0)    
 END    
   )      
  END))) AS [BEFORE_EFFORT_AUTOMATION],          
 ABS(FLOOR(SUM(CASE WHEN (IS_ONETIME = 1 AND AUTOMATE = 1) THEN AFTER_EFFORT       
   ELSE (CASE WHEN (AFTER_TIME_TAKEN_UOM = 1 AND AUTOMATE = 1) THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) / 60, 0)    
   WHEN  (AFTER_TIME_TAKEN_UOM = 2 AND AUTOMATE = 1) THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT), 0)    
   WHEN  (AFTER_TIME_TAKEN_UOM = 3 AND AUTOMATE = 1) THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) * 8, 0)    
 END)      
  END))) AS [AFTER_EFFORT_AUTOMATION],       
  ABS(SUM(CASE WHEN (BEFORE_EFFORT IS NULL AND AFTER_EFFORT IS NULL) THEN CUSTOMER_PERSONHOUR_SAVINGS  
    ELSE 0 END)) AS 'SAVING_PER_YEAR_EFFORT',   
                
 ABS(FLOOR(SUM( CASE WHEN INTERNAL_SAVINGS <> 'NaN' then CAST(INTERNAL_SAVINGS AS NUMERIC(10, 2))              
 ELSE 0 END              
 )))  AS 'SAVINGS_IN_USD',               
          
 ABS(FLOOR(SUM(CUSTOMER_SAVINGS)))  AS 'HARD_BENEFITS',              
 ' ' AS 'SOFT_BENEFITS',              
 ABS(FLOOR(SUM(FINANCIAL_REVENUE))) AS 'REVENUE',              
 ABS(FLOOR(SUM(FINANCIAL_OPERATING_COST))) AS 'OPERATING_COST',              
 ABS(FLOOR(SUM(FINANCIAL_PROFITABILITY))) AS 'PROFITABILITY'              
 FROM project_innovation PI               
              
 INNER JOIN [BAS].DBO.PROJECT P ON PI.PROJECT_ID = P.PROJ_ID               
 INNER JOIN [BAS].DBO.CUSTOMER C ON C.CUST_ID = P.CUST_ID              
 LEFT JOIN  PORTFOLIO_PROJECT PP on PP.PROJ_ID = p.PROJ_ID and pp.ISACTIVE = 1              
 left join PORTFOLIO port on port.ID = pp.PORTFOLIO_ID and port.ISACTIVE = 1               
               
 WHERE               
               
 (((@statuS_IDENTIFIED = 1 and pi.STATUS = 'Identified') OR (@statuS_PLANNING = 2 and pi.STATUS = 'Planning') OR     
 (@statuS_EXECUTION = 3 and pi.STATUS = 'Execution')      
 ) OR  (@statuS_COMPLETED = 4 and pi.status = 'Completed' and (pi.actual_date >= @STARTDATE and pi.actual_date <= @ENDDATE)) )               
 AND PI.IDENTIFIED_DATE <= @ENDDATE AND PI.STATUS NOT IN ('Cancelled','Suspended')              
 AND (@CUSTID = -1 OR C.CUST_ID = @CUSTID)               
 AND (@PROJIDS = '' OR PI.PROJECT_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,','))) and PI.ISACTIVE = 1              
 GROUP BY C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE, P.PROJ_ID, P.PROJ_NM              
              
ELSE              
               
 SELECT C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE AS 'PORTFOLIO_NM', P.PROJ_ID, P.PROJ_NM,               
 SUM(CASE WHEN @statuS_COMPLETED = 4 AND PI.STATUS = 'Completed' AND (PI.ACTUAL_DATE >= @STARTDATE AND PI.ACTUAL_DATE <= @ENDDATE)  THEN 1 ELSE 0 END) 'COMPLETED',              
 SUM(CASE WHEN @statuS_IDENTIFIED = 1 AND PI.STATUS = 'Identified' THEN 1               
          WHEN @statuS_PLANNING = 2   AND PI.STATUS = 'Planning' THEN 1                 
       WHEN @statuS_EXECUTION = 3   AND PI.STATUS = 'Execution' THEN 1               
       ELSE 0 END) 'INPROGRESS',              
              
 ABS(FLOOR(CASE WHEN SUM([BEFORE_ERROR]) > 0 THEN (SUM([BEFORE_ERROR]) -  SUM([AFTER_ERROR])) / SUM([BEFORE_ERROR])               
 ELSE 0              
 END * 100)) AS 'QUALITY_REDUCTION_OF_ERRORS',              
             
 ABS(FLOOR(SUM(BEFORE_ERROR))) AS 'TOTAL_BEFORE_ERROR',              
 ABS(FLOOR(SUM(AFTER_ERROR))) AS 'TOTAL_AFTER_ERROR',              
 ABS(FLOOR(SUM(dbo.getminutes([BEFORE_LEAD_TIME],[BEFORE_LEAD_TIME_UOM])))) AS 'TOTAL_BEFORE_LEAD',              
 ABS(FLOOR(SUM(dbo.getminutes([AFTER_LEAD_TIME],[AFTER_LEAD_TIME_UOM])))) AS 'TOTAL_AFTER_LEAD',              
              
 ABS(FLOOR(SUM(dbo.getminutes([BEFORE_CYCLE_TIME],[BEFORE_CYCLE_TIME_UOM])))) AS 'TOTAL_BEFORE_CYCLE',              
 ABS(FLOOR(SUM(dbo.getminutes([AFTER_CYCLE_TIME],[AFTER_CYCLE_TIME_UOM])))) AS 'TOTAL_AFTER_CYCLE',              
 ABS(FLOOR(SUM(CASE WHEN IS_ONETIME = 1 THEN BEFORE_EFFORT      
   ELSE (    
 CASE WHEN BEFORE_TIME_TAKEN_UOM = 1 THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) / 60, 0)    
   WHEN  BEFORE_TIME_TAKEN_UOM = 2 THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT), 0)    
   WHEN  BEFORE_TIME_TAKEN_UOM = 3 THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) * 8, 0)    
 END    
   )      
  END))) AS [BEFORE_EFFORT],          
 ABS(FLOOR(SUM(CASE WHEN IS_ONETIME = 1 THEN AFTER_EFFORT       
   ELSE (CASE WHEN AFTER_TIME_TAKEN_UOM = 1 THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) / 60, 0)    
   WHEN  AFTER_TIME_TAKEN_UOM = 2 THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT), 0)    
   WHEN  AFTER_TIME_TAKEN_UOM = 3 THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) * 8, 0)    
 END)      
  END))) AS [AFTER_EFFORT],          
    ABS(FLOOR(SUM(CASE WHEN (IS_ONETIME = 1 AND AUTOMATE = 1) THEN BEFORE_EFFORT      
   ELSE (    
 CASE WHEN  (BEFORE_TIME_TAKEN_UOM = 1 AND AUTOMATE = 1) THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) / 60, 0)    
   WHEN  (BEFORE_TIME_TAKEN_UOM = 2 AND AUTOMATE = 1) THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT), 0)    
   WHEN  (BEFORE_TIME_TAKEN_UOM = 3 AND AUTOMATE = 1) THEN ROUND((BEFORE_TIME_TAKEN * BEFORE_OCCOURANCE_COUNT) * 8, 0)    
 END    
   )      
  END))) AS [BEFORE_EFFORT_AUTOMATION],          
 ABS(FLOOR(SUM(CASE WHEN (IS_ONETIME = 1 AND AUTOMATE = 1) THEN AFTER_EFFORT       
   ELSE (CASE WHEN (AFTER_TIME_TAKEN_UOM = 1 AND AUTOMATE = 1) THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) / 60, 0)    
   WHEN  (AFTER_TIME_TAKEN_UOM = 2 AND AUTOMATE = 1) THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT), 0)    
   WHEN  (AFTER_TIME_TAKEN_UOM = 3 AND AUTOMATE = 1) THEN ROUND((AFTER_TIME_TAKEN * AFTER_OCCOURANCE_COUNT) * 8, 0)    
 END)      
  END))) AS [AFTER_EFFORT_AUTOMATION],     
    
 ABS(SUM(CASE WHEN (BEFORE_EFFORT IS NULL AND AFTER_EFFORT IS NULL) THEN CUSTOMER_PERSONHOUR_SAVINGS  
    ELSE 0 END)) AS 'SAVING_PER_YEAR_EFFORT',   
               
 ABS(FLOOR(SUM( CASE WHEN INTERNAL_SAVINGS <> 'NaN' then CAST(INTERNAL_SAVINGS AS NUMERIC(10, 2))              
 ELSE 0 END              
 )))  AS 'SAVINGS_IN_USD',               
               
 ABS(FLOOR(SUM(CUSTOMER_SAVINGS)))  AS 'HARD_BENEFITS',              
 ' ' AS 'SOFT_BENEFITS',              
 ABS(FLOOR(SUM(FINANCIAL_REVENUE))) AS 'REVENUE',              
 ABS(FLOOR(SUM(FINANCIAL_OPERATING_COST))) AS 'OPERATING_COST',              
 ABS(FLOOR(SUM(FINANCIAL_PROFITABILITY))) AS 'PROFITABILITY'              
 FROM project_innovation PI               
              
 INNER JOIN [BAS].DBO.PROJECT P ON PI.PROJECT_ID = P.PROJ_ID               
 INNER JOIN [BAS].DBO.CUSTOMER C ON C.CUST_ID = P.CUST_ID              
 LEFT JOIN  PORTFOLIO_PROJECT PP on PP.PROJ_ID = p.PROJ_ID and pp.ISACTIVE = 1              
 left join PORTFOLIO port on port.ID = pp.PORTFOLIO_ID and port.ISACTIVE = 1              
              
 WHERE               
               
 (((@statuS_IDENTIFIED = 1 and pi.STATUS = 'Identified') OR (@statuS_PLANNING = 2 and pi.STATUS = 'Planning') OR    
 (@statuS_EXECUTION = 3 and pi.STATUS = 'Execution')      
 ) OR  (@statuS_COMPLETED = 4 and pi.status = 'Completed' and (pi.actual_date >= @STARTDATE and pi.actual_date <= @ENDDATE)) )               
 AND PI.IDENTIFIED_DATE <= @ENDDATE AND PI.STATUS NOT IN ('Cancelled','Suspended')               
 AND (@CUSTID = -1 OR C.CUST_ID = @CUSTID)               
 AND (@PROJIDS = '' OR PI.PROJECT_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,',')))              
 AND PI.ISACTIVE = 1              
 AND (              
  (@AUTOMATE = 1 AND PI.AUTOMATE = @AUTOMATE) OR               
  (@INNOVATION = 1 AND PI.ISINNOVATION = @INNOVATION) OR              
  (@IMPROVEMENT = 1 AND PI.ISPROCESSIMPROVEMENT = @IMPROVEMENT) OR              
     (@CUSTOMER_SAVINGS = 1 AND (PI.CUSTOMER_SAVINGS IS NOT NULL OR CUSTOMER_BUSINESS_VALUE IS NOT NULL))              
  )              
              
 GROUP BY C.CUST_ID, C.CUST_NM, pp.PORTFOLIO_ID, port.TITLE, P.PROJ_ID, P.PROJ_NM              
END 