//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_EXECUTION
    {
        public int ID { get; set; }
        public int AUDIT_EXECUTION_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public string PROJECT_ID { get; set; }
        public Nullable<System.DateTime> AUDIT_START_DATE { get; set; }
        public Nullable<System.DateTime> AUDIT_END_DATE { get; set; }
        public string AUDIT_PLAN_REFERENCE { get; set; }
        public int TEST_ID { get; set; }
        public string TEST_RESULT { get; set; }
        public string STATUS_OF_CONTROL { get; set; }
        public string RESULT_DESCRIPTION { get; set; }
        public string FINDING_DESCRIPTION { get; set; }
        public string FINDING_TYPE { get; set; }
        public Nullable<int> IMPACTING_ATTRIBUTES_ID { get; set; }
        public string SEVERITY { get; set; }
        public string STATUS_OF_AUDIT { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    }
}
