//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BU_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BU_INFO()
        {
            this.DEPT_INFO = new HashSet<DEPT_INFO>();
            this.PROJECTs = new HashSet<PROJECT>();
        }
    
        public short BU_ID { get; set; }
        public string LOCAL_BU_ID { get; set; }
        public string BU_NAME { get; set; }
        public string BU_TYPE { get; set; }
        public string BU_DESC { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string BU_HEAD_EMP_ID { get; set; }
    
        public virtual EMP_INFO EMP_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPT_INFO> DEPT_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT> PROJECTs { get; set; }
    }
}
