//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSINESS_SERVICES
    {
        public int ID { get; set; }
        public string SERVICE_NAME { get; set; }
        public string SERVICE_DESCRIPTION { get; set; }
        public string SERVICE_SHORTFORM { get; set; }
        public bool ISACTIVE { get; set; }
    }
}
