//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNTRY_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CNTRY_INFO()
        {
            this.CNTRY_HOLIDAY = new HashSet<CNTRY_HOLIDAY>();
            this.EMP_PASSPORT = new HashSet<EMP_PASSPORT>();
            this.CUST_ADDR = new HashSet<CUST_ADDR>();
            this.EMP_INFO = new HashSet<EMP_INFO>();
            this.RESRC_RIMBS = new HashSet<RESRC_RIMBS>();
            this.RESRC_RQST = new HashSet<RESRC_RQST>();
            this.LKP_RIMBS_PRE_DEFINED_AMT = new HashSet<LKP_RIMBS_PRE_DEFINED_AMT>();
            this.VISA_DETAILS = new HashSet<VISA_DETAILS>();
        }
    
        public short CNTRY_ID { get; set; }
        public string CNTRY_CD { get; set; }
        public string CNTRY_NM { get; set; }
        public string REGION_NM { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNTRY_HOLIDAY> CNTRY_HOLIDAY { get; set; }
        public virtual CNTRY_WEEKEND CNTRY_WEEKEND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_PASSPORT> EMP_PASSPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUST_ADDR> CUST_ADDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_INFO> EMP_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_RIMBS> RESRC_RIMBS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_RQST> RESRC_RQST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LKP_RIMBS_PRE_DEFINED_AMT> LKP_RIMBS_PRE_DEFINED_AMT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISA_DETAILS> VISA_DETAILS { get; set; }
    }
}
