//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPT_BU_INFO
    {
        public short BU_ID { get; set; }
        public string BU_CD { get; set; }
        public short DEPT_ID { get; set; }
        public string DEPT_CD { get; set; }
        public string Department_Name { get; set; }
        public string PROJ_BUHEAD_EMP_ID { get; set; }
        public string DEPT_HEAD_EMP_ID { get; set; }
    }
}
