//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_PROJ_ROLE_MAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMP_PROJ_ROLE_MAP()
        {
            this.PROJ_RESOURCE = new HashSet<PROJ_RESOURCE>();
        }
    
        public int EMP_PROJ_ROLE_MAP_ID { get; set; }
        public string PROJ_ID { get; set; }
        public short PROJ_ROLE_ID { get; set; }
        public short PROJ_SUB_ROLE_ID { get; set; }
        public short PROJ_ROLE_LOC_ID { get; set; }
        public System.DateTime START_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public decimal HRLY_RATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
    
        public virtual PROJECT PROJECT { get; set; }
        public virtual PROJ_ROLE PROJ_ROLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_RESOURCE> PROJ_RESOURCE { get; set; }
        public virtual PROJ_SUB_ROLE PROJ_SUB_ROLE { get; set; }
        public virtual PROJ_ROLE_LOC PROJ_ROLE_LOC { get; set; }
    }
}
