//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXCHANGE_RATE
    {
        public int EXCH_RATE_ID { get; set; }
        public short CLNDR_YEAR { get; set; }
        public short CLNDR_MONTH { get; set; }
        public short CRNCY_ID { get; set; }
        public decimal EXCH_RATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
    
        public virtual CRNCY_INFO CRNCY_INFO { get; set; }
    }
}
