//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_LOOKUP
    {
        public int MASTER_ID { get; set; }
        public Nullable<int> MASTER_TYPE_ID { get; set; }
        public string MASTER_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public bool ENABLED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual MASTER_TYPE MASTER_TYPE { get; set; }
    }
}
