//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJ_RESOURCE_ROLE_MAP_BILLING
    {
        public int PROJ_RESOURCE_ROLE_MAP_BILLING_ID { get; set; }
        public int PROJ_RESRC_ID { get; set; }
        public int PROJ_ROLE_MAP_BILLING_ID { get; set; }
    
        public virtual PROJ_RESOURCE PROJ_RESOURCE { get; set; }
        public virtual PROJ_ROLE_MAP_BILLING PROJ_ROLE_MAP_BILLING { get; set; }
    }
}
