//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJ_RESRC_TIME_ENTRY
    {
        public int PROJ_RESRC_TIME_ENTRY_ID { get; set; }
        public string PROJ_ID { get; set; }
        public string EMP_ID { get; set; }
        public int DATE_ID { get; set; }
        public Nullable<short> PROJ_TASK_ID { get; set; }
        public string TASK_DESC { get; set; }
        public decimal CLOCKED_MINS { get; set; }
        public string TIME_ENTRY_STATUS { get; set; }
        public string OTHER_DETAILS { get; set; }
        public Nullable<System.DateTime> APPRL_DATE { get; set; }
        public Nullable<System.DateTime> REJECT_DATE { get; set; }
        public string REJECT_DESC { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
        public string BILLING_PROJ_ID { get; set; }
        public string ID { get; set; }
    
        public virtual DATE_DIM DATE_DIM { get; set; }
        public virtual EMP_INFO EMP_INFO { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual PROJ_TASK PROJ_TASK { get; set; }
    }
}
