//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTS_PARAMS
    {
        public int ID { get; set; }
        public int REPORT_SP_ID { get; set; }
        public string PARAM_NAME { get; set; }
        public string PARAM_TYPE { get; set; }
        public string PARAM_VALUE { get; set; }
    }
}
