//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESRC_RQST_SKILLSET
    {
        public short RESRC_RQST_ID { get; set; }
        public short SKILLSET_ID { get; set; }
        public string SKILLSET_TYPE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
    
        public virtual SKILLSET_INFO SKILLSET_INFO { get; set; }
    }
}
