//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESRC_RQST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESRC_RQST()
        {
            this.RESRC_RQST_WF = new HashSet<RESRC_RQST_WF>();
        }
    
        public short RESRC_RQST_ID { get; set; }
        public string PROJ_ID { get; set; }
        public short CNTRY_ID { get; set; }
        public string RESRC_MANAGER_EMP_ID { get; set; }
        public string RESRC_REVIEWER_EMP_ID { get; set; }
        public string RESRC_TYPE { get; set; }
        public string RESRC_LEVEL { get; set; }
        public bool BILL_FLG { get; set; }
        public Nullable<decimal> BILL_RATE { get; set; }
        public Nullable<short> CRNCY_ID { get; set; }
        public string BILL_RATE_TYPE { get; set; }
        public System.DateTime EXPT_START_DATE { get; set; }
        public System.DateTime EXPT_END_DATE { get; set; }
        public string JOB_DESC { get; set; }
        public string JOB_ROLE { get; set; }
        public string DESIRABLE_SKILL { get; set; }
        public string OTHER_SKILL { get; set; }
        public string COMMENTS { get; set; }
        public string REQUEST_TYPE { get; set; }
        public string REPLACEMENT_EMP_ID { get; set; }
        public string EXPERIENCE { get; set; }
        public string SFDC_STATUS { get; set; }
        public string SOW_STATUS { get; set; }
        public string WORK_HOUR { get; set; }
        public Nullable<bool> CLIENT_INTERVIEW { get; set; }
        public string RRF_TYPE { get; set; }
        public string RRF_PRIORITY { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
        public Nullable<short> PRMY_SKILLSET_ID { get; set; }
        public Nullable<short> SCDRY_SKILLSET_ID { get; set; }
        public decimal ALLCT_PCT { get; set; }
    
        public virtual CNTRY_INFO CNTRY_INFO { get; set; }
        public virtual CRNCY_INFO CRNCY_INFO { get; set; }
        public virtual EMP_INFO EMP_INFO { get; set; }
        public virtual EMP_INFO EMP_INFO1 { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual SKILLSET_INFO SKILLSET_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_RQST_WF> RESRC_RQST_WF { get; set; }
        public virtual SKILLSET_INFO SKILLSET_INFO1 { get; set; }
    }
}
