//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIMBS_FILES
    {
        public int RIMBS_FILE_ID { get; set; }
        public Nullable<int> REF_RIMBS_ID { get; set; }
        public Nullable<int> PROJ_RESRC_ID { get; set; }
        public Nullable<int> DATE_ID { get; set; }
        public string RIMBS_TYPE { get; set; }
        public string FILE_NAME { get; set; }
        public byte[] FILE_DATA { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        public virtual DATE_DIM DATE_DIM { get; set; }
        public virtual PROJ_RESOURCE PROJ_RESOURCE { get; set; }
        public virtual RESRC_RIMBS RESRC_RIMBS { get; set; }
    }
}
