//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOW_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOW_INFO()
        {
            this.PROJ_ROLE_BILLING_ALLOCATION = new HashSet<PROJ_ROLE_BILLING_ALLOCATION>();
            this.PROJ_ROLE_MAP_BILLING = new HashSet<PROJ_ROLE_MAP_BILLING>();
            this.PROJECT_EXPENSE = new HashSet<PROJECT_EXPENSE>();
            this.PROJECT_MILESTONE = new HashSet<PROJECT_MILESTONE>();
        }
    
        public int SOW_ID { get; set; }
        public string PROJECT_ID { get; set; }
        public Nullable<System.DateTime> DATE_FROM { get; set; }
        public Nullable<System.DateTime> DATE_TO { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<bool> IS_PROJECTION_FREEZED { get; set; }
        public Nullable<bool> IS_MILESTONE_FREEZED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<decimal> FB_COST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_ROLE_BILLING_ALLOCATION> PROJ_ROLE_BILLING_ALLOCATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_ROLE_MAP_BILLING> PROJ_ROLE_MAP_BILLING { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_EXPENSE> PROJECT_EXPENSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_MILESTONE> PROJECT_MILESTONE { get; set; }
    }
}
