//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOKEN
    {
        public int TOKENID { get; set; }
        public string EMAILID { get; set; }
        public string AUTHKEY { get; set; }
        public Nullable<System.DateTime> ISSUEDON { get; set; }
        public Nullable<System.DateTime> EXPIRESON { get; set; }
    }
}
