//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_INFO
    {
        public int USER_ID { get; set; }
        public int ROLE_ID { get; set; }
        public string LOGIN_ID { get; set; }
        public string EMAIL_ID { get; set; }
        public string EMP_CSP_ROLE { get; set; }
    
        public virtual ROLE_INFO ROLE_INFO { get; set; }
    }
}
