using GAVS.AllocationSystem.Model.AllSys;
using GAVS.AllocationSystem.Model.CSP;
using GAVS.AllocationSystem.Model.CSP.Tables;
//using GAVS.AllocationSystem.Model.CSP.Tables;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GAVS.AllocationSystem.Data.Contracts
{
    public interface ICSPDB
    {
        void Commit(bool canCommit = true);
        IRepository_CSP<APP_ACCESS_CONTROLS> APP_ACCESS_CONTROLS { get; }
        IRepository_CSP<APP_ACCESS_CONTROLS_DETAILS> APP_ACCESS_CONTROLS_DETAILS { get; }
        IRepository_CSP<APP_CONTROL_FEATURES> APP_CONTROL_FEATURES { get; }
        IRepository_CSP<APP_CONTROLS> APP_CONTROLS { get; }
        IRepository_CSP<AUDIT_SCHEDULE> AUDIT_SCHEDULE { get; }
        IRepository_CSP<AUDIT_SCHEDULE_REF> AUDIT_SCHEDULE_REF { get; }
        IRepository_CSP<CONTACTS> CONTACTS { get; }
        IRepository_CSP<CRISP_CATEGORY> CRISP_CATEGORY { get; }
        IRepository_CSP<CRISP_CRITERIA> CRISP_CRITERIA { get; }
        IRepository_CSP<CRISP_PROJECT_CATEGORY> CRISP_PROJECT_CATEGORY { get; }
        IRepository_CSP<CRISP_PROJECT_CRITERIA> CRISP_PROJECT_CRITERIA { get; }
        IRepository_CSP<CRISP_PROJECT_VALIDATIONS> CRISP_PROJECT_VALIDATIONS { get; }
        IRepository_CSP<CRISP_SCORES_CATEGORY> CRISP_SCORES_CATEGORY { get; }
        IRepository_CSP<CRISP_SCORES_PROJECT> CRISP_SCORES_PROJECT { get; }
        IRepository_CSP<CRISP_SCORES_CRITERIA> CRISP_SCORES_CRITERIA { get; }
        IRepository_CSP<CRISP_SCORES_VALIDATIONS> CRISP_SCORES_VALIDATIONS { get; }
        IRepository_CSP<CRISP_VALIDATIONS> CRISP_VALIDATIONS { get; }
        IRepository_CSP<CSS_BATCHES> CSS_BATCHES { get; }
        IRepository_CSP<CSS_BATCH_CUSTOMERS> CSS_BATCH_CUSTOMERS { get; }
        IRepository_CSP<CSS_BATCH_MONTHLY> CSS_BATCH_MONTHLY { get; }
        IRepository_CSP<CSS_BATCH_CUSTOMER_MONTHLY> CSS_BATCH_CUSTOMER_MONTHLY { get; }
        IRepository_CSP<CSS_QUESTION_REPLIES> CSS_QUESTION_REPLIES { get; }
        IRepository_CSP<CSS_QUESTION_MASTER> CSS_QUESTION_MASTER { get; }
        IRepository_CSP<CSS_SURVEY_ITERATION> CSS_SURVEY_ITERATION { get; }
        IRepository_CSP<CUSTOMER_FEEDBACK> CUSTOMER_FEEDBACK { get; }
        IRepository_CSP<CUSTOMER_MOM_DETAILS> CUSTOMER_MOM_DETAILS { get; }
        IRepository_CSP<CUSTOMER_PROJECTS> CUSTOMER_PROJECTS { get; }
        IRepository_CSP<CUSTOMER_USERS> CUSTOMER_USERS { get; }
        IRepository_CSP<CUSTOMER_REPORTS> CUSTOMER_REPORTS { get; }
        IRepository_CSP<DASHBOARD_DETAILS> DASHBOARD_DETAILS { get; }
        IRepository_CSP<ENGAGEMENT_OVERVIEW> ENGAGEMENT_OVERVIEW { get; }
        IRepository_CSP<FILTER_PREFERENCE> FILTER_PREFERENCE { get; }
        IRepository_CSP<SQA_REPORT_FILES> SQA_REPORT_FILES { get; }
        IRepository_CSP<HIGHLIGHTS> HIGHLIGHTS { get; }
        IRepository_CSP<GLOBAL_KPI_CATEGORY> GLOBAL_KPI_CATEGORY { get; }
        IRepository_CSP<GLOBAL_PERSPECTIVE> GLOBAL_PERSPECTIVE { get; }
        IRepository_CSP<GLOBAL_PERSPECTIVE_KPI_CATEGORY_MAPPING> GLOBAL_PERSPECTIVE_KPI_CATEGORY_MAPPING { get; }
        IRepository_CSP<KPI> KPI { get; }
        IRepository_CSP<KPI_DETAILS> KPI_DETAILS { get; }
        IRepository_CSP<KPI_TARGETS> KPI_TARGETS { get; }
        IRepository_CSP<KPI_DetailMonthandWeekly> KPI_DetailMonthandWeekly { get; }
        IRepository_CSP<KPI_GOALS> KPI_GOALS { get; }
        IRepository_CSP<LAST_UPDATED_DETAILS> LAST_UPDATED_DETAILS { get; }

        IRepository_CSP<NOTES>NOTES { get; }
        IRepository_CSP<MOM> MOM { get; }
        IRepository_CSP<PARAMETER_TABLE> PARAMETER_TABLE { get; }
        IRepository_CSP<CSAT_SURVEY_DATA> CSAT_SURVEY_DATA { get; }
        IRepository_CSP<PORTFOLIO> PORTFOLIO { get; }
        
        IRepository_CSP<PORTFOLIO_PRODUCT> PORTFOLIO_PRODUCTS { get; }
        IRepository_CSP<PORTFOLIO_PROJECT> PORTFOLIO_PROJECT { get; }
        IRepository_CSP<PORTFOLIOS> PORTFOLIOS { get; }
        IRepository_CSP<PORTFOLIOS_OWNERS> PORTFOLIOS_OWNERS { get; }
        IRepository_CSP<PORTFOLIOS_OWNERS_PROJECT> PORTFOLIOS_OWNERS_PROJECT { get; }
        IRepository_CSP<PROCESS_AREA> PROCESS_AREA { get; }
        IRepository_CSP<PROCESS_OBJECTIVE_MAPPING> PROCESS_OBJECTIVE_MAPPING { get; }
        IRepository_CSP<PROCESS> PROCESS { get; }
        IRepository_CSP<PROCESS_MODEL_TESTS_NEW> PROCESS_MODEL_TESTS_NEW { get; }
        IRepository_CSP<PROJECT_BEST_PRACTICES> PROJECT_BEST_PRACTICES { get; }
        IRepository_CSP<PROJECT_DELIVERY> PROJECT_DELIVERY { get; }
        IRepository_CSP<PROJECT_INNOVATION> PROJECT_INNOVATION { get; }
        IRepository_CSP<PROJECT_ISSUE> PROJECT_ISSUE { get; }
        IRepository_CSP<PROJECT_LESSON_LEARNT> PROJECT_LESSON_LEARNT { get; }
        IRepository_CSP<PROJECT_PEOPLE> PROJECT_PEOPLE { get; }
        IRepository_CSP<PROJECT_PROCESS> PROJECT_PROCESS { get; }
        IRepository_CSP<PROJECT_RISK> PROJECT_RISK { get; }
        IRepository_CSP<PROJECT_SCOPE> PROJECT_SCOPE { get; }
        IRepository_CSP<PROJECT_SUCCESS> PROJECT_SUCCESS { get; }
        IRepository_CSP<PROJECT_VALUEADDS> PROJECT_VALUEADDS { get; }
        IRepository_CSP<PROJECT_ACTIONITEM> PROJECT_ACTIONITEM { get; }
        IRepository_CSP<PROJECT_RAGS> PROJECT_RAGS { get; }
        IRepository_CSP<PROJECT_CSAT_DATA> PROJECT_CSAT_DATA { get; }
        IRepository_CSP<SQA_CHART_FILTER> SQA_CHART_FILTER { get; }
        IRepository_CSP<SQA_CHART_GROUPS> SQA_CHART_GROUPS { get; }
        IRepository_CSP<SQA_DATA_REPOSITORY> SQA_DATA_REPOSITORY { get; }
        IRepository_CSP<SQA_PROJECT_CHART_PARAMS> SQA_PROJECT_CHART_PARAMS { get; }
        IRepository_CSP<SQA_PROJECT_REPORTS> SQA_PROJECT_REPORTS { get; }
        IRepository_CSP<SQA_PROJECT_REPORTS_STRUCT> SQA_PROJECT_REPORTS_STRUCT { get; }
        //IRepository_CSP<PROJECT_PROCESS_CATEGORY> PROJECT_PROCESS_CATEGORY { get; }
        //IRepository_CSP<PROCESS_MODEL_AUDITOR_DATA> PROCESS_MODEL_AUDITOR_DATA { get; }
        IRepository_CSP<INNOVATION_SERVICE_MAPPING> INNOVATION_SERVICE_MAPPING { get; }
        IRepository_CSP<GAVS_SERVICE> GAVS_SERVICE { get; }
        IRepository_CSP<PROCESS_MODEL> PROCESS_MODEL { get; }
        IRepository_CSP<PROCESS_MODEL_OBJECTIVES> PROCESS_MODEL_OBJECTIVES { get; }
        IRepository_CSP<CONTROL_REFERENCE> CONTROL_REFERENCE { get; }

        IRepository_CSP<PROCESS_MODEL_OBJECTIVES_NEW> PROCESS_MODEL_OBJECTIVES_NEW { get; }

        //IRepository_CSP<PROCESS_OBJECTIVE_MAPPING> PROCESS_OBJECTIVE_MAPPING { get; }

        IRepository_CSP<PROCESS_MODEL_CONTROL_NEW> PROCESS_MODEL_CONTROL_NEW { get; }

        IRepository_CSP<CONTROL_RISKS_MAPPING> CONTROL_RISKS_MAPPING { get; }
        IRepository_CSP<CONTROL_CLASSIFICATIONS> CONTROL_CLASSIFICATIONS { get; }
        IRepository_CSP<TEST_CONTROL_MAPPING> TEST_CONTROL_MAPPING { get; }
        IRepository_CSP<PROCESS_MODEL_RISKS> PROCESS_MODEL_RISKS { get; }
        IRepository_CSP<PROCESS_MODEL_CONTROL> PROCESS_MODEL_CONTROL { get; }
        IRepository_CSP<PROCESS_MODEL_TESTS> PROCESS_MODEL_TESTS { get; }
        IRepository_CSP<PROCESS_SERVICE_AREA> PROCESS_SERVICE_AREA { get; }
        IRepository_CSP<PROCESS_SERVICE_AREA_NEW> PROCESS_SERVICE_AREA_NEW { get; }
        IRepository_CSP<PROCESS_MODEL_PROJECT_CONFIG> PROCESS_MODEL_PROJECT_CONFIG { get; }
        IRepository_CSP<PROCESS_MODEL_PROCESS_MAPPING> PROCESS_MODEL_PROCESS_MAPPING { get; }
        IRepository_CSP<PROCESS_SERVICE_AREA_PROJECT_MAPPING> PROCESS_SERVICE_AREA_PROJECT_MAPPING { get; }
        IRepository_CSP<PROCESS_SERVICE_AREA_MAPPING> PROCESS_SERVICE_AREA_MAPPING { get; }
        IRepository_CSP<PM_PROJECT_SERVICE_AREA_PROCESS_MAPPING> PM_PROJECT_SERVICE_AREA_PROCESS_MAPPING { get; }
        IRepository_CSP<PM_PROCESS_CHECKLIST_MAPPING> PM_PROCESS_CHECKLIST_MAPPING { get; }
        IRepository_CSP<PM_CHECKLIST> PM_CHECKLIST { get; }
        IRepository_CSP<PM_CHECKLIST_QUESTIONS> PM_CHECKLIST_QUESTIONS { get; }

        IRepository_CSP<RISKS_OBJECTIVES_MAPPING> RISKS_OBJECTIVES_MAPPING { get; }
        IRepository_CSP<PROCESS_MODEL_RISKS_NEW> PROCESS_MODEL_RISKS_NEW { get; }
        IRepository_CSP<CONTROL_CATEGORY> CONTROL_CATEGORY { get; }

        IRepository_CSP<PROCESS_OBJECTIVES_MAPPING> PROCESS_OBJECTIVES_MAPPING { get; }

        IRepository_CSP<RISKS_LEVEL1_DETAILS> RISKS_LEVEL1_DETAILS { get; }
        IRepository_CSP<RISKS_LEVEL2_DETAILS> RISKS_LEVEL2_DETAILS { get; }

        IRepository_CSP<RISKS_LEVEL3_DETAILS> RISKS_LEVEL3_DETAILS { get; }

        IRepository_CSP<CSM_TITLES> CSM_TITLES { get; }
        IRepository_CSP<AUDIT_EXECUTION_MODEL> AUDIT_EXECUTION_MODEL { get; }
        IRepository_CSP<AUDIT_EXECUTION_AUDITEE_DETAILS> AUDIT_EXECUTION_AUDITEE_DETAILS { get; }
        IRepository_CSP<EXECUTION_IMPACT_MAPPING> EXECUTION_IMPACT_MAPPING { get; }
        IRepository_CSP<AUDIT_CHECKLIST_PROJECT_EXECUTION> AUDIT_CHECKLIST_PROJECT_EXECUTION { get; }
        IRepository_CSP<AUDIT_CHECKLIST_WEIGHT_NC_TABLE> AUDIT_CHECKLIST_WEIGHT_NC_TABLE { get; }
        IRepository_CSP<AUDIT_CHECKLIST_PROJECT_FINDINGS> AUDIT_CHECKLIST_PROJECT_FINDINGS { get; }
        IRepository_CSP<AUDIT_CHECKLIST_QUESTIONS> AUDIT_CHECKLIST_QUESTIONS { get; }
        IRepository_CSP<AUDIT_CHECKLIST_PROJECT_SAMPLES_AUDITED> AUDIT_CHECKLIST_PROJECT_SAMPLES_AUDITED { get; }
        IRepository_CSP<CHECKLIST_EXECUTION_AUDITEE_DETAILS> CHECKLIST_EXECUTION_AUDITEE_DETAILS { get; }
        IRepository_CSP<PROCESS_MODEL_PROCESS> PROCESS_MODEL_PROCESS { get; }
        IRepository_CSP<AUDIT_CHECKLIST_WEIGHTAGE> AUDIT_CHECKLIST_WEIGHTAGE { get; }
        IRepository_CSP<AUDIT_CHECKLIST_STATUS_MAPPING> AUDIT_CHECKLIST_STATUS_MAPPING { get; }
        IRepository_CSP<GAVS_SERVICE_AREA> GAVS_SERVICE_AREA { get; }
        IRepository_CSP<SUBPROJECT> SUBPROJECT { get; }
        IRepository_CSP<SUBPROJECT_TASK> SUBPROJECT_TASK { get; }
        IRepository_CSP<AUDIT_FINDING_STAGES> AUDIT_FINDING_STAGES { get; }
        IRepository_CSP<AUDIT_FINDING_STAGES_MAPPING> AUDIT_FINDING_STAGES_MAPPING { get; }
        IRepository_CSP<AUDIT_FINDINGS_CAPA> AUDIT_FINDINGS_CAPA { get; }
        IRepository_CSP<AUDIT_FINIDINGS_CAPA_CAUSE_MAPPING> AUDIT_FINIDINGS_CAPA_CAUSE_MAPPING { get; }
        IRepository_CSP<AUDIT_MANAGEMENT_CAUSES> AUDIT_MANAGEMENT_CAUSES { get; }
        IRepository_CSP<AUDIT_MANAGEMENT_ROOTCAUSES> AUDIT_MANAGEMENT_ROOTCAUSES { get; }
        IRepository_CSP<AUDIT_FINDING_CAPA_STATUS_HISTORY> AUDIT_FINDING_CAPA_STATUS_HISTORY { get; }
        IRepository_CSP<AUDIT_FINDING_CAPA_REVIEW> AUDIT_FINDING_CAPA_REVIEW { get; }
        IRepository_CSP<AUDIT_FINDING_CAPA_IMPLEMENTATION> AUDIT_FINDING_CAPA_IMPLEMENTATION { get; }
        IRepository_CSP<AUDIT_FINDING_CAPA_VERIFICATION> AUDIT_FINDING_CAPA_VERIFICATION { get; }
        IRepository_CSP<PROCESS_MODEL_CLAUSES> PROCESS_MODEL_CLAUSES { get; }
        IRepository_CSP<PROCESS_MODEL_QUESTIONS> PROCESS_MODEL_QUESTIONS { get; }
        IRepository_CSP<AUDIT_CHECKLIST_QUESTION_CLAUSES_MAPPING> AUDIT_CHECKLIST_QUESTION_CLAUSES_MAPPING { get; }
        IRepository_CSP<TASK> TASK { get; }
        IRepository_CSP<TASK_CATEGORY> TASK_CATEGORY { get; }
        IRepository_CSP<TASK_RECURRENCE> TASK_RECURRENCE { get; }
        IRepository_CSP<TASK_TYPE> TASK_TYPE { get; }
        IRepository_CSP<EMAIL_LOG> EMAIL_LOG { get; }
        IRepository_CSP<PM_MATURITY_LEVEL> PM_MATURITY_LEVEL { get; }
        IRepository_CSP<PM_MATURITYLEVEL_MAPPING> PM_MATURITYLEVEL_MAPPING { get; }
        IRepository_CSP<AUDIT_CHECKLIST_STATUS_LIST> AUDIT_CHECKLIST_STATUS_LIST { get; }
        IRepository_CSP<AUDIT_CHECKLIST_STATUS_LIST_VALUES> AUDIT_CHECKLIST_STATUS_LIST_VALUES { get; }
        IRepository_CSP<PM_PROCESS_QUESTIONS_MAPPING> PM_PROCESS_QUESTIONS_MAPPING { get; }
        IRepository_CSP<FINDINGSTYPE> FINDINGSTYPE { get; }
        IRepository_CSP<FINDINGSTYPE_VALUES> FINDINGSTYPE_VALUES { get; }
        IRepository_CSP<AUDITEE_ACCEPTANCE> AUDITEE_ACCEPTANCE { get; }

        IRepository_CSP<CUST_REQ_REF> CUST_REQ_REF { get; }
        IRepository_CSP<CUST_REQ_STATUS> CUST_REQ_STATUS { get; }
        IRepository_CSP<CUST_REQ_STAGE_STATUS> CUST_REQ_STAGE_STATUS { get; }
        IRepository_CSP<REQ_CATEGORY> REQ_CATEGORY { get; }
        IRepository_CSP<REQ_CAT_MAPPING> REQ_CAT_MAPPING { get; }
        IRepository_CSP<REQ_LEVEL> REQ_LEVEL { get; }
        IRepository_CSP<REQ_LEVEL_MAPPING> REQ_LEVEL_MAPPING { get; }

        IAppRepository_CSP AppRepo { get; }

        IRepository_CSP<SERVICE_LEVEL_IDENTIFIER_MODEL> SERVICE_LEVEL_IDENTIFIER_MODEL { get; }

        IRepository_CSP<FMEA_Task_Model> FMEA_Task_Model { get; }

        IRepository_CSP<FMEAModel> FMEAModel { get; }
        IRepository_CSP<Failure_Mode_Master> Failure_Mode_Master { get; }
        
        IRepository_CSP<CHECKLIST_SCORES_BY_AUDIT> CHECKLIST_SCORES_BY_AUDIT { get; }

        IRepository_CSP<FMEA_DATA_STAGE2_MODEL> FMEA_DATA_STAGE2_MODEL { get; }

        IRepository_CSP<FMEA_Rating_Factors_Model> FMEA_Rating_Factors_Model { get; }
        IRepository_CSP<CHECKLIST_EXECUTION_CC_DETAILS> CHECKLIST_EXECUTION_CC_DETAILS { get; }

        IRepository_CSP<PROJECT_CONFIGURATION_SETTING> PROJECT_CONFIGURATION_SETTING { get; }

        IRepository_CSP<PROJECT_CONFIGURATION_DATA> PROJECT_CONFIGURATION_DATA { get; }


        IRepository_CSP<TIMEFORMAT_CONFIG> TIMEFORMAT_CONFIG { get; }
        IRepository_CSP<AUDIT_CHECKLIST_EXECUTION_DETAILS> AUDIT_CHECKLIST_EXECUTION_DETAILS { get; }
        IRepository_CSP<AUDIT_CHECKLIST_EXECUTION_SUMMARY> AUDIT_CHECKLIST_EXECUTION_SUMMARY { get; }
        IRepository_CSP<IDEA> IDEA { get; }
        IRepository_CSP<IDEA_STATUS> IDEA_STATUS { get; }
        IRepository_CSP<IDEA_IMPROVEMENT_TYPE> IDEA_IMPROVEMENT_TYPE { get; }
        IRepository_CSP<POTENTIAL_SOLUTION_CATEGORY> POTENTIAL_SOLUTION_CATEGORY { get; }
        IRepository_CSP<BENEFIT_DETAILS_QUANTITATIVE> BENEFIT_DETAILS_QUANTITATIVE { get; }
        IRepository_CSP<IDEA_BENEFIT_SUMMARY> IDEA_BENEFIT_SUMMARY { get; }
        IRepository_CSP<IDEA_CATEGORY_UOM_MAPPING> IDEA_CATEGORY_UOM_MAPPING { get; }
        IRepository_CSP<UOM> UOM { get; }
        IRepository_CSP<IDEA_CATEGORY> IDEA_CATEGORY { get; }
        IRepository_CSP<BENEFIT_DETAILS_QUALITATIVE> BENEFIT_DETAILS_QUALITATIVE { get; }
        IRepository_CSP<IDEA_IMPLEMENTATION_PLAN> IDEA_IMPLEMENTATION_PLAN { get; }
        IRepository_CSP<IDEA_STAGE_STATUS> IDEA_STAGE_STATUS { get; }
        IRepository_CSP<PROJECT_FAILURES_MAPPING> PROJECT_FAILURES_MAPPING { get; }
        IRepository_CSP<FAILURE_ASSESSMENT> FAILURE_ASSESSMENT { get; }

        IRepository_CSP<CONTACT_ROLES> CONTACT_ROLES { get; }

        IRepository_CSP<PRODUCT_MODE_MAPPING> PRODUCT_MODE_MAPPING { get; }

        IRepository_CSP<MODE_KPI_MAPPING> MODE_KPI_MAPPING { get; }
        IRepository_CSP<PRODUCT_TIER> PRODUCT_TIER { get; }

        IRepository_CSP<TIER_LEVEL_MATRIX> TIER_LEVEL_MATRIX { get; }

        IRepository_CSP<PRODUCTS_SERVICE_AREA> PRODUCTS_SERVICE_AREA { get; }

        IRepository_CSP<PRODUCTS_SLA_CATEGORY> PRODUCTS_SLA_CATEGORY { get; }

        IRepository_CSP<PRODUCTS_SERVICE_LEVEL_MODE> PRODUCTS_SERVICE_LEVEL_MODE { get; }

        IRepository_CSP<PRODUCTS_SERVICE_LEVEL_TYPE> PRODUCTS_SERVICE_LEVEL_TYPE { get; }

        IRepository_CSP<PRODUCT_SERVICE_LEVEL_METRICS> PRODUCT_SERVICE_LEVEL_METRICS { get; }        
        IRepository_CSP<REFERENCE_MASTER> REFERENCE_MASTER { get; }

        IRepository_CSP<BASE_MEASURE> BASE_MEASURE { get; }
        IRepository_CSP<SERVICE_LEVEL_MEASUREMENT_2_BASE_MEASURE_CONFIG> SERVICE_LEVEL_MEASUREMENT_2_BASE_MEASURE_CONFIG { get; }
        IRepository_CSP<KPI_BASE_MEASURE_VALUE> KPI_BASE_MEASURE_VALUE { get; }
    
        IRepository_CSP<AUDIT_CHECKLIST_WEIGHTAGE_SCORES> AUDIT_CHECKLIST_WEIGHTAGE_SCORES { get; }
        IRepository_CSP<PRODUCT_RESPONSIBLE> PRODUCT_RESPONSIBLE { get; }

        IRepository_CSP<KPI2PRODUCT_SERVICE_LEVEL_METRICS> KPI2PRODUCT_SERVICE_LEVEL_METRICS { get; }

        IRepository_CSP<PRODUCT_RESPONSIBLE_MANAGEMENT_TYPE> PRODUCT_RESPONSIBLE_MANAGEMENT_TYPE { get; }

        IRepository_CSP<SUPPORT_VALUE_TYPE> SUPPORT_VALUE_TYPE { get; }
        IRepository_CSP<SUPPORT_VALUE_REQUEST> SUPPORT_VALUE_REQUEST { get; }
        IRepository_CSP<BASE_MEASURE_FORMULA_TYPE> BASE_MEASURE_FORMULA_TYPE { get; }
        IRepository_CSP<CUSTOMER_CAPA_APPROVAL> CUSTOMER_CAPA_APPROVAL { get; }
        IRepository_CSP<CUSTOMER_CAPA_APPROVAL_STATUS> CUSTOMER_CAPA_APPROVAL_STATUS { get; }
        IRepository_CSP<SLA_REJECTION> SLA_REJECTION { get; }
        IRepository_CSP<SLA_REJECTION_KPI_DETAILS> SLA_REJECTION_KPI_DETAILS { get; }
        IRepository_CSP<SLA_REJECTION_STATUS_HISTORY> SLA_REJECTION_STATUS_HISTORY { get; }
        IRepository_CSP<SLA_REJECTION_STATUS> SLA_REJECTION_STATUS { get; }
        IRepository_CSP<TASK_STATUS_HISTORY> TASK_STATUS_HISTORY { get; }

        IRepository_CSP<APPRECIATION> APPRECIATION { get; }        
        IRepository_CSP<PROJECT_INSCOPE_DETAILS> PROJECT_INSCOPE_DETAILS { get; }
        IRepository_CSP<CSS_QUESTION_MODELS> CSS_QUESTION_MODELS { get; }

        IRepository_CSP<ACCESS_REQUEST> ACCESS_REQUEST { get; }

        IRepository_CSP<PROJECT_SCOPE_VALUES> PROJECT_SCOPE_VALUES { get; }

        IRepository_CSP<INTEGRATION_REQUEST_DATA> INTEGRATION_REQUEST_DATA { get; }
    }
}
