
USE BAS
GO
IF NOT EXISTS(select 1 from CONFIGURATION_EXT where [KEY]='KPI_WITH_ZEROTARGET')
BEGIN
INSERT INTO BAS..CONFIGURATION_EXT VALUES('KPI_WITH_ZEROTARGET','System Uptime',-1,NULL,NULL,0,1,NULL,NULL)
END
IF NOT EXISTS(select 1 from CONFIGURATION_EXT where [KEY]='LESS_THAN_MINTARGET')
BEGIN
INSERT INTO BAS..CONFIGURATION_EXT VALUES('LESS_THAN_MINTARGET','Issues detected post-go-live,Re-opened defects before GoLive',-1,NULL,NULL,0,1,NULL,NULL)
END
IF NOT EXISTS(select 1 from CONFIGURATION_EXT where [KEY]='10%_OF_BASELINE')
BEGIN
INSERT INTO BAS..CONFIGURATION_EXT VALUES('10%_OF_BASELINE','Process Efficiency',-1,NULL,NULL,0,1,NULL,NULL)
END
GO