USE BAS
GO
--drop cONSTRAINTS
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='BU_HEAD_EMP_ID_FK')  BEGIN ALTER TABLE BU_INFO  DROP CONSTRAINT BU_HEAD_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='DEPT_INFO_EMP_ID_FK')  BEGIN ALTER TABLE DEPT_INFO  DROP CONSTRAINT DEPT_INFO_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='EMP_DEPARTMENT_EMP_ID_FK')  BEGIN ALTER TABLE EMP_DEPARTMENT  DROP CONSTRAINT EMP_DEPARTMENT_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='EMP_ID_FK')  BEGIN ALTER TABLE EMP_PASSPORT  DROP CONSTRAINT EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='EMP_ID_PROJECT_EXPENSE_FK')  BEGIN ALTER TABLE PROJECT_EXPENSE  DROP CONSTRAINT EMP_ID_PROJECT_EXPENSE_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='RESRC_MANAGER_EMP_ID_FK')  BEGIN ALTER TABLE RESRC_RQST  DROP CONSTRAINT RESRC_MANAGER_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='RESRC_REVIEWER_EMP_ID_FK')  BEGIN ALTER TABLE RESRC_RQST  DROP CONSTRAINT RESRC_REVIEWER_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='RESRC_RQST_WF_STAGE_OWNER_EMP_ID_FK')  BEGIN ALTER TABLE RESRC_RQST_WF  DROP CONSTRAINT RESRC_RQST_WF_STAGE_OWNER_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='RESRC_RQST_WF_TAG_EMP_ID_FK')  BEGIN ALTER TABLE RESRC_RQST_WF  DROP CONSTRAINT RESRC_RQST_WF_TAG_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJECT_NEW_PROJ_BU_EMP_ID_FK')  BEGIN ALTER TABLE PROJECT_NEW  DROP CONSTRAINT PROJECT_NEW_PROJ_BU_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJECT_NEW_PROJ_DM_EMP_ID_FK')  BEGIN ALTER TABLE PROJECT_NEW  DROP CONSTRAINT PROJECT_NEW_PROJ_DM_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJECT_PROJ_AM_EMP_ID_FK')  BEGIN ALTER TABLE PROJECT  DROP CONSTRAINT PROJECT_PROJ_AM_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJECT_PROJ_BUHEAD_EMP_ID_FK')  BEGIN ALTER TABLE PROJECT  DROP CONSTRAINT PROJECT_PROJ_BUHEAD_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJECT_PROJ_DM_EMP_ID_FK')  BEGIN ALTER TABLE PROJECT  DROP CONSTRAINT PROJECT_PROJ_DM_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJECT_PROJ_PM_EMP_ID_FK')  BEGIN ALTER TABLE PROJECT  DROP CONSTRAINT PROJECT_PROJ_PM_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_RESOURCE_PROJ_RM_EMP_ID_FK')  BEGIN ALTER TABLE PROJ_RESOURCE  DROP CONSTRAINT PROJ_RESOURCE_PROJ_RM_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_RESRC_TIME_ENTRY_EMP_ID_FK_2')  BEGIN ALTER TABLE PROJ_RESRC_TIME_ENTRY  DROP CONSTRAINT PROJ_RESRC_TIME_ENTRY_EMP_ID_FK_2; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_REVIEWER_EMP_ID_FK')  BEGIN ALTER TABLE PROJ_RESOURCE  DROP CONSTRAINT PROJ_REVIEWER_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_RM_EMP_ID_FK')  BEGIN ALTER TABLE PROJ_RESOURCE  DROP CONSTRAINT PROJ_RM_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_RP_EMP_ID_FK')  BEGIN ALTER TABLE PROJ_RESOURCE  DROP CONSTRAINT PROJ_RP_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_TIMESHEET_UPLD_EMP_ID_FK')  BEGIN ALTER TABLE PROJ_TIMESHEET  DROP CONSTRAINT PROJ_TIMESHEET_UPLD_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='EMP_INFO_MANAGER_EMP_ID_FK')  BEGIN ALTER TABLE EMP_INFO  DROP CONSTRAINT EMP_INFO_MANAGER_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='EMP_INFO_REVIEWER_EMP_ID_FK')  BEGIN ALTER TABLE EMP_INFO  DROP CONSTRAINT EMP_INFO_REVIEWER_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='EMP_SKILLSET_MATRIX_EMP_ID_FK')  BEGIN ALTER TABLE EMP_SKILLSET_MATRIX  DROP CONSTRAINT EMP_SKILLSET_MATRIX_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_RESOURCE_EMPID_FK')  BEGIN ALTER TABLE PROJ_RESOURCE  DROP CONSTRAINT PROJ_RESOURCE_EMPID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_RESOURCE_PROJ_REVIEWER_EMP_ID_FK')  BEGIN ALTER TABLE PROJ_RESOURCE  DROP CONSTRAINT PROJ_RESOURCE_PROJ_REVIEWER_EMP_ID_FK; END
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='PK_COMPLIANCE_TRAINING_ASSESSMENT_RESULT2')  BEGIN ALTER TABLE COMPLIANCE_TRAINING_ASSESSMENT_RESULT  DROP CONSTRAINT PK_COMPLIANCE_TRAINING_ASSESSMENT_RESULT2; END 
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='EMP_DEPARTMENT_PK')  BEGIN ALTER TABLE EMP_DEPARTMENT  DROP CONSTRAINT EMP_DEPARTMENT_PK; END 
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME ='EMP_INFO_PK')  BEGIN ALTER TABLE EMP_INFO  DROP CONSTRAINT EMP_INFO_PK; END 



--drop INDEX
IF EXISTS(SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[dbo].[PROJ_RESRC_TIME_ENTRY]') AND name='proj_resrc_time_entry_idx')       BEGIN  DROP INDEX [dbo].[PROJ_RESRC_TIME_ENTRY].proj_resrc_time_entry_idx; END
IF EXISTS(SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[dbo].[EMP_DEPARTMENT]') AND name='EMP_DEPARTMENT_PK')       BEGIN  DROP INDEX [dbo].[EMP_DEPARTMENT].EMP_DEPARTMENT_PK; END
IF EXISTS(SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[dbo].[EMP_INFO]') AND name='EMP_INFO_PK')       BEGIN  DROP INDEX [dbo].[EMP_INFO].EMP_INFO_PK; END
IF EXISTS(SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[dbo].[COMPLIANCE_TRAINING_ASSESSMENT_RESULT]') AND name='PK_COMPLIANCE_TRAINING_ASSESSMENT_RESULT2')       BEGIN  DROP INDEX [dbo].[COMPLIANCE_TRAINING_ASSESSMENT_RESULT].PK_COMPLIANCE_TRAINING_ASSESSMENT_RESULT2; END



--sP_help Emp_info

-- aLTER TABLE SCRTIPTS
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='EMP_INFO' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE EMP_INFO  ALTER COLUMN EMP_ID varchar(50) NOT NULL;  END
--IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='Master$' AND name='Employee Id' AND system_type_id IN (56)) BEGIN ALTER TABLE Master$  ALTER COLUMN [Employee Id] varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJMGT_TEAM' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJMGT_TEAM  ALTER COLUMN EMP_ID varchar(50);  END
--IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='tmpEmpSkill' AND name='Employee Id' AND system_type_id IN (56)) BEGIN ALTER TABLE tmpEmpSkill  ALTER COLUMN Employee Id varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT' AND name='QUALITY_SPOC' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT  ALTER COLUMN QUALITY_SPOC varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='EMP_INFO_FOR_CUSTOMER' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE EMP_INFO_FOR_CUSTOMER  ALTER COLUMN EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJ_TIMESHEET' AND name='UPLD_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJ_TIMESHEET  ALTER COLUMN UPLD_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT' AND name='LVL_1_APPR_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT  ALTER COLUMN LVL_1_APPR_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT' AND name='LVL_2_APPR_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT  ALTER COLUMN LVL_2_APPR_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT' AND name='LVL_3_APPR_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT  ALTER COLUMN LVL_3_APPR_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT' AND name='LVL_4_APPR_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT  ALTER COLUMN LVL_4_APPR_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT' AND name='PROJ_BUHEAD_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT  ALTER COLUMN PROJ_BUHEAD_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT' AND name='PROJ_DM_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT  ALTER COLUMN PROJ_DM_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT' AND name='PROJ_PM_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT  ALTER COLUMN PROJ_PM_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT' AND name='PROJ_AM_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT  ALTER COLUMN PROJ_AM_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='BU_INFO' AND name='BU_HEAD_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE BU_INFO  ALTER COLUMN BU_HEAD_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT_EXPENSE' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT_EXPENSE  ALTER COLUMN EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='RESRC_RQST' AND name='RESRC_MANAGER_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE RESRC_RQST  ALTER COLUMN RESRC_MANAGER_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='RESRC_RQST' AND name='RESRC_REVIEWER_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE RESRC_RQST  ALTER COLUMN RESRC_REVIEWER_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='RESRC_RQST' AND name='REPLACEMENT_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE RESRC_RQST  ALTER COLUMN REPLACEMENT_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='RESRC_RQST_WF' AND name='STAGE_OWNER_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE RESRC_RQST_WF  ALTER COLUMN STAGE_OWNER_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='RESRC_RQST_WF' AND name='TAG_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE RESRC_RQST_WF  ALTER COLUMN TAG_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT_NEW' AND name='PROJ_DM_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT_NEW  ALTER COLUMN PROJ_DM_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJECT_NEW' AND name='PROJ_BU_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJECT_NEW  ALTER COLUMN PROJ_BU_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJ_RESRC_TIME_ENTRY' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJ_RESRC_TIME_ENTRY  ALTER COLUMN EMP_ID varchar(50);  END
--IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='Master$_20170513' AND name='Employee Id' AND system_type_id IN (56)) BEGIN ALTER TABLE Master$_20170513  ALTER COLUMN Employee Id varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='DEPT_BU_INFO' AND name='PROJ_BUHEAD_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE DEPT_BU_INFO  ALTER COLUMN PROJ_BUHEAD_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='DEPT_BU_INFO' AND name='DEPT_HEAD_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE DEPT_BU_INFO  ALTER COLUMN DEPT_HEAD_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='DEPT_INFO' AND name='DEPT_HEAD_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE DEPT_INFO  ALTER COLUMN DEPT_HEAD_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='proj_resrc_time_entry_copy' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE proj_resrc_time_entry_copy  ALTER COLUMN EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJ_RESOURCE_temp' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJ_RESOURCE_temp  ALTER COLUMN EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJ_RESOURCE_temp' AND name='PROJ_RM_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJ_RESOURCE_temp  ALTER COLUMN PROJ_RM_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJ_RESOURCE_temp' AND name='PROJ_REVIEWER_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJ_RESOURCE_temp  ALTER COLUMN PROJ_REVIEWER_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='EMP_DEPARTMENT' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE EMP_DEPARTMENT  ALTER COLUMN EMP_ID varchar(50) NOT NULL;  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='EMP_INFO' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE EMP_INFO  ALTER COLUMN EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='EMP_INFO' AND name='MANAGER_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE EMP_INFO  ALTER COLUMN MANAGER_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='EMP_INFO' AND name='REVIEWER_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE EMP_INFO  ALTER COLUMN REVIEWER_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='EMP_PASSPORT' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE EMP_PASSPORT  ALTER COLUMN EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='EMP_SECONDARY_SKILL$' AND name='emp_id' AND system_type_id IN (56)) BEGIN ALTER TABLE EMP_SECONDARY_SKILL$  ALTER COLUMN emp_id varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='EMP_SKILLSET_MATRIX' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE EMP_SKILLSET_MATRIX  ALTER COLUMN EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='COMPLIANCE_TRAINING_ASSESSMENT_RESULT' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE COMPLIANCE_TRAINING_ASSESSMENT_RESULT  ALTER COLUMN EMP_ID varchar(50)  NOT NULL;  END
--IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='Master_Data' AND name='Employee Id' AND system_type_id IN (56)) BEGIN ALTER TABLE Master_Data  ALTER COLUMN Employee Id varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJ_RESOURCE' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJ_RESOURCE  ALTER COLUMN EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJ_RESOURCE' AND name='PROJ_RM_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJ_RESOURCE  ALTER COLUMN PROJ_RM_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJ_RESOURCE' AND name='PROJ_REVIEWER_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJ_RESOURCE  ALTER COLUMN PROJ_REVIEWER_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROCESS_MODEL_AUDITOR' AND name='emp_id' AND system_type_id IN (56)) BEGIN ALTER TABLE PROCESS_MODEL_AUDITOR  ALTER COLUMN emp_id varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROCESS_MODEL_AUDITOR' AND name='created_by' AND system_type_id IN (56)) BEGIN ALTER TABLE PROCESS_MODEL_AUDITOR  ALTER COLUMN created_by varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROCESS_MODEL_AUDITOR' AND name='UPDATED_BY' AND system_type_id IN (56)) BEGIN ALTER TABLE PROCESS_MODEL_AUDITOR  ALTER COLUMN UPDATED_BY varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='AUDITOR_QUALIFIED_STANDARDS' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE AUDITOR_QUALIFIED_STANDARDS  ALTER COLUMN EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='AUDITOR_QUALIFIED_STANDARDS' AND name='created_by' AND system_type_id IN (56)) BEGIN ALTER TABLE AUDITOR_QUALIFIED_STANDARDS  ALTER COLUMN created_by varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='AUDITOR_QUALIFIED_STANDARDS' AND name='UPDATED_BY' AND system_type_id IN (56)) BEGIN ALTER TABLE AUDITOR_QUALIFIED_STANDARDS  ALTER COLUMN UPDATED_BY varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='emp_info_copy' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE emp_info_copy  ALTER COLUMN EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='emp_info_copy' AND name='MANAGER_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE emp_info_copy  ALTER COLUMN MANAGER_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='emp_info_copy' AND name='REVIEWER_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE emp_info_copy  ALTER COLUMN REVIEWER_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='emp_info_final' AND name='EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE emp_info_final  ALTER COLUMN EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='emp_info_final' AND name='MANAGER_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE emp_info_final  ALTER COLUMN MANAGER_EMP_ID varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='emp_info_final' AND name='REVIEWER_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE emp_info_final  ALTER COLUMN REVIEWER_EMP_ID varchar(50);  END
--IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='Sheet1$' AND name='DM emp Id' AND system_type_id IN (56)) BEGIN ALTER TABLE Sheet1$  ALTER COLUMN DM emp Id varchar(50);  END
IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='PROJ_REV_APPRL_WF' AND name='APPR_EMP_ID' AND system_type_id IN (56)) BEGIN ALTER TABLE PROJ_REV_APPRL_WF  ALTER COLUMN APPR_EMP_ID varchar(50);  END
--IF EXISTS(SELECT 1 FROM sys.columns WHERE OBJECT_NAME(object_id) ='Master$_20170521' AND name='Employee Id' AND system_type_id IN (56)) BEGIN ALTER TABLE Master$_20170521  ALTER COLUMN Employee Id varchar(50);  END







--cREATE CONSTRAINTS
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME='EMP_INFO' AND CONSTRAINT_NAME ='EMP_INFO_PK')  BEGIN ALTER TABLE EMP_INFO  ADD CONSTRAINT EMP_INFO_PK PRIMARY KEY (EMP_ID);  END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME='EMP_DEPARTMENT' AND CONSTRAINT_NAME ='EMP_DEPARTMENT_PK')  BEGIN ALTER TABLE EMP_DEPARTMENT  ADD CONSTRAINT EMP_DEPARTMENT_PK PRIMARY KEY ([EMP_ID] ASC,	[DEPT_ID] ASC);  END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME='COMPLIANCE_TRAINING_ASSESSMENT_RESULT' AND CONSTRAINT_NAME ='PK_COMPLIANCE_TRAINING_ASSESSMENT_RESULT2')  BEGIN ALTER TABLE COMPLIANCE_TRAINING_ASSESSMENT_RESULT  ADD CONSTRAINT PK_COMPLIANCE_TRAINING_ASSESSMENT_RESULT2 PRIMARY KEY ([TITLE_ID] ASC,	[EMP_ID] ASC,	[DATE_OF_COMPLETION] ASC,	[RESULT] ASC);  END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='BU_HEAD_EMP_ID_FK')  BEGIN ALTER TABLE BU_INFO  ADD CONSTRAINT BU_HEAD_EMP_ID_FK  FOREIGN KEY (BU_HEAD_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='DEPT_INFO_EMP_ID_FK')  BEGIN ALTER TABLE DEPT_INFO  ADD CONSTRAINT DEPT_INFO_EMP_ID_FK  FOREIGN KEY (DEPT_HEAD_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='EMP_DEPARTMENT_EMP_ID_FK')  BEGIN ALTER TABLE EMP_DEPARTMENT  ADD CONSTRAINT EMP_DEPARTMENT_EMP_ID_FK  FOREIGN KEY (EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='EMP_ID_FK')  BEGIN ALTER TABLE EMP_PASSPORT  ADD CONSTRAINT EMP_ID_FK  FOREIGN KEY (EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='EMP_ID_PROJECT_EXPENSE_FK')  BEGIN ALTER TABLE PROJECT_EXPENSE  ADD CONSTRAINT EMP_ID_PROJECT_EXPENSE_FK  FOREIGN KEY (EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='RESRC_MANAGER_EMP_ID_FK')  BEGIN ALTER TABLE RESRC_RQST  ADD CONSTRAINT RESRC_MANAGER_EMP_ID_FK  FOREIGN KEY (RESRC_MANAGER_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='RESRC_REVIEWER_EMP_ID_FK')  BEGIN ALTER TABLE RESRC_RQST  ADD CONSTRAINT RESRC_REVIEWER_EMP_ID_FK  FOREIGN KEY (RESRC_REVIEWER_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='RESRC_RQST_WF_STAGE_OWNER_EMP_ID_FK')  BEGIN ALTER TABLE RESRC_RQST_WF  ADD CONSTRAINT RESRC_RQST_WF_STAGE_OWNER_EMP_ID_FK  FOREIGN KEY (STAGE_OWNER_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='RESRC_RQST_WF_TAG_EMP_ID_FK')  BEGIN ALTER TABLE RESRC_RQST_WF  ADD CONSTRAINT RESRC_RQST_WF_TAG_EMP_ID_FK  FOREIGN KEY (TAG_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJECT_NEW_PROJ_BU_EMP_ID_FK')  BEGIN ALTER TABLE PROJECT_NEW  ADD CONSTRAINT PROJECT_NEW_PROJ_BU_EMP_ID_FK  FOREIGN KEY (PROJ_BU_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJECT_NEW_PROJ_DM_EMP_ID_FK')  BEGIN ALTER TABLE PROJECT_NEW  ADD CONSTRAINT PROJECT_NEW_PROJ_DM_EMP_ID_FK  FOREIGN KEY (PROJ_DM_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJECT_PROJ_AM_EMP_ID_FK')  BEGIN ALTER TABLE PROJECT  ADD CONSTRAINT PROJECT_PROJ_AM_EMP_ID_FK  FOREIGN KEY (PROJ_AM_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJECT_PROJ_BUHEAD_EMP_ID_FK')  BEGIN ALTER TABLE PROJECT  ADD CONSTRAINT PROJECT_PROJ_BUHEAD_EMP_ID_FK  FOREIGN KEY (PROJ_BUHEAD_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJECT_PROJ_DM_EMP_ID_FK')  BEGIN ALTER TABLE PROJECT  ADD CONSTRAINT PROJECT_PROJ_DM_EMP_ID_FK  FOREIGN KEY (PROJ_DM_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJECT_PROJ_PM_EMP_ID_FK')  BEGIN ALTER TABLE PROJECT  ADD CONSTRAINT PROJECT_PROJ_PM_EMP_ID_FK  FOREIGN KEY (PROJ_PM_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_RESOURCE_PROJ_RM_EMP_ID_FK')  BEGIN ALTER TABLE PROJ_RESOURCE  ADD CONSTRAINT PROJ_RESOURCE_PROJ_RM_EMP_ID_FK  FOREIGN KEY (PROJ_RM_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_RESRC_TIME_ENTRY_EMP_ID_FK_2')  BEGIN ALTER TABLE PROJ_RESRC_TIME_ENTRY  ADD CONSTRAINT PROJ_RESRC_TIME_ENTRY_EMP_ID_FK_2  FOREIGN KEY (EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_REVIEWER_EMP_ID_FK')  BEGIN ALTER TABLE PROJ_RESOURCE  ADD CONSTRAINT PROJ_REVIEWER_EMP_ID_FK  FOREIGN KEY (PROJ_REVIEWER_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_RM_EMP_ID_FK')  BEGIN ALTER TABLE PROJ_RESOURCE  ADD CONSTRAINT PROJ_RM_EMP_ID_FK  FOREIGN KEY (PROJ_RM_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_RP_EMP_ID_FK')  BEGIN ALTER TABLE PROJ_RESOURCE  ADD CONSTRAINT PROJ_RP_EMP_ID_FK  FOREIGN KEY (PROJ_REVIEWER_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_TIMESHEET_UPLD_EMP_ID_FK')  BEGIN ALTER TABLE PROJ_TIMESHEET  ADD CONSTRAINT PROJ_TIMESHEET_UPLD_EMP_ID_FK  FOREIGN KEY (UPLD_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='EMP_INFO_MANAGER_EMP_ID_FK')  BEGIN ALTER TABLE EMP_INFO  ADD CONSTRAINT EMP_INFO_MANAGER_EMP_ID_FK  FOREIGN KEY (MANAGER_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='EMP_INFO_REVIEWER_EMP_ID_FK')  BEGIN ALTER TABLE EMP_INFO  ADD CONSTRAINT EMP_INFO_REVIEWER_EMP_ID_FK  FOREIGN KEY (REVIEWER_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='EMP_SKILLSET_MATRIX_EMP_ID_FK')  BEGIN ALTER TABLE EMP_SKILLSET_MATRIX  ADD CONSTRAINT EMP_SKILLSET_MATRIX_EMP_ID_FK  FOREIGN KEY (EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_RESOURCE_EMPID_FK')  BEGIN ALTER TABLE PROJ_RESOURCE  ADD CONSTRAINT PROJ_RESOURCE_EMPID_FK  FOREIGN KEY (EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END
IF NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_NAME ='PROJ_RESOURCE_PROJ_REVIEWER_EMP_ID_FK')  BEGIN ALTER TABLE PROJ_RESOURCE  ADD CONSTRAINT PROJ_RESOURCE_PROJ_REVIEWER_EMP_ID_FK  FOREIGN KEY (PROJ_REVIEWER_EMP_ID) REFERENCES EMP_INFO(EMP_ID) ; END





--create index
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[dbo].[PROJ_RESRC_TIME_ENTRY]') AND name='proj_resrc_time_entry_idx')       BEGIN CREATE INDEX proj_resrc_time_entry_idx ON [dbo].[PROJ_RESRC_TIME_ENTRY]([PROJ_ID], [EMP_ID], [DATE_ID]); END
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[dbo].[EMP_DEPARTMENT]') AND name='EMP_DEPARTMENT_PK')       BEGIN CREATE INDEX EMP_DEPARTMENT_PK ON [dbo].[EMP_DEPARTMENT]([EMP_ID], [DEPT_ID]); END
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[dbo].[EMP_INFO]') AND name='EMP_INFO_PK')       BEGIN CREATE INDEX EMP_INFO_PK ON [dbo].[EMP_INFO]([EMP_ID]); END
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('[dbo].[COMPLIANCE_TRAINING_ASSESSMENT_RESULT]') AND name='PK_COMPLIANCE_TRAINING_ASSESSMENT_RESULT2')       BEGIN CREATE INDEX PK_COMPLIANCE_TRAINING_ASSESSMENT_RESULT2 ON [dbo].[COMPLIANCE_TRAINING_ASSESSMENT_RESULT]([TITLE_ID], [EMP_ID], [DATE_OF_COMPLETION], [RESULT]); END