IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='get_RiskDetailsByCustomerId' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[get_RiskDetailsByCustomerId]
END
GO

CREATE PROCEDURE [dbo].[get_RiskDetailsByCustomerId]                  
                
@PROJIDS VARCHAR(MAX),                
@allproj bit      
  
AS                  

BEGIN   

SELECT * FROM (
    SELECT R.[ID], C.CUST_ID, C.CUST_NM, R.[PROJECT_ID], PORT.ID PORTFOLIO_ID, PORT.TITLE PORTFOLIO_NM,
           P.PROJ_NM, R.[RAG], R.[DESCRIPTION], [IMPACT], [PROBABILITY_SCALE], [IMPACT_SCALE], R.[RISK_RATING], 
		   R.[RISK_CATEGORY], R.[LOCATION], R.[RISK_LEVEL], R.[NEW_CONSEQUENCES_SCALE], R.[NEW_LIKELIHOOD_SCALE],
		   R.[NEW_RISK_RATING], R.[NEW_RISK_LEVEL],
           R.[OWNER], [AREA], [IDENTIFIED_BY], R.[IDENTIFIED_DATE], [RISK_TREATMENT_STRATEGY],
           R.[TARGET_DATE], [ACTUAL_DATE], R.[STATUS], [ACTION_TAKEN], R.[CREATED_BY], R.[CREATED_DATE],
           R.[UPDATED_BY], R.[UPDATED_DATE], R.[ISACTIVE], R.[RISK_REPOSITORY_ID], R.[IS_DRAFT],
           ISNULL(E.FRST_NM, R.[OWNER]) AS OWNER_NAME, R.ACCEPT_TILL,
           CAST(CASE WHEN PA.RISK_ID IS NOT NULL THEN 1 ELSE 0 END AS BIT) AS IS_PLAN_EXISTS,
           PA.ID AS ACTION_ITEM_ID, PA.DESCRIPTION AS ACTION_ITEM_DESCRIPTION,
           PA.OWNER AS ACTION_ITEM_OWNER, PA.IDENTIFIED_DATE AS ACTION_ITEM_IDENTIFIED_DATE,
           PA.TARGET_DATE AS ACTION_ITEM_TARGET_DATE, PA.STATUS AS ACTION_ITEM_STATUS,
           PA.COMPLETION_DATE AS ACTION_ITEM_COMPLETION_DATE, PA.COMMENTS as ACTION_ITEM_COMMENTS,
		   PA.NEW_RISK_ASSESSMENT_DATE, PA.RISK_TREATMENT_EFFECTIVENESS_STATUS, PA.RISK_TREATMENT_EFFECTIVENESS_VERIFIED_BY,
		   PA.RISK_TREATMENT_EFFECTIVENESS_VERIFIED_DATE,
           ROW_NUMBER() OVER (PARTITION BY R.[ID] ORDER BY R.IDENTIFIED_DATE DESC) AS RowNumber

    FROM PROJECT_RISK R (NOLOCK)
    INNER JOIN PROJECT P (NOLOCK) ON R.PROJECT_ID = P.PROJ_ID
        AND P.PROJ_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS, ','))
        AND R.ISACTIVE = 1
    INNER JOIN CUSTOMER C (NOLOCK) ON C.CUST_ID = P.CUST_ID
    LEFT JOIN EMP_INFO E (NOLOCK) ON R.OWNER = CONVERT(VARCHAR, E.EMAIL_ID)
        OR R.OWNER = CONVERT(VARCHAR, E.EMP_ID)
    LEFT OUTER JOIN PORTFOLIO_PROJECT PP (NOLOCK) ON PP.PROJ_ID = P.PROJ_ID
    LEFT OUTER JOIN PORTFOLIO PORT (NOLOCK) ON PORT.ID = PP.PORTFOLIO_ID
    LEFT JOIN PROJECT_ACTIONITEM PA (NOLOCK) ON PA.RISK_ID = R.ID AND PA.PROJECT_ID = R.PROJECT_ID
) AS Subquery
WHERE RowNumber = 1
ORDER BY IDENTIFIED_DATE DESC;
                  
END       
GO
