IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getAllMappedProcessByProcessModel' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[getAllMappedProcessByProcessModel]
END
GO

CREATE PROCEDURE [dbo].[getAllMappedProcessByProcessModel]      
 
 as      
 begin      

SELECT 
    ML.ID AS PROCESS_MODEL_ID, 
    ML.TITLE AS PROCESS_MODEL_NAME, 
    PA.TITLE AS PROCESS_AREA, 
    PA.ID AS PROCESS_AREA_ID,      
    P.ID AS PROCESS_ID,      
    P.TITLE AS PROCESS_TITLE, 
    P.DESCRIPTION AS PROCESS_DESCRIPTION, 
    STRING_AGG(PMR.ID, ',') AS REFERENCE_COLUMN  
FROM 
    PROCESS P 
INNER JOIN 
    PROCESS_MODEL_PROCESS_MAPPING MP ON P.ID = MP.PROCESS_ID 
INNER JOIN 
    PROCESS_MODEL ML ON MP.PROCESS_MODEL_ID = ML.ID       
INNER JOIN 
    PROCESS_AREA PA ON P.PROCESS_AREA_ID = PA.ID  
LEFT JOIN
    PROCESS_AREA_MODEL_REFERENCE PAR ON PAR.PROCESS_ID = P.ID
LEFT JOIN
    PROCESS_MODEL_REFERENCE PMR ON PMR.ID = PAR.PROCESS_MODEL_REFERENCE_ID
WHERE 
    MP.ISACTIVE = 1 AND ML.ISACTIVE = 1 AND PA.ISACTIVE = 1 AND P.SHOW_IN_MASTER = 1 AND P.ISACTIVE=1
	AND (PMR.ISACTIVE = 1 OR PMR.ID IS NULL) AND (PAR.ISACTIVE = 1 OR PAR.ID IS NULL)  
GROUP BY
    ML.ID, ML.TITLE, PA.TITLE, PA.ID, P.ID, P.TITLE, P.DESCRIPTION
ORDER BY  
    ML.TITLE, PA.TITLE, P.TITLE

End
Go