USE BAS
GO

IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getKPIDetails' AND TYPE='P')
BEGIN
DROP PROCEDURE getKPIDetails          
END
GO
      --[getKPIDetails] '06/01/2022','06/30/2022','202P000133-03'
CREATE PROCEDURE [dbo].[getKPIDetails]            
@START_DATE datetime,            
@END_DATE datetime,
@ProjIds VARCHAR(MAX)   =NULL
AS            
BEGIN            
SELECT KD.[ID],KD.[KPI_ID],KD.[PERIOD], MONTH(KD.[PERIOD]) AS MONTH_VAL, CONVERT(CHAR(3), KD.[PERIOD], 0) AS MONTH_NM            
 ,YEAR(KD.[PERIOD]) AS YEAR            
 ,DATEFROMPARTS(YEAR(KD.[PERIOD]), MONTH(KD.[PERIOD]), 1) AS MONTH_YEAR            
 ,K.[KPI_NAME], K.[PRIORITY], K.[SUPPORT_WINDOW]            
 ,KD.[PERIOD_TYPE],KD.[KPI_ACTUAL],KD.[KPI_METRIC],KD.[HIGHLIGHTS],KD.[CREATED_BY],KD.[CREATED_DATE],KD.[UPDATED_BY],KD.[UPDATED_DATE],KD.[ISACTIVE],KD.[ISFLAG]            
 ,K.CUSTOMER_ID, C.CUST_NM CUSTOMER_NM, K.PROJECT_ID, P.PROJ_NM PROJECT_NM, K.GOAL_ID            
 ,K.GLOBAL_KPI_CATEGORY_ID            
 ,GKC.SHORT_DESC GLOBAL_KPI_CATEGORY_NM            
 ,(SELECT GLOBAL_PERSPECTIVE_ID FROM GLOBAL_PERSPECTIVE_KPI_CATEGORY_MAPPING  (NOLOCK) WHERE GLOBAL_KPI_CATEGORY_ID = K.GLOBAL_KPI_CATEGORY_ID AND GLOBAL_PERSPECTIVE_ID IN (SELECT ID FROM GLOBAL_PERSPECTIVE  (NOLOCK) WHERE GROUP_CODE = 'KPI')) as GLOBAL_KPI_PERSPECTIVE_ID   
  
    
      
        
          
            
 ,IS_SOW_COMMITMENT, K.SERVICE_AREA,            
 K.SLA_TARGET_UNIT_OF_MEASUREMENT            
,(SELECT top 1 SLA_TARGET_VERYHIGH_VALUE FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_VERYHIGH_VALUE               
,(SELECT top 1 SLA_TARGET_VERYHIGH_OPERATOR FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_VERYHIGH_OPERATOR            
,(SELECT top 1 SLA_TARGET_VERYHIGH_DESCRIPTION FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_VERYHIGH_DESCRIPTION               
,(SELECT top 1 SLA_TARGET_HIGH_VALUE FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_HIGH_VALUE              
,(SELECT top 1 SLA_TARGET_HIGH_OPERATOR FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_HIGH_OPERATOR            
,(SELECT top 1 SLA_TARGET_HIGH_DESCRIPTION FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_HIGH_DESCRIPTION            
,(SELECT top 1 SLA_TARGET_MEDIUM_VALUE FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_MEDIUM_VALUE               
,(SELECT top 1 SLA_TARGET_MEDIUM_OPERATOR FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_MEDIUM_OPERATOR            
,(SELECT top 1 SLA_TARGET_MEDIUM_DESCRIPTION FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_MEDIUM_DESCRIPTION            
,(SELECT top 1 SLA_TARGET_LOW_VALUE FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_LOW_VALUE               
,(SELECT top 1 SLA_TARGET_LOW_OPERATOR FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_LOW_OPERATOR            
,(SELECT top 1 SLA_TARGET_LOW_DESCRIPTION FROM KPI_TARGETS  (NOLOCK) WHERE KD.PERIOD >= START_DATE AND KD.PERIOD <= END_DATE AND KPI_ID = KD.KPI_ID) as SLA_TARGET_LOW_DESCRIPTION            
            
FROM KPI_DETAILS KD  (NOLOCK)            
            
INNER JOIN KPI K (NOLOCK) ON K.ID = KD.KPI_ID AND K.ISACTIVE = 1    
INNER JOIN KPI_GOALS GOALS  (NOLOCK) ON GOALS.ID = K.GOAL_ID AND GOALS.ISACTIVE = 1     
INNER JOIN PROJECT P  (NOLOCK) ON P.PROJ_ID = K.PROJECT_ID             
INNER JOIN CUSTOMER C  (NOLOCK) ON C.CUST_ID = K.CUSTOMER_ID             
INNER JOIN GLOBAL_KPI_CATEGORY GKC (NOLOCK)  ON K.GLOBAL_KPI_CATEGORY_ID = GKC.ID            
WHERE PERIOD BETWEEN @START_DATE AND @END_DATE AND KD.ISFLAG=0  AND KD.ISACTIVE =1  and isnull(p.PROJ_STATUS,'') != 'Close' 
AND (ISNULL(@PROJIDS,'')='' OR K.PROJECT_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJIDS,',')))
ORDER BY C.CUST_NM, P.PROJ_NM    
END    