IF EXISTS(SELECT 1 FROM sys.procedures WHERE name ='getOverallTaskDetails' AND TYPE='P')
BEGIN
       DROP PROCEDURE [dbo].[getOverallTaskDetails]
END
GO

CREATE PROCEDURE [dbo].[getOverallTaskDetails]  
  
@START_DATE DATETIME,  
@END_DATE DATETIME  ,  
@CUSTOMER_ID varchar(MAX) = '-1',  
@PROJECT_ID varchar(MAX) = '-1',  
@TASK_CATEGORY varchar(MAX) = '-1'  
  
AS  
  
BEGIN  
  
DECLARE @skipInternalAuditId INT = (SELECT ID FROM PROJECT_CONFIGURATION_SETTING WHERE SETTING_NAME = 'SKIP INTERNAL AUDIT' AND ISACTIVE = 1);                
      
WITH AUDITS AS (      
    SELECT      
        T.CUST_ID, T.PROJ_ID, T.ID,T.DESCRIPTION, T.STATUS, T.DUE_DATE, TR.FREQUENCY,ACT.actual_audit_end_date    
    FROM      
        TASK T       
        LEFT JOIN AUDIT_SCHEDULE ASCH ON ASCH.TITLE = T.DESCRIPTION AND ASCH.CUST_ID = T.CUST_ID AND ASCH.PROJ_ID = T.PROJ_ID       
            AND ASCH.ISACTIVE = 1 AND (T.PARENT_TASK_ID = ASCH.TASK_ID OR T.ID = ASCH.TASK_ID)     
  LEFT JOIN TASK_RECURRENCE TR ON T.ID = TR.TASK_ID AND TR.ISACTIVE = 1    
        LEFT JOIN AUDIT_SCHEDULE_REF ASREF ON ASREF.AUDIT_SCHEDULE_ID = ASCH.ID AND ASREF.ISACTIVE = 1      
        LEFT JOIN AUDIT_CHECKLIST_EXECUTION_SUMMARY ACT ON T.ID = ACT.ASSESSMENT_ID AND ACT.ISACTIVE = 1      
    WHERE      
        T.STATUS NOT IN ('CANCELLED') AND T.ISACTIVE = 1 AND T.DUE_DATE IS NOT NULL AND ISNULL(T.IS_DRAFT, 0) = 0 
  AND T.TASK_CATEGORY_ID in (select * from fn_getParameterTableOptionIds('AUDIT_CATEGORY'))       
        AND COALESCE(T.SCHEDULED_START_DATE, T.DUE_DATE) BETWEEN @START_DATE AND @END_DATE      
    GROUP BY      
        T.CUST_ID, T.PROJ_ID, T.ID,T.DESCRIPTION, T.STATUS, T.DUE_DATE, TR.FREQUENCY, ACT.actual_audit_end_date  
)      
      
SELECT         
    C.CUST_NM, P.PROJ_NM,       
    ISO_STANDARDS = STUFF((      
        SELECT ', ' + PIS.STANDARD_NAME      
        FROM PROJECT_ISO_STANDARD PIS       
        INNER JOIN PROJECT_ISO_STANDARD_MAPPING PIM ON PIS.ID = PIM.ISO_STANDARD_ID      
        WHERE PIM.PROJECT_ID = P.PROJ_ID AND PIS.ISACTIVE = 1      
        FOR XML PATH('')), 1, 2, ''),      
    CERTIFICATION_SCOPES = STUFF((      
        SELECT ', ' + PIS.STANDARD_NAME + ' - ' + PCS.SCOPE_NAME      
        FROM PROJECT_CERTIFICATION_SCOPE PCS       
        INNER JOIN PROJECT_CERTIFICATION_SCOPE_MAPPING PCM ON PCS.ID = PCM.CERTIFICATION_SCOPE_ID      
        INNER JOIN PROJECT_ISO_STANDARD PIS ON PIS.ID = PCS.ISO_STANDARD_ID      
        WHERE PCM.PROJECT_ID = P.PROJ_ID AND PCS.ISACTIVE = 1      
        FOR XML PATH('')), 1, 2, ''),      
    CONVERT(VARCHAR, P.START_DATE, 107) AS START_DATE,      
    CONVERT(VARCHAR, P.END_DATE, 107) AS END_DATE,      
    HEADCOUNT = (SELECT COUNT(*) FROM PROJ_RESOURCE PR WHERE PR.PROJ_ID = P.PROJ_ID AND PR.BILL_FLG =1 AND PR.CURR_INDC ='Y' AND PR.END_DATE >= GETDATE()),      
    AUDIT_TITLE = A.DESCRIPTION,      
    AUDIT_STATUS = A.STATUS,      
    LAST_AUDITED_DATE = CONVERT(VARCHAR, A.actual_audit_end_date, 107),      
    FREQUENCY = A.FREQUENCY,      
    AUDITS_PLANNED = (SELECT COUNT(ID) FROM AUDITS WHERE STATUS NOT IN ('CANCELLED','COMPLETED') AND CUST_ID = C.CUST_ID AND PROJ_ID = P.PROJ_ID),      
    AUDITS_COMPLETED = (SELECT COUNT(ID) FROM AUDITS WHERE STATUS IN ('COMPLETED') AND CUST_ID = C.CUST_ID AND PROJ_ID = P.PROJ_ID),      
    P.PROJ_ID, C.CUST_ID      
FROM       
    PROJECT P       
INNER JOIN       
    CUSTOMER C ON P.CUST_ID = C.CUST_ID        
LEFT JOIN       
    AUDITS A ON A.PROJ_ID = P.PROJ_ID AND A.ID = (SELECT TOP 1 ID FROM AUDITS WHERE PROJ_ID = P.PROJ_ID ORDER BY ID DESC)      
LEFT JOIN       
    TASK T ON T.ID = A.ID AND T.ISACTIVE = 1 AND ISNULL(T.STATUS,'')!='CANCELLED' AND ISNULL(T.IS_DRAFT, 0) = 0      
    
WHERE       
 P.PROJ_ID NOT IN (SELECT PROJ_ID FROM PROJECT_CONFIGURATION_DATA WHERE ISACTIVE = 1 AND IS_APPROVED = 1 AND CONFIGURATION_SETTING_ID = @skipInternalAuditId  
 AND END_DATE IS NULL OR END_DATE > GETDATE())      
    AND COALESCE(T.SCHEDULED_START_DATE, T.DUE_DATE) BETWEEN @START_DATE AND @END_DATE      
    AND ((@CUSTOMER_ID = '-1' AND @PROJECT_ID = '-1')      
        OR (@CUSTOMER_ID <> '-1' AND @PROJECT_ID = '-1' AND C.CUST_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@CUSTOMER_ID, ',')))      
        OR (@CUSTOMER_ID <> '-1' AND @PROJECT_ID <> '-1' AND P.PROJ_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@PROJECT_ID, ','))))      
    AND (@TASK_CATEGORY = '-1' OR T.TASK_CATEGORY_ID IN (SELECT * FROM [DBO].[FN_SPLITSTRING](@TASK_CATEGORY, ',')))      
GROUP BY      
    C.CUST_NM, P.PROJ_NM, P.START_DATE, P.END_DATE, P.PROJ_ID, C.CUST_ID, A.DESCRIPTION, A.STATUS, A.ID, A.DUE_DATE, A.FREQUENCY  ,A.actual_audit_end_date  
ORDER BY       
    P.PROJ_NM, C.CUST_NM      
      
END      
GO
