//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNTRY_WEEKEND
    {
        public short CNTRY_ID { get; set; }
        public byte DAY_FROM { get; set; }
        public byte DAY_TO { get; set; }
    
        public virtual CNTRY_INFO CNTRY_INFO { get; set; }
    }
}
