//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPLIANCE_TRAINING_ASSESSMENT_HEADER
    {
        public int ID { get; set; }
        public string COMPLIANCE_TRAINING_TITLE { get; set; }
        public Nullable<int> TOTAL_QUESTIONS { get; set; }
        public Nullable<int> TOTAL_MARKS { get; set; }
        public Nullable<int> PASS_PERCENTAGE { get; set; }
        public Nullable<System.DateTime> COMPLIANCE_PERIOD_START_DATE { get; set; }
        public Nullable<System.DateTime> COMPLIANCE_PERIOD_END_DATE { get; set; }
    }
}
