//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURATION
    {
        public int SNO { get; set; }
        public string KEY { get; set; }
        public string VALUE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<bool> IS_ENCRYPT { get; set; }
    }
}
