//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENCY_RATE_CONVERSION
    {
        public int CURRENCY_RATE_CONVERSION_ID { get; set; }
        public short MONTH { get; set; }
        public short YEAR { get; set; }
        public string FROM_CURRENCY_CODE { get; set; }
        public string TO_CURRENCY_CODE { get; set; }
        public Nullable<decimal> CONVERSION_RATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    }
}
