//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_INFO_old
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMP_INFO_old()
        {
            this.BU_INFO = new HashSet<BU_INFO>();
            this.DEPT_INFO = new HashSet<DEPT_INFO>();
            this.EMP_PASSPORT = new HashSet<EMP_PASSPORT>();
            this.PROJECT_EXPENSE = new HashSet<PROJECT_EXPENSE>();
            this.EMP_INFO_old1 = new HashSet<EMP_INFO_old>();
            this.EMP_INFO_old11 = new HashSet<EMP_INFO_old>();
            this.EMP_SKILLSET_MATRIX = new HashSet<EMP_SKILLSET_MATRIX>();
            this.PROJ_RESOURCE = new HashSet<PROJ_RESOURCE>();
            this.PROJ_RESOURCE1 = new HashSet<PROJ_RESOURCE>();
            this.PROJ_RESOURCE2 = new HashSet<PROJ_RESOURCE>();
            this.PROJ_RESOURCE3 = new HashSet<PROJ_RESOURCE>();
            this.PROJ_RESOURCE4 = new HashSet<PROJ_RESOURCE>();
            this.PROJ_TIMESHEET = new HashSet<PROJ_TIMESHEET>();
            this.PROJECT_NEW = new HashSet<PROJECT_NEW>();
            this.PROJECT_NEW1 = new HashSet<PROJECT_NEW>();
            this.PROJECTs = new HashSet<PROJECT>();
            this.PROJECTs1 = new HashSet<PROJECT>();
            this.PROJECTs2 = new HashSet<PROJECT>();
            this.PROJECTs3 = new HashSet<PROJECT>();
            this.RESRC_RQST = new HashSet<RESRC_RQST>();
            this.RESRC_RQST1 = new HashSet<RESRC_RQST>();
            this.RESRC_RQST_WF = new HashSet<RESRC_RQST_WF>();
            this.RESRC_RQST_WF1 = new HashSet<RESRC_RQST_WF>();
            this.DEPT_INFO1 = new HashSet<DEPT_INFO>();
        }
    
        public int EMP_ID { get; set; }
        public short BASE_CNTRY_ID { get; set; }
        public int MANAGER_EMP_ID { get; set; }
        public int REVIEWER_EMP_ID { get; set; }
        public string EMPL_TYPE { get; set; }
        public string FRST_NM { get; set; }
        public string MIDDLE_NM { get; set; }
        public string LAST_NM { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public System.DateTime DOJ { get; set; }
        public Nullable<System.DateTime> DOR { get; set; }
        public string LEVEL { get; set; }
        public string TITLE { get; set; }
        public string EXPERIENCE { get; set; }
        public string EMAIL_ID { get; set; }
        public string MOBILE_NBR { get; set; }
        public bool POTENTIAL_TO_BILL { get; set; }
        public string UNBILL_CLASSIFY { get; set; }
        public string EMP_ROLE { get; set; }
        public string EMP_BAS_ROLE { get; set; }
        public string APPRAISAL_RATING { get; set; }
        public string PROMOTION_INFO { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
        public Nullable<bool> SUPERADMIN { get; set; }
        public string EMP_CSP_ROLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BU_INFO> BU_INFO { get; set; }
        public virtual CNTRY_INFO CNTRY_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPT_INFO> DEPT_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_PASSPORT> EMP_PASSPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_EXPENSE> PROJECT_EXPENSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_INFO_old> EMP_INFO_old1 { get; set; }
        public virtual EMP_INFO_old EMP_INFO_old2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_INFO_old> EMP_INFO_old11 { get; set; }
        public virtual EMP_INFO_old EMP_INFO_old3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_SKILLSET_MATRIX> EMP_SKILLSET_MATRIX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_RESOURCE> PROJ_RESOURCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_RESOURCE> PROJ_RESOURCE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_RESOURCE> PROJ_RESOURCE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_RESOURCE> PROJ_RESOURCE3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_RESOURCE> PROJ_RESOURCE4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_TIMESHEET> PROJ_TIMESHEET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_NEW> PROJECT_NEW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_NEW> PROJECT_NEW1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT> PROJECTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT> PROJECTs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT> PROJECTs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT> PROJECTs3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_RQST> RESRC_RQST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_RQST> RESRC_RQST1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_RQST_WF> RESRC_RQST_WF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_RQST_WF> RESRC_RQST_WF1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPT_INFO> DEPT_INFO1 { get; set; }
    }
}
