//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_PASSPORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMP_PASSPORT()
        {
            this.VISA_DETAILS = new HashSet<VISA_DETAILS>();
        }
    
        public int PASSPORT_ID { get; set; }
        public string EMP_ID { get; set; }
        public short COUNTRY_ID { get; set; }
        public string PASSPORT_NO { get; set; }
        public System.DateTime VALID_FROM { get; set; }
        public System.DateTime VALID_TO { get; set; }
        public string REMARKS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string PLACE_OF_ISSUE { get; set; }
    
        public virtual CNTRY_INFO CNTRY_INFO { get; set; }
        public virtual EMP_INFO EMP_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISA_DETAILS> VISA_DETAILS { get; set; }
    }
}
