//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXECUTION_IMPACT_MAPPING
    {
        public int ID { get; set; }
        public int TEST_ID { get; set; }
        public string IMPACTING_ATTRIBUTES { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    }
}
