//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKP_RIMBS_PRE_DEFINED_AMT
    {
        public short RIMBS_PRE_DEFINED_ID { get; set; }
        public short RIMBS_TYPE_ID { get; set; }
        public short CNTRY_ID { get; set; }
        public short RIMBS_CRNCY_ID { get; set; }
        public System.DateTime START_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public string CURR_INDC { get; set; }
        public decimal RIMBS_AMT { get; set; }
    
        public virtual CNTRY_INFO CNTRY_INFO { get; set; }
        public virtual CRNCY_INFO CRNCY_INFO { get; set; }
        public virtual RIMBS_TYPE RIMBS_TYPE { get; set; }
    }
}
