//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJECT()
        {
            this.BILLING_CYCLE = new HashSet<BILLING_CYCLE>();
            this.EMP_PROJ_ROLE_MAP = new HashSet<EMP_PROJ_ROLE_MAP>();
            this.PROJ_RESOURCE = new HashSet<PROJ_RESOURCE>();
            this.PROJ_RESRC_TIME_ENTRY = new HashSet<PROJ_RESRC_TIME_ENTRY>();
            this.PROJ_REV = new HashSet<PROJ_REV>();
            this.PROJ_ROLE_MAP_BILLING = new HashSet<PROJ_ROLE_MAP_BILLING>();
            this.PROJ_TIMESHEET = new HashSet<PROJ_TIMESHEET>();
            this.PROJECT_MILESTONE = new HashSet<PROJECT_MILESTONE>();
            this.SOW_INFO = new HashSet<SOW_INFO>();
            this.RESRC_RIMBS_OTHERS = new HashSet<RESRC_RIMBS_OTHERS>();
            this.RESRC_RQST = new HashSet<RESRC_RQST>();
            this.USER_RIGHTS = new HashSet<USER_RIGHTS>();
        }
    
        public string PROJ_ID { get; set; }
        public int CUST_ADDR_ID { get; set; }
        public short BILL_CRNCY_ID { get; set; }
        public string PROJ_NM { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public bool BILL_TYPE { get; set; }
        public string PROC_TYPE { get; set; }
        public string LVL_1_APPR_EMP_ID { get; set; }
        public string LVL_2_APPR_EMP_ID { get; set; }
        public string LVL_3_APPR_EMP_ID { get; set; }
        public string LVL_4_APPR_EMP_ID { get; set; }
        public string PROJ_BUHEAD_EMP_ID { get; set; }
        public string PROJ_DM_EMP_ID { get; set; }
        public string PROJ_PM_EMP_ID { get; set; }
        public string PROJ_AM_EMP_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
        public Nullable<short> DEPT_ID { get; set; }
        public string CUST_ID { get; set; }
        public Nullable<short> BU_ID { get; set; }
        public string PARENT_PROJ_ID { get; set; }
        public string PROJ_ALIAS_NM { get; set; }
        public string CUST_ID_S { get; set; }
        public string BILL_CRNCY { get; set; }
        public string DEPT { get; set; }
        public string BU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILLING_CYCLE> BILLING_CYCLE { get; set; }
        public virtual BU_INFO BU_INFO { get; set; }
        public virtual CRNCY_INFO CRNCY_INFO { get; set; }
        public virtual CUST_ADDR CUST_ADDR { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual DEPT_INFO DEPT_INFO { get; set; }
        public virtual DEPT_INFO DEPT_INFO1 { get; set; }
        public virtual EMP_INFO EMP_INFO { get; set; }
        public virtual EMP_INFO EMP_INFO1 { get; set; }
        public virtual EMP_INFO EMP_INFO2 { get; set; }
        public virtual EMP_INFO EMP_INFO3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_PROJ_ROLE_MAP> EMP_PROJ_ROLE_MAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_RESOURCE> PROJ_RESOURCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_RESRC_TIME_ENTRY> PROJ_RESRC_TIME_ENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_REV> PROJ_REV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_ROLE_MAP_BILLING> PROJ_ROLE_MAP_BILLING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_TIMESHEET> PROJ_TIMESHEET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_MILESTONE> PROJECT_MILESTONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOW_INFO> SOW_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_RIMBS_OTHERS> RESRC_RIMBS_OTHERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_RQST> RESRC_RQST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_RIGHTS> USER_RIGHTS { get; set; }
    }
}
