//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_PREFERENCE
    {
        public string CUST_ID { get; set; }
        public string PROJ_ID { get; set; }
        public string PREFERENCE_TITLE { get; set; }
        public bool ALLOW { get; set; }
    }
}
