//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJ_ROLE_BILLING_ALLOCATION
    {
        public int PROJ_RESOURCE_BILLING_ALLOCATION_ID { get; set; }
        public int PROJ_ROLE_MAP_BILLING_ID { get; set; }
        public Nullable<int> SOW_ID { get; set; }
        public short YEAR { get; set; }
        public short MONTH { get; set; }
        public Nullable<decimal> ALLOCATION_WEIGHTAGE { get; set; }
    
        public virtual PROJ_ROLE_MAP_BILLING PROJ_ROLE_MAP_BILLING { get; set; }
        public virtual SOW_INFO SOW_INFO { get; set; }
    }
}
