//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_EXPENSE
    {
        public int PROJECT_EXPENSE_ID { get; set; }
        public int SOW_ID { get; set; }
        public string EMP_ID { get; set; }
        public int EXPENSE_ITEM_ID { get; set; }
        public decimal AMOUNT { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> EXPDATE { get; set; }
    
        public virtual EMP_INFO EMP_INFO { get; set; }
        public virtual SOW_INFO SOW_INFO { get; set; }
    }
}
