//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJ_ROLE_MAP_BILLING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJ_ROLE_MAP_BILLING()
        {
            this.PROJ_RESOURCE_ROLE_MAP_BILLING = new HashSet<PROJ_RESOURCE_ROLE_MAP_BILLING>();
            this.PROJ_ROLE_BILLING_ALLOCATION = new HashSet<PROJ_ROLE_BILLING_ALLOCATION>();
        }
    
        public int PROJ_ROLE_MAP_BILLING_ID { get; set; }
        public string PROJECT_ID { get; set; }
        public Nullable<int> SOW_ID { get; set; }
        public Nullable<short> ROLE_ID { get; set; }
        public Nullable<byte> ROLE_TYPE { get; set; }
        public Nullable<decimal> BILLING_RATE_PER_HOUR { get; set; }
        public Nullable<byte> MAX_BILLING_HOURS_PER_DAY { get; set; }
        public Nullable<byte> CAPPED_HOURS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_RESOURCE_ROLE_MAP_BILLING> PROJ_RESOURCE_ROLE_MAP_BILLING { get; set; }
        public virtual PROJ_ROLE PROJ_ROLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_ROLE_BILLING_ALLOCATION> PROJ_ROLE_BILLING_ALLOCATION { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        public virtual SOW_INFO SOW_INFO { get; set; }
    }
}
