//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJ_ROLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJ_ROLE()
        {
            this.EMP_PROJ_ROLE_MAP = new HashSet<EMP_PROJ_ROLE_MAP>();
            this.PROJ_ROLE_MAP_BILLING = new HashSet<PROJ_ROLE_MAP_BILLING>();
        }
    
        public short PROJ_ROLE_ID { get; set; }
        public string ROLE_NM { get; set; }
        public string ROLE_DESC { get; set; }
        public Nullable<bool> IS_EDITABLE { get; set; }
        public Nullable<bool> ENABLED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_PROJ_ROLE_MAP> EMP_PROJ_ROLE_MAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJ_ROLE_MAP_BILLING> PROJ_ROLE_MAP_BILLING { get; set; }
    }
}
