//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_bk15July2019
    {
        public string PROJ_ID { get; set; }
        public int CUST_ADDR_ID { get; set; }
        public short BILL_CRNCY_ID { get; set; }
        public string PROJ_NM { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public bool BILL_TYPE { get; set; }
        public string PROC_TYPE { get; set; }
        public Nullable<int> LVL_1_APPR_EMP_ID { get; set; }
        public Nullable<int> LVL_2_APPR_EMP_ID { get; set; }
        public Nullable<int> LVL_3_APPR_EMP_ID { get; set; }
        public Nullable<int> LVL_4_APPR_EMP_ID { get; set; }
        public Nullable<int> PROJ_BUHEAD_EMP_ID { get; set; }
        public Nullable<int> PROJ_DM_EMP_ID { get; set; }
        public Nullable<int> PROJ_PM_EMP_ID { get; set; }
        public Nullable<int> PROJ_AM_EMP_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_DATE { get; set; }
        public Nullable<short> DEPT_ID { get; set; }
        public Nullable<int> CUST_ID { get; set; }
        public Nullable<short> BU_ID { get; set; }
        public string PARENT_PROJ_ID { get; set; }
        public string PROJ_ALIAS_NM { get; set; }
    }
}
