//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKILLSET_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SKILLSET_INFO()
        {
            this.EMP_SKILLSET_MATRIX = new HashSet<EMP_SKILLSET_MATRIX>();
            this.RESRC_RQST = new HashSet<RESRC_RQST>();
            this.RESRC_RQST1 = new HashSet<RESRC_RQST>();
            this.RESRC_RQST_SKILLSET = new HashSet<RESRC_RQST_SKILLSET>();
        }
    
        public short SKILLSET_ID { get; set; }
        public string SKILLSET_DISP_NAME { get; set; }
        public string SKILLSET_LONG_NAME { get; set; }
        public string SKILLSET_DESC { get; set; }
        public string SKILLSET_GROUP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_SKILLSET_MATRIX> EMP_SKILLSET_MATRIX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_RQST> RESRC_RQST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_RQST> RESRC_RQST1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESRC_RQST_SKILLSET> RESRC_RQST_SKILLSET { get; set; }
    }
}
