//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAVS.AllocationSystem.WebApi.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_RIGHTS
    {
        public int CLNDR_ID { get; set; }
        public int CLNDR_YEAR { get; set; }
        public int CLNDR_MONTH { get; set; }
        public Nullable<System.DateTime> FORECAST_STARTDATE { get; set; }
        public Nullable<System.DateTime> FORECAST_ENDDATE { get; set; }
        public Nullable<System.DateTime> ACTUAL_STARTDATE { get; set; }
        public Nullable<System.DateTime> ACTUAL_ENDDATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string PROJECT_ID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual PROJECT PROJECT { get; set; }
    }
}
