--------------------------------- QUALITATIVE_ANALYSIS--------------------------------------------------------

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'CSS_QUESTION_REPLIES' AND COLUMN_NAME = 'QUALITATIVE_CATEGORY')
BEGIN
    ALTER TABLE CSS_QUESTION_REPLIES ADD QUALITATIVE_CATEGORY varchar(20) NULL;
END

GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'CSS_QUESTION_REPLIES' AND COLUMN_NAME = 'QUALITATIVE_STATUS')
BEGIN
    ALTER TABLE CSS_QUESTION_REPLIES ADD QUALITATIVE_STATUS varchar(50) NULL;
END

GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'CSS_QUESTION_REPLIES' AND COLUMN_NAME = 'QUALITATIVE_REMARKS')
BEGIN
    ALTER TABLE CSS_QUESTION_REPLIES ADD QUALITATIVE_REMARKS varchar(200)NULL;
END

GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'CSS_QUESTION_REPLIES' AND COLUMN_NAME = 'QUALITATIVE_SUBMITTED')
BEGIN
     ALTER TABLE CSS_QUESTION_REPLIES ADD QUALITATIVE_SUBMITTED bit;
END

GO



IF NOT EXISTS(Select 1 from sys.tables where name ='DROPDOWN_OPTIONS' AND type='U')
BEGIN
CREATE table DROPDOWN_OPTIONS(
ID INT NOT NULL IDENTITY(1,1),
DD_NAME VARCHAR(50),
DD_VALUE VARCHAR(50),
DD_TEXT VARCHAR(50),
CREATED_BY VARCHAR(10),
CREATED_DATE  DATETIME,
UPDATED_BY VARCHAR(10),
UPDATED_DATE DATETIME,
ISACTIVE bit )

END
GO


IF NOT EXISTS (SELECT 1 FROM DROPDOWN_OPTIONS WHERE DD_NAME= 'QUALITATIVE_ANALYSIS')   
 BEGIN
INSERT INTO DROPDOWN_OPTIONS (DD_NAME,DD_VALUE,DD_TEXT,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE,ISACTIVE)
VALUES 

('QUALITATIVE_ANALYSIS','QUALITY_OF_DELIVERY','Quality of Delivery','104744',getdate(),'104744',getdate(),1),

('QUALITATIVE_ANALYSIS','RESOURCE_COMPETENCY','Resource Competency','104744',getdate(),'104744',getdate(),1),

('QUALITATIVE_ANALYSIS','RISK_MGMT_RESPONSIVENESS','Risk Management & Responsiveness','104744',getdate(),'104744',getdate(),1),

('QUALITATIVE_ANALYSIS','TEAM_COLLABORATION','Team Commitment & Collaboration','104744',getdate(),'104744',getdate(),1),

('QUALITATIVE_ANALYSIS','THOUGHT_LEADERSHIP','Thought Leadership','104744',getdate(),'104744',getdate(),1),

('QUALITATIVE_ANALYSIS','TIMELINE_ADHERENCE','Timeline Adherence','104744',getdate(),'104744',getdate(),1),

('QUALITATIVE_ANALYSIS','RESOURCE_FULFILLMENT','Timely Resource Fulfillment','104744',getdate(),'104744',getdate(),1)


END

GO


Declare @RESOURCEID int = 827
Declare @EMPID varchar(10) = '104744'
Declare @RescourceName varchar(250) = 'VOC > Qualitative Analysis'

If not exists(select 1 from  APP_CONTROLS where RESOURCE_NAME = @RescourceName)
begin 
insert into APP_CONTROLS (RESOURCE_ID,RESOURCE_TYPE,RESOURCE_NAME,COMMENTS,CREATED_BY,CREATED_DATE,UPDATED_BY,UPDATED_DATE,ISACTIVE)
values (@RESOURCEID,'Control',@RescourceName,null,@EMPID,GETDATE(),@EMPID,GETDATE(),1)
set @RESOURCEID = (select RESOURCE_ID from  APP_CONTROLS where RESOURCE_NAME = @RescourceName )
end

If not exists(select 1 from  APP_ACCESS_CONTROLS where RESOURCE_ID = @RESOURCEID)
begin 
insert into  APP_ACCESS_CONTROLS
(RESOURCE_ID,ROLE_ID,EMP_ID,CUST_ID,PROJ_ID,COMMENTS,CREATED_BY,UPDATED_BY,VIEW_ACCESS,CREATE_ACCESS,
EDIT_ACCESS,DELETE_ACCESS,DEFAULT_ACCESS,ISACTIVE,ACCESS_LEVEL,CREATED_DATE,UPDATED_DATE)
values 
(@RESOURCEID,1,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,2,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,3,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,4,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,5,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,6,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,7,'','','',null,@EMPID,@EMPID,1,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,8,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,9,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,10,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,11,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,12,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate()),
(@RESOURCEID,13,'','','',null,@EMPID,@EMPID,0,0,0,0,0,1,1,getdate(),getdate())

End

GO